### ISSUE TITLE
请问我使用的druid作为连接池  但是连接池的参数我如何配置呢

### ISSUE THREAD

**Issue by hanzhenchaoGit** [baomidou/dynamic-datasource-spring-boot-starter#1]
请问我使用的druid作为连接池  但是连接池的参数我如何配置呢 比如连接池初始大小之类的配置

**Comment by huayanYu** [comment]
暂时还不支持,计划1.30支持。

**Comment by hanzhenchaoGit** [comment]
什么时候能更新呢  准备自己搞一套框架  以这个动态数据源作为基础呢

**Comment by huayanYu** [comment]
预计下周天吧，你先用着。 参数这个不影响暂时，支持了加上就是了。

**Comment by hanzhenchaoGit** [comment]
对 就是想着扩展性能好一些 原先druid starter能支持灵活配置的东西也都能支持了 就完美许多了

**Comment by huayanYu** [comment]
恩，下周吧。我要先发个1.2.0的版本,支持一下spel的切面。

**Comment by huayanYu** [comment]
@hanzhenchaoGit  提供了支持，明天应该能同步1.2.0。
