### ISSUE TITLE
如果是JPA并且主从库使用不同数据库类型就无法支持

### ISSUE THREAD

**Issue by hzy0769** [baomidou/dynamic-datasource-spring-boot-starter#103]
我测试发现如果ORM框架用的是JPA(Hibernate)，并且主库与从库使用的数据库类型不一样，那么从库的访问会异常，主库可正常访问。我猜测会不会是spring.jpa.properties.hibernate.dialect这个配置也需要实现动态切换？是不是需要在@EnableJpaRepositories配置里面重写entityManagerFactory，自己初始化entityManager？

**Comment by huayanYu** [comment]
jpa一直就没支持过。
你可以研究下PR。
