### ISSUE TITLE
springboot maven 多模块下无法使用

### ISSUE THREAD

**Issue by qq812033101** [baomidou/dynamic-datasource-spring-boot-starter#105]
当前springboot 版本 2.15 采用 maven 多模块的方式构建项目
项目构建中，我的数据源是自己写的配置类去实现，并且排除了MybatisAutoConfiguration这个自动配置类

动态数据源的版本为当前最新版本

**Comment by huayanYu** [comment]
自己写的自己去排查啊。 啥详细信息都没有，怎么帮你？
