### ISSUE TITLE
从数据源宕机，读写分离插件不会切换到其他数据源

### ISSUE THREAD

**Issue by tfwx** [baomidou/dynamic-datasource-spring-boot-starter#108]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.1.3.RELEASE

Starter Version(required): 2.5.3

# Describe

使用Mybatis-Plus使用读写分离和多数据源时，配置了1个主数据源
和1个从数据源，在测试代码中循环查询SQL，在执行查询SQL时，强行停掉从数据库后，发现执行失败，并且一直在建立与刚刚停掉的从数据库的连接，并没有自动切换到其他可用数据源上

Expected Result: 希望发现从数据库宕机后，自动切换到其他可用数据源

Actual Result:  从数据源的不可用导致整个应用程序在执行查询时都不可用

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
正在做类似的事情，但是比较难设计。

**Comment by tfwx** [comment]
> 正在做类似的事情，但是比较难设计。

好的，网上的读写分离方案都是代码层面最简单的读写分离，并不保证可用。希望以后能支持。
