### ISSUE TITLE
无法配置Druid支持同时执行 使用分号分割的多条sql语句

### ISSUE THREAD

**Issue by cc69001210** [baomidou/dynamic-datasource-spring-boot-starter#111]
# Enviroment

JDK Version(required): 
1.8.0_112
SpringBoot Version(required): 
2.2.0.RELEASE
Starter Version(required):
2.4.2
# Describe

在使用druid连接池的时候，一个sql语句为使用“;”分割的多条语句，在执行的时候报错：Error updating database.  Cause: java.sql.SQLException: sql injection violation, multi-statement not allow : 

按照码云文档预览中：
https://gitee.com/baomidou/dynamic-datasource-spring-boot-starter/wikis/pages?sort_id=1030570&doc_id=147063

配置了允许执行分号分割语句：
spring.datasource.dynamic.druid.wall.multiStatementAllow=true
但是不起作用

查看DuridConfig源码发现，其源码中并没有multiStatementAllow属性。

想咨询下是否有其余的配置。

**Comment by huayanYu** [comment]
建议升级。
