### ISSUE TITLE
class com.alibaba.druid.pool.DruidDataSource cannot be cast to class com.baomidou.dynamic.datasource.DynamicRoutingDataSource (com.alibaba.druid.pool.DruidDataSource and com.baomidou.dynamic.datasource.DynamicRoutingDataSource are in unnamed module of loader 'app')

### ISSUE THREAD

**Issue by Rickykurt** [baomidou/dynamic-datasource-spring-boot-starter#114]
# Enviroment

JDK Version(required): 
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

SpringBoot Version(required): 

2.2.0.RELEASE
Starter Version(required):
2.5.7
# Describe
![image](https://user-images.githubusercontent.com/1176984/68279821-3663ac00-00af-11ea-8e93-5a23da1647a6.png)
调用LoadController中的now方法提示
![image](https://user-images.githubusercontent.com/1176984/68280027-aa9e4f80-00af-11ea-9c94-52d30f9eaea1.png)
springboot 数据库初始配置如下：
spring.datasource.dynamic.datasource.master.url=jdbc:mysql://192.168.1.123:3306/gd?characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull
spring.datasource.dynamic.datasource.master.username=root
spring.datasource.dynamic.datasource.master.password=123456
spring.datasource.dynamic.datasource.master.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.dynamic.datasource.master.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.dynamic.datasource.master.hikari.idle-timeout=10000
spring.datasource.dynamic.datasource.master.druid.initConnectionSqls=set names utf8mb4

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
无法重现
