### ISSUE TITLE
updateBatchById 无法切换数据源

### ISSUE THREAD

**Issue by likeswinds** [baomidou/dynamic-datasource-spring-boot-starter#116]
# Enviroment

JDK Version(required):  1.8
SpringBoot Version(required): 2.1.7

Starter Version(required): 2.5.6

# Describe
通过实现Interceptor类来切换数据源，调用service.updateBatchById 或saveOrUpdateBatch方法时，数据源未切换，updateById可正常切换

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
自己实现的自己排查问题啊。
