### ISSUE TITLE
是否支持hikari 全局配置

### ISSUE THREAD

**Issue by zzg19901210** [baomidou/dynamic-datasource-spring-boot-starter#12]
# Enviroment

JDK Version: 

SpringBoot Version: 

Starter Version:

# Describe

Expected Result: 
 
Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
暂时不支持，以后会支持。预计2周内吧。

**Comment by huayanYu** [comment]
明天试试2.4.0. 全局不太行，和druid不一样。 现在只能挨个设置
