### ISSUE TITLE
动态数据源报错

### ISSUE THREAD

**Issue by Jkanon** [baomidou/dynamic-datasource-spring-boot-starter#120]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.1.3.RELEASE

Starter Version(required):2.5.7

# Describe
在mapper上应用@DS注解报以下错误
Can not set final java.lang.Class field com.baomidou.mybatisplus.core.override.MybatisMapperProxy.mapperInterface to org.springframework.aop.framework.JdkDynamicAopProxy

放在service上是没问题的

**Comment by huayanYu** [comment]
强制配置成cglib代理
