### ISSUE TITLE
是否必须加载 HikariCP 驱动？

### ISSUE THREAD

**Issue by alxe1528** [baomidou/dynamic-datasource-spring-boot-starter#125]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.2.1

Starter Version(required):2.5.7

# Describe
项目启动的时候报HikariCP 驱动没找到，但是配置文件没有配置HikariCP相关的东西，pom 加上HikariCP就不报错了~~用的试druid

**Comment by huayanYu** [comment]
仔细看文档
