### ISSUE TITLE
多主多从数据库，支持配置规则负载均衡吗

### ISSUE THREAD

**Issue by zhouchengfei** [baomidou/dynamic-datasource-spring-boot-starter#128]
# Enviroment

JDK Version(required): 

SpringBoot Version(required): 

Starter Version(required):

# Describe

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
支持，看文档约定3
