### ISSUE TITLE
是否可以支持懒加载数据库datasource

### ISSUE THREAD

**Issue by Timyooo** [baomidou/dynamic-datasource-spring-boot-starter#132]
例如：DynamicRoutingDataSource 增加一个属性Map<String, DataSourceProperty> 如果dataSourceMap中不存在目标ds，则从上面map中找到数据库配置来创建Datasource

**Comment by huayanYu** [comment]
为什么要这么做？ 已经支持了从外部创建。 你把Map<String, DataSourceProperty> 放到你自己的外部，需要的时候添加数据源不就可以。

**Comment by Timyooo** [comment]
实现都可以实现，就是业务代码中还要来判断一下是不是已经加载了目标数据源，有点不简洁。
