### ISSUE TITLE
为什么在嵌套情况下，ServiceA调取@Autwrite ServiceB，依然使用的是ServiceA指定的@DS?

### ISSUE THREAD

**Issue by Lisichenghah** [baomidou/dynamic-datasource-spring-boot-starter#134]
@DS("A")
public ServiceA{
@Autowrite
ServiceB serviceB;
public void test(){
ServiceA.insert();
serviceB.insert();
}
}

然后会报b表不存在A库

**Comment by huayanYu** [comment]
检查是否有事务。

**Comment by dpp66** [comment]
如果在public ServiceA方法上面加上@Transactional标签，这种情况下不能自动切换数据源，怎么解决？
