### ISSUE TITLE
已经支持基于seata的分布式事务

### ISSUE THREAD

**Issue by huayanYu** [baomidou/dynamic-datasource-spring-boot-starter#137]
### 详情请查看wiki，有相关文档和案例。

https://github.com/baomidou/dynamic-datasource-spring-boot-starter/wiki/Integration-With-Seata

如果觉得本项目对你有用，可以请作者喝杯咖啡。

https://github.com/baomidou/dynamic-datasource-spring-boot-starter/wiki/Donate

**Comment by CSuperC** [comment]
@huayanYu 能给代码，开个branch提交的权限么，你这代码，分布式事务的样例，不好，我帮你搞一个好的，对接http的 ，我本地已经走通了

**Comment by huayanYu** [comment]
> @huayanYu 能给代码，开个branch提交的权限么，你这代码，分布式事务的样例，不好，我帮你搞一个好的，对接http的 ，我本地已经走通了

直接PR上来嘛。

**Comment by huayanYu** [comment]
dynamic-datasource-sring-boot-starter 组件内部开启seata后会自动使用DataSourceProxy来包装DataSource,所以需要以下方式来保持兼容

1.如果你引入的是seata-all,请不要使用@EnableAutoDataSourceProxy注解。

2.如果你引入的是seata-spring-boot-starter 请关闭自动代理。

```
seata:
  enable-auto-data-source-proxy: false
```
