### ISSUE TITLE
多数据源的主从配置

### ISSUE THREAD

**Issue by tkec** [baomidou/dynamic-datasource-spring-boot-starter#138]
MasterSlaveAutoRoutingPlugin可以支持一个工程中有一个主从库，如果有多组主从数据源，比如User和Article是不同的源，每个源有1组2从，有办法实现吗？

**Comment by huayanYu** [comment]
可以啊，注入数据源，可以获得所有数据源。 那么只是少一个规则，写配置文件或者写死都可以

**Comment by tkec** [comment]
比如user有master_user、slave_user_1、slave_user_2，article有master_article、slave_article_1、slave_article_2，参考MasterSlaveAutoRoutingPlugin里面怎么修改实现呢？一个sql请求，怎么知道需要哪组数据源呢？

**Comment by huayanYu** [comment]
@tkec  必须得加注解了，比如某个方法上加@DS("article"),  插件注入DynamicRoutingDataSource 可以获得所有数据源，可以再根据需求再分组。DynamicDataSourceContextHolder.peek()可以获得当前选择切换的组如article。
 那么有了所有数据源，也知道当前是article组，再根据当前方法是不是查询方法，就能返回对应数据源了。
