### ISSUE TITLE
是否默认支持主写，从读的

### ISSUE THREAD

**Issue by RobinsChens** [baomidou/dynamic-datasource-spring-boot-starter#142]
# Enviroment

JDK Version(required): 

SpringBoot Version(required): 

Starter Version(required):

# Describe

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
只支持mybatis基于插件的，仔细看文档
