### ISSUE TITLE
关于增了事务注解后，读取库错误的问题

### ISSUE THREAD

**Issue by phoema** [baomidou/dynamic-datasource-spring-boot-starter#143]
# Enviroment
Windows10
JDK Version(required): 
1.8
SpringBoot Version(required): 
2.2.2
Starter Version(required):
最新版

# Describe
注：不需要支持多库事务，在事务开启后，能够正常切换数据库进行读取即可

你好，我尝试在Demo：dynamic-mybatisplus3-sample
中增加@Transactional注解
发现一些不理解的地方
我将库设置为master，test等库，库结构一致
Service层的类注解为@DS("test")
在测试类中插入测试数据
在加了事务注解@Transactional后尝试读取
发现并没有预期读取到test库的数据，直接读取的master库，
相关测试代码请见附件
[dynamic-mybatisplus3-sample.zip](https://github.com/baomidou/dynamic-datasource-spring-boot-starter/files/4247797/dynamic-mybatisplus3-sample.zip)

![image](https://user-images.githubusercontent.com/8730272/75209695-e291e580-57b9-11ea-83ec-beff52d0d200.png)

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
不支持： 你需要理解底层事务注解做了什么。  复用连接。
这个是spring底层设计，无法更改

**Comment by phoema** [comment]
你好，我的测试结果是：
即使内部DS全部注解的test库，外面包裹了@transactional注解后，依然走master库，不应该统一走test库吗？

**Comment by phoema** [comment]
可能我理解的不太深入
我想确认一个问题
用了DS注解，所以地方不能再用@transactional注解吗？

**Comment by huayanYu** [comment]
@phoema 在单体项目中如果使用事务注解会复用连接， 谁第一个开启的事物，后面所有连接都会复用，不能切换数据源。
你的需求可以在最外层同时加事务注解和@DS("test"),那么底下都是test。

或者使用分布式事务方案集成seata，WIKI有文档和示例。

**Comment by phoema** [comment]
我在测试用例外部加了DS注解，强制test库，但是依然获取的master数据，是说按照master开启的事务吗？我查了之前的issue，说事务注解先于DS注解启动了，所以拿到了默认的master数据源，是这个原理吗？

![image](https://user-images.githubusercontent.com/8730272/75599197-91e1fb80-5add-11ea-8c86-a8a39a8558f6.png)

**Comment by phoema** [comment]
@Test
  public void testAddUser() {
    User user = new User();
    user.setName("Test" + random.nextInt());
    user.setAge(random.nextInt(100));
    // test库插入
    userService.addUser(user);
    // test库有ID2，master库不存在
    userService.addUser(user);
    user.setName("Master" + random.nextInt());
    // master库插入
    userService.addUserNoTran(user);

  }

  @DS("test")
  @Test
  @Transactional
  public void testSelectUser() {
    //加了事务，预期是Test用户，实际是Master用户，直接读取了Master库
    User user1 = userService.getById(1);
    //加了事务，预期是Test用户，应该获取ID2，实际是Master用户，直接读取了Master库，导致无数据
    User user2 = userService.getById(2);
    //加了事务，预期是Test用户，实际是Master用户，直接读取了Master库
    // list函数加不加DS注解并没有用，list函数加不加@Transactional也并没有用
    List<User> list = userService.list();
    System.out.println(list.size());
    List<User> list2 = userService.listNoTran();
    System.out.println(list2.size());

  }

**Comment by phoema** [comment]
@DS("test")
  @Test
  @Transactional
  public void testSelectUser() {
    //加了事务，预期是Test用户，实际是Master用户，直接读取了Master库
    User user1 = userService.getById(1);
    //加了事务，预期是Test用户，应该获取ID2，实际是Master用户，直接读取了Master库，导致无数据
    User user2 = userService.getById(2);
    //加了事务，预期是Test用户，实际是Master用户，直接读取了Master库
    // list函数加不加DS注解并没有用，list函数加不加@Transactional也并没有用
    List<User> list = userService.list();
    System.out.println(list.size());
    List<User> list2 = userService.listNoTran();
    System.out.println(list2.size());

  }

**Comment by huayanYu** [comment]
不再回复，提示不要在测试方法上加注解。
