### ISSUE TITLE
2.5.8版本启动报错BasicDataSourceCreator' that could not be found.

### ISSUE THREAD

**Issue by zhaofangcheng** [baomidou/dynamic-datasource-spring-boot-starter#144]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.2.2

Starter Version(required):2.5.8/3.3.0

# Describe

Description:

Parameter 2 of constructor in com.xxx.controller.LoadController required a bean of type 'com.baomidou.dynamic.datasource.creator.BasicDataSourceCreator' that could not be found.

Action:

Consider defining a bean of type 'com.baomidou.dynamic.datasource.creator.BasicDataSourceCreator' in your configuration.

Disconnected from the target VM, address: '127.0.0.1:53072', transport: 'socket'

Process finished with exit code 0

pom引入没有问题，jar下载也是完整的异常的包名和类在jar中都存在，maven编译可以通过，启动报错。

**Comment by huayanYu** [comment]
似乎你注入了BasicDataSourceCreator。 要3.0.0才能注入吧。

**Comment by zhaofangcheng** [comment]
> 似乎你注入了BasicDataSourceCreator。 要3.0.0才能注入吧。

master下的
https://github.com/baomidou/dynamic-datasource-spring-boot-starter/tree/master/samples/dynamic-add-remove-datasource/src/main 直接拿来测的，没做过修改，master适用于哪个版本呢？ #113 也是这个问题，为什么都关闭了呢？

**Comment by huayanYu** [comment]
3.0.0

**Comment by zhaofangcheng** [comment]
> 3.0.0

升到3.0.0问题依旧，3.0有需要特殊注意的地方吗，是否还有其他需要配置的地方呢？
