### ISSUE TITLE
多租户场景 是通过filter手动设置DynamicDataSourceContextHolder 的.如果在service层开一个新的线程.  子线程再操作数据库就无法切换数据源.

### ISSUE THREAD

**Issue by siaron** [baomidou/dynamic-datasource-spring-boot-starter#147]
# Enviroment
macos

JDK Version(required): 
jdk1.8

SpringBoot Version(required): 
1.5.x

Starter Version(required):
3.0.1

# Describe
多租户场景 是通过filter手动设置DynamicDataSourceContextHolder 的.如果在service层开一个新的线程.  子线程再操作数据库就无法切换数据源. 是不是可以使用`NamedInheritableThreadLocal` 会更好
```
private static final ThreadLocal<Deque<String>> LOOKUP_KEY_HOLDER = new NamedInheritableThreadLocal("dynamicDs") {
    @Override
    protected Object initialValue() {
      return new ArrayDeque();
    }
  };
```

Expected Result: 
子线程可以继承父线程的数据源标识

Actual Result:  
为peek为null

# Steps to reproduce

- Step 1 
![image](https://user-images.githubusercontent.com/13701232/75756279-5b211500-5d6b-11ea-897a-894f1e9d8cd4.png)

- Step 2 
![image](https://user-images.githubusercontent.com/13701232/75756295-6116f600-5d6b-11ea-9ea2-5e4ff5aa225a.png)

- Step 3 

![image](https://user-images.githubusercontent.com/13701232/75756365-7db32e00-5d6b-11ea-8e61-7cb2bbf2863b.png)

**Comment by huayanYu** [comment]
下个版本

**Comment by 0532** [comment]
> 下个版本

hello 这个有开发计划吗 ， 或者有开发的分支了吗 ，我们也想用一下这个功能，可以和你一起测一下

**Comment by siaron** [comment]
@0532  看master 改到过NamedInheritableThreadLocal , 但是又改回了 NamedThreadLocal ,不知道为什么

**Comment by 0532** [comment]
> @0532 看master 改到过NamedInheritableThreadLocal , 但是又改回了 NamedThreadLocal ,不知道为什么

https://github.com/baomidou/dynamic-datasource-spring-boot-starter/issues/200#issue-620640060

可能是这个issue的问题

**Comment by siaron** [comment]
觉得可以增加类似于spring的`LocaleContextHolder`或`RequestContextHolder` 来兼容这种场景.  如同 https://github.com/baomidou/dynamic-datasource-spring-boot-starter/issues/200#issuecomment-631218234  这个描述.

**Comment by cfl520** [comment]
Thread  线程类创建inheritableThreadLocals时会把父线程的对象的值给子线程
--------
  if (inheritThreadLocals && parent.inheritableThreadLocals != null)
            this.inheritableThreadLocals =
                ThreadLocal.createInheritedMap(parent.inheritableThreadLocals);
--------
 private ThreadLocalMap(ThreadLocalMap parentMap) {
            Entry[] parentTable = parentMap.table;
            int len = parentTable.length;
            setThreshold(len);
            table = new Entry[len];

            for (int j = 0; j < len; j++) {
                Entry e = parentTable[j];
                if (e != null) {
                    @SuppressWarnings("unchecked")
                    ThreadLocal<Object> key = (ThreadLocal<Object>) e.get();
                    if (key != null) {
                        Object value = key.childValue(e.value);
                        Entry c = new Entry(key, value);
                        int h = key.threadLocalHashCode & (len - 1);
                        while (table[h] != null)
                            h = nextIndex(h, len);
                        table[h] = c;
                        size++;
                    }
                }
            }
        }
这里的Entry 的value 里的对象会被所有子线程共享
而DynamicDataSourceContextHolder 类的InheritableThreadLocal 值 ArrayDeque 是线程不安全的所有。
多线程会有问题所以改回了NamedThreadLocal

**Comment by cfl520** [comment]
Thread 线程类创建inheritableThreadLocals时会把父线程的对象的值给子线程
Thread 类的init 方法 初始化inheritableThreadLocals对象
---------
if (inheritThreadLocals && parent.inheritableThreadLocals != null)
this.inheritableThreadLocals =
ThreadLocal.createInheritedMap(parent.inheritableThreadLocals);

------------




-----------
private ThreadLocalMap(ThreadLocalMap parentMap) {
Entry[] parentTable = parentMap.table;
int len = parentTable.length;
setThreshold(len);
table = new Entry[len];

        for (int j = 0; j < len; j++) {
            Entry e = parentTable[j];
            if (e != null) {
                @SuppressWarnings("unchecked")
                ThreadLocal<Object> key = (ThreadLocal<Object>) e.get();
                if (key != null) {
                    Object value = key.childValue(e.value);
                    Entry c = new Entry(key, value);
                    int h = key.threadLocalHashCode & (len - 1);
                    while (table[h] != null)
                        h = nextIndex(h, len);
                    table[h] = c;
                    size++;
                }
            }
        }
    }
--------------

InheritableThreadLocal的childValue方法
--------------
protected T childValue(T parentValue) {
        return parentValue;
    }
---------------


这里的Entry 的value 里的对象会被所有子线程共享
而DynamicDataSourceContextHolder 类的InheritableThreadLocal 值 ArrayDeque 是线程不安全的。
多线程会有问题所以改回了NamedThreadLocal

**Comment by cfl520** [comment]
Thread 线程类创建inheritableThreadLocals时会把父线程的对象的值给子线程
Thread 类的init 方法 初始化inheritableThreadLocals对象
`
if (inheritThreadLocals && parent.inheritableThreadLocals != null)
this.inheritableThreadLocals =
ThreadLocal.createInheritedMap(parent.inheritableThreadLocals);

`




`
private ThreadLocalMap(ThreadLocalMap parentMap) {
Entry[] parentTable = parentMap.table;
int len = parentTable.length;
setThreshold(len);
table = new Entry[len];

        for (int j = 0; j < len; j++) {
            Entry e = parentTable[j];
            if (e != null) {
                @SuppressWarnings("unchecked")
                ThreadLocal<Object> key = (ThreadLocal<Object>) e.get();
                if (key != null) {
                    Object value = key.childValue(e.value);
                    Entry c = new Entry(key, value);
                    int h = key.threadLocalHashCode & (len - 1);
                    while (table[h] != null)
                        h = nextIndex(h, len);
                    table[h] = c;
                    size++;
                }
            }
        }
    }
`

InheritableThreadLocal的childValue方法
`
protected T childValue(T parentValue) {
        return parentValue;
    }
`


这里的Entry 的value 里的对象会被所有子线程共享
而DynamicDataSourceContextHolder 类的InheritableThreadLocal 值 ArrayDeque 是线程不安全的。
多线程会有问题所以改回了NamedThreadLocal
