### ISSUE TITLE
oracle sid连接方式不支持  

### ISSUE THREAD

**Issue by ldcmd** [baomidou/dynamic-datasource-spring-boot-starter#150]
连接
spring.datasource.dynamic.datasource.land.url==jdbc:oracle:thin:@17x.1x.1x.16x:1521:XE
报错
![image](https://user-images.githubusercontent.com/25797957/76680038-491f5c00-6620-11ea-977e-0692ea3a7681.png)

**Comment by huayanYu** [comment]
底层不支持我无法处理，请联系druid处理。

**Comment by ldcmd** [comment]
谢谢



发自我的小米手机在 小锅盖 <notifications@github.com>，2020年3月14日 20:22写道：

底层不支持我无法处理，请联系druid处理。



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/baomidou/dynamic-datasource-spring-boot-starter/issues/150#issuecomment-599051226",

"url": "https://github.com/baomidou/dynamic-datasource-spring-boot-starter/issues/150#issuecomment-599051226",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
