### ISSUE TITLE
单元测试时，在@SpringBootTest同级的位置用@DS的注解无效

### ISSUE THREAD

**Issue by remember-5** [baomidou/dynamic-datasource-spring-boot-starter#153]
# Enviroment
mac 10.14.6 
JDK Version(required): 
1.8
SpringBoot Version(required): 
2.2.0
Starter Version(required):
3.0.0
# Describe
单元测试时，在@SpringBootTest同级的位置用@DS的注解无效

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
没被代理。

**Comment by remember-5** [comment]
请问这个要怎么解决？ @huayanYu
