### ISSUE TITLE
外部引用jar，@DS失效

### ISSUE THREAD

**Issue by neozo** [baomidou/dynamic-datasource-spring-boot-starter#156]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.2.0

Starter Version(required):2.5.6

# Describe

引用外部jar时，无法切换数据源

我们的工程用mavene分成了几个模块，通用的模块打成jar给其他用，发现打成jar后，里面的@DS就失效了，有没有什么办法解决

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
没遇到此种场景，没有案例。 可以参考示例代码提供一份案例。

或者自己排查，是不是AOP失效了。

**Comment by neozo** [comment]
问题找到了，调用方加了事务，虽然事务里用的都是同一个库，但是用了事务会导致获取数据源名称为空，强制使用了默认数据源。
