### ISSUE TITLE
请教一下数据源配置不成功的问题

### ISSUE THREAD

**Issue by tuess** [baomidou/dynamic-datasource-spring-boot-starter#158]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.2.6

mybatis-plus-boot-starter  version: '3.3.1'

dynamic-datasource-spring-boot-starter  version: '2.5.8'

# Describe
yml数据源配置如图
![avatar](https://s1.ax1x.com/2020/03/31/GK2enf.png)
service如图
![avatar](https://s1.ax1x.com/2020/03/31/GK2Ect.png)

其它一切正常，启动会报错：Caused by: java.lang.RuntimeException: dynamic-datasource Please check the setting of primary

请教一下大佬是哪里出了问题😂

**Comment by huayanYu** [comment]
自己检查配置格式，没有读到master
