### ISSUE TITLE
非WEB程序不能使用

### ISSUE THREAD

**Issue by cklogic** [baomidou/dynamic-datasource-spring-boot-starter#165]
2.5.4 依赖WebApplicationContext
`
    @Bean
    @ConditionalOnMissingBean
    public DynamicDataSourceCreator dynamicDataSourceCreator(@Autowired WebApplicationContext webApplicationContext) {
        DynamicDataSourceCreator dynamicDataSourceCreator = new DynamicDataSourceCreator();
        dynamicDataSourceCreator.setApplicationContext(webApplicationContext);
        dynamicDataSourceCreator.setDruidGlobalConfig(properties.getDruid());
        dynamicDataSourceCreator.setHikariGlobalConfig(properties.getHikari());
        return dynamicDataSourceCreator;
    }
`

**Comment by huayanYu** [comment]
升级3.0.0稳定版
