### ISSUE TITLE
druid-spring-boot-starte 1.1.21按照您的教程配置404

### ISSUE THREAD

**Issue by fkfgq2008** [baomidou/dynamic-datasource-spring-boot-starter#167]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.2.1

Starter Version(required):mybatis-plus-boot-starter：3.1.0；dynamic-datasource-spring-boot-starter；2.5.3

# Describe
druid-spring-boot-starte 1.1.21按照您的教程配置404
druid-spring-boot-starte 1.1.10按照您的教程配置却可以显示监控

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by chenjunhua8080** [comment]
版本问题

**Comment by fkfgq2008** [comment]
> 版本问题

问题解决了，是这样的，我发现在1.1.0之后，需要增加配置：spring.datasource.druid.stat-view-servlet.enabled=true
因为1.1.0之前好像默认true，但是后面的版本变成了false，所以加上这个配置就其他版本就行了
