### ISSUE TITLE
not support DECLARE (mssql)

### ISSUE THREAD

**Issue by hgp7369** [baomidou/dynamic-datasource-spring-boot-starter#17]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.0.5

Starter Version(required):2.4.0

# Describe
不支持类似语句 "DECLARE @Count as int  = 0"
若不添加setMultiStatementAllow之类会提示
`java.sql.SQLException: sql injection violation, syntax error: syntax error`
若添加之后，会提示:
`java.sql.SQLSyntaxErrorException: unknown token`

**Comment by huayanYu** [comment]
不太明白你的意思，我这个只负责切换数据源，只要切换成功了。后面发生的错误就不是这个项目的原因了。

**Comment by hgp7369** [comment]
> 不太明白你的意思，我这个只负责切换数据源，只要切换成功了。后面发生的错误就不是这个项目的原因了。

嗯嗯，我已经找到原因了，是druid的filters中的wall引起的
