### ISSUE TITLE
深入使用@DS之后，并发所产生的问题

### ISSUE THREAD

**Issue by BeyondTheBlade** [baomidou/dynamic-datasource-spring-boot-starter#170]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.2.2

Starter Version(required):3.0.0

# Describe
在深入使用这个产品之后，用到了一些高级功能，比如自己动态添加数据源等，但是在实际使用的时候发现，在大并发环境下，@DS失效了。希望能和作者讨论下这块产生的原因，github提问不太及时，能否留个QQ交流下。

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
332309254

**Comment by BeyondTheBlade** [comment]
@huayanYu 大佬你的QQ有问题要回答要密码，你加我下845003730

**Comment by BeyondTheBlade** [comment]
大佬，你的QQ加不上，你加下我的吧，845003730




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"小锅盖"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月14日(星期二) 上午9:54
收件人:&nbsp;"baomidou/dynamic-datasource-spring-boot-starter"<dynamic-datasource-spring-boot-starter@noreply.github.com&gt;;
抄送:&nbsp;"林涵鑫"<845003730@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [baomidou/dynamic-datasource-spring-boot-starter] 深入使用@DS之后，并发所产生的问题 (#170)





 
332309254
