### ISSUE TITLE
无法加载到多数据源

### ISSUE THREAD

**Issue by hp88yx** [baomidou/dynamic-datasource-spring-boot-starter#172]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.2.4

Starter Version(required):3.0.4

# Describe
 动态数据源-检测到druid存在,如配置中未指定type,druid会默认配置，只进行到这一步，却没有提示加载到几个数据源

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by hp88yx** [comment]
spring:
  application:
    name: report
  datasource:
    initialization-mode: always
    dynamic:
      primary: account
      datasource:
        account:
          url: jdbc:mysql://Xxx.xx.xx.xx:3306/wowqu_account?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
          username: root
          password: root
          driverClassName:  com.mysql.jdbc.Driver
          continueOnError: false

**Comment by huayanYu** [comment]
先自己断点看一下啊

**Comment by hp88yx** [comment]
spring:
  application:
    name: report
  datasource:
    initialization-mode: always
    dynamic:
      primary: account
      datasource:
        account:
          url: jdbc:mysql://Xxx.xx.xx.xx:3306/wowqu_account?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
          username: root
          password: root
          driverClassName:  com.mysql.jdbc.Driver
          continueOnError: false

**Comment by hp88yx** [comment]
> 先自己断点看一下啊

(⊙o⊙)…

**Comment by tingmag** [comment]
同问，项目出现其他问题解决了之后，再启动就无法加载数据源了

**Comment by huayanYu** [comment]
一般都是配置问题或者数据源本身问题。 排查问题的时候应尽量精简不必要的配置去排查。

**Comment by hp88yx** [comment]
> 同问，项目出现其他问题解决了之后，再启动就无法加载数据源了

同学，你是怎么解决的，我把这个依赖切换到3.0.0还是不行，试过把数据库连接池切换成HikariCp一样的问题

**Comment by tingmag** [comment]
> > 同问，项目出现其他问题解决了之后，再启动就无法加载数据源了
> 
> 同学，你是怎么解决的，我把这个依赖切换到3.0.0还是不行，试过把数据库连接池切换成HikariCp一样的问题

没有解决啊

**Comment by tingmag** [comment]
> 一般都是配置问题或数据源本身问题。

就是觉得很奇怪这一块没有任何改动，早上一启动就提示这个了，标识很懵……

**Comment by huayanYu** [comment]
> > 一般都是配置问题或数据源本身问题。
> 
> 就是觉得很奇怪这一块没有任何改动，早上一启动就提示这个了，标识很懵……

检查数据源本身，可以重启试试。 不然就断点，我猜测是添加数据源的时候添加不了线程卡住了。

**Comment by hp88yx** [comment]
> > > 一般都是配置问题或数据源本身问题。
> > 
> > 
> > 就是觉得很奇怪这一块没有任何改动，早上一启动就提示这个了，标识很懵……
> 
> 检查数据源本身，可以重启试试。 不然就断点，我猜测是添加数据源的时候添加不了线程卡住了。

没有，我把spring boot版本切换回2. 0后又可以，换成2.2就不行

**Comment by tingmag** [comment]
> > > 一般都是配置问题或数据源本身问题。
> > 
> > 
> > 就是觉得很奇怪这一块没有任何改动，早上一启动就提示这个了，标识很懵……
> 
> 检查数据源本身，可以重启试试。 不然就断点，我猜测是添加数据源的时候添加不了线程卡住了。


> > > > 一般都是配置问题或数据源本身问题。
> > > 
> > > 
> > > 就是觉得很奇怪这一块没有任何改动，早上一启动就提示这个了，标识很懵……
> > 
> > 
> > 检查数据源本身，可以重启试试。 不然就断点，我猜测是添加数据源的时候添加不了线程卡住了。
> 
> 没有，我把spring boot版本切换回2. 0后又可以，换成2.2就不行

我试试

**Comment by hp88yx** [comment]
> > > > 一般都是配置问题或数据源本身问题。
> > > 
> > > 
> > > 就是觉得很奇怪这一块没有任何改动，早上一启动就提示这个了，标识很懵……
> > 
> > 
> > 检查数据源本身，可以重启试试。 不然就断点，我猜测是添加数据源的时候添加不了线程卡住了。
> 
> > > > > 一般都是配置问题或数据源本身问题。
> > > > 
> > > > 
> > > > 就是觉得很奇怪这一块没有任何改动，早上一启动就提示这个了，标识很懵……
> > > 
> > > 
> > > 检查数据源本身，可以重启试试。 不然就断点，我猜测是添加数据源的时候添加不了线程卡住了。
> > 
> > 
> > 没有，我把spring boot版本切换回2. 0后又可以，换成2.2就不行
> 
> 我试试

但是现在项目要升级版本，spring boot必须是2.2，头疼

**Comment by tingmag** [comment]
> > > > 一般都是配置问题或数据源本身问题。
> > > 
> > > 
> > > 就是觉得很奇怪这一块没有任何改动，早上一启动就提示这个了，标识很懵……
> > 
> > 
> > 检查数据源本身，可以重启试试。 不然就断点，我猜测是添加数据源的时候添加不了线程卡住了。
> 
> 没有，我把spring boot版本切换回2. 0后又可以，换成2.2就不行

具体是什么版本？

**Comment by tingmag** [comment]
> > > > > 一般都是配置问题或数据源本身问题。
> > > > 
> > > > 
> > > > 就是觉得很奇怪这一块没有任何改动，早上一启动就提示这个了，标识很懵……
> > > 
> > > 
> > > 检查数据源本身，可以重启试试。 不然就断点，我猜测是添加数据源的时候添加不了线程卡住了。
> > 
> > 
> > > > > > 一般都是配置问题或数据源本身问题。
> > > > > 
> > > > > 
> > > > > 就是觉得很奇怪这一块没有任何改动，早上一启动就提示这个了，标识很懵……
> > > > 
> > > > 
> > > > 检查数据源本身，可以重启试试。 不然就断点，我猜测是添加数据源的时候添加不了线程卡住了。
> > > 
> > > 
> > > 没有，我把spring boot版本切换回2. 0后又可以，换成2.2就不行
> > 
> > 
> > 我试试
> 
> 但是现在项目要升级版本，spring boot必须是2.2，头疼

我这边也是。。。

**Comment by hp88yx** [comment]
> > > > > > 一般都是配置问题或数据源本身问题。
> > > > > 
> > > > > 
> > > > > 就是觉得很奇怪这一块没有任何改动，早上一启动就提示这个了，标识很懵……
> > > > 
> > > > 
> > > > 检查数据源本身，可以重启试试。 不然就断点，我猜测是添加数据源的时候添加不了线程卡住了。
> > > 
> > > 
> > > > > > > 一般都是配置问题或数据源本身问题。
> > > > > > 
> > > > > > 
> > > > > > 就是觉得很奇怪这一块没有任何改动，早上一启动就提示这个了，标识很懵……
> > > > > 
> > > > > 
> > > > > 检查数据源本身，可以重启试试。 不然就断点，我猜测是添加数据源的时候添加不了线程卡住了。
> > > > 
> > > > 
> > > > 没有，我把spring boot版本切换回2. 0后又可以，换成2.2就不行
> > > 
> > > 
> > > 我试试
> > 
> > 
> > 但是现在项目要升级版本，spring boot必须是2.2，头疼
> 
> 我这边也是。。。

2.0.4可以成功运行，2.2.4就GG思密达

**Comment by tingmag** [comment]
ok，我试试看

**Comment by hp88yx** [comment]
> ok，我试试看

同学，有解决思路吗

**Comment by tingmag** [comment]
> > ok，我试试看
> 
> 同学，有解决思路吗

我这边改版本也不行，只能把源码弄下来调试了

**Comment by hp88yx** [comment]
> > > ok，我试试看
> > 
> > 
> > 同学，有解决思路吗
> 
> 我这边改版本也不行，只能把源码弄下来调试了
方便加个微信吗，一起讨论一下，github上面不方便

**Comment by tingmag** [comment]
> > > > ok，我试试看
> > > 
> > > 
> > > 同学，有解决思路吗
> > 
> > 
> > 我这边改版本也不行，只能把源码弄下来调试了
> > 方便加个微信吗，一起讨论一下，github上面不方便

QQ吧，方便一点 2689605130

**Comment by dlchris** [comment]
> > 同问，项目出现其他问题解决了之后，再启动就无法加载数据源了
> 
> 同学，你是怎么解决的，我把这个依赖切换到3.0.0还是不行，试过把数据库连接池切换成HikariCp一样的问题

springboot 2.2.5 + HikariCp 并未发现上述问题。要不换成2.2.5试试？

**Comment by tingmag** [comment]
> > > 同问，项目出现其他问题解决了之后，再启动就无法加载数据源了
> > 
> > 
> > 同学，你是怎么解决的，我把这个依赖切换到3.0.0还是不行，试过把数据库连接池切换成HikariCp一样的问题
> 
> springboot 2.2.5 + HikariCp 并未发现上述问题。要不换成2.2.5试试？
> JDK Version(Corretto): 11

可以贴一下配置吗？

**Comment by hp88yx** [comment]
> > > 同问，项目出现其他问题解决了之后，再启动就无法加载数据源了
> > 
> > 
> > 同学，你是怎么解决的，我把这个依赖切换到3.0.0还是不行，试过把数据库连接池切换成HikariCp一样的问题
> 
> springboot 2.2.5 + HikariCp 并未发现上述问题。要不换成2.2.5试试？
> JDK Version(Corretto): 11

成功脱坑了，写了个Demo，一个jar包一个jar包引入，后来发现是Druid jar包冲突，删除自己项目引入的jar包就解决问题了

**Comment by hp88yx** [comment]
> > > > 同问，项目出现其他问题解决了之后，再启动就无法加载数据源了
> > > 
> > > 
> > > 同学，你是怎么解决的，我把这个依赖切换到3.0.0还是不行，试过把数据库连接池切换成HikariCp一样的问题
> > 
> > 
> > springboot 2.2.5 + HikariCp 并未发现上述问题。要不换成2.2.5试试？
> > JDK Version(Corretto): 11
> 
> 可以贴一下配置吗？

已经解决了，jar包之间有冲突，不是配置问题，👻

**Comment by hp88yx** [comment]
没有提示加载到多少数据源，其实是已经加载到了的
