### ISSUE TITLE
Druid监控页面，SQL防火墙的表访问统计问题

### ISSUE THREAD

**Issue by moustachetyf** [baomidou/dynamic-datasource-spring-boot-starter#174]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.0.6.RELEASE

Starter Version(required):3.0.0

# Describe
Druid监控页面，SQL防火墙的表访问统计不准确，启动一次服务后，只能统计到其中一个数据源的内容，或者就是每个数据源都统计不到。但是防御统计还是一直在计数

Expected Result: 
![image](https://user-images.githubusercontent.com/26763532/79631513-677ef700-818c-11ea-92a6-3fe96893afca.png)

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by moustachetyf** [comment]
附上我的配置文件
![image](https://user-images.githubusercontent.com/26763532/79631609-04da2b00-818d-11ea-8bff-7933d4fad91f.png)

**Comment by huayanYu** [comment]
直觉不是我的问题，可能是druid的问题

**Comment by moustachetyf** [comment]
> 直觉不是我的问题，可能是druid的问题

单独使用druid监控统计是没问题的

**Comment by huayanYu** [comment]
> > 直觉不是我的问题，可能是druid的问题
> 
> 单独使用druid监控统计是没问题的

你可以断点看看druid我的加载过程，如果没有参数加载问题，那就是druid的问题。
