### ISSUE TITLE
移除、添加数据源时，oracle的session数是一直累加的，不会自动销毁

### ISSUE THREAD

**Issue by betatoo** [baomidou/dynamic-datasource-spring-boot-starter#175]
按照例子添加和删除数据源，但是oracle数据库的session并没有因为移除二减少，会一直累加，大佬有没有解决办法？
https://github.com/baomidou/dynamic-datasource-spring-boot-starter/wiki/Manual-Add-Remove-DataSource

select username,count(username) count from v$session where username is not null group by username

**Comment by huayanYu** [comment]
你断点检查下，是否调用了底层数据源close方法， 是不是没有关闭成功。  如果成功了，那我就没法。

**Comment by betatoo** [comment]
com.baomidou.dynamic.datasource.DynamicRoutingDataSource#removeDataSource
com.baomidou.dynamic.datasource.DynamicGroupDataSource#removeDatasource
这2个方法确实没有真正的关闭数据源连接，只是从list里移除了

**Comment by betatoo** [comment]
> 你断点检查下，是否调用了底层数据源close方法， 是不是没有关闭成功。 如果成功了，那我就没法。

谢谢提醒

**Comment by betatoo** [comment]
看到master上的代码已经增加了关闭数据源的代码块，不知道作者什么时候发布

**Comment by betatoo** [comment]
3.0.1已经解决了
