### ISSUE TITLE
如何整合activiti

### ISSUE THREAD

**Issue by Fengxici** [baomidou/dynamic-datasource-spring-boot-starter#178]
如何整合activiti

**Comment by wangpeiyao** [comment]
同问

**Comment by huayanYu** [comment]
@wangpeiyao @Fengxici  你们整合遇到什么问题，详细描述。 可fork示例项目，给出demo。

**Comment by wangpeiyao** [comment]
acitviti需要注入数据源和事务管理器，并且所有的servicer定义和orm有自身上下文管理，未交给spring管理

**Comment by huayanYu** [comment]
> acitviti需要注入数据源和事务管理器，并且所有的servicer定义和orm有自身上下文管理，未交给spring管理

所以你最后怎么解决的也，  我从未用过activiti，不太清楚。 如果可能的话可以把解决方法回答一下， 给后面有需要的人看。
