### ISSUE TITLE
p6spy: true 导致sql执行两次

### ISSUE THREAD

**Issue by ayida** [baomidou/dynamic-datasource-spring-boot-starter#181]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.2.5

Starter Version(required):3.0.0

# Describe
yml中配置p6spy: true 会导致SQL执行两次，我不配置p6spy，也能正常输出spy打印的完整sql

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by ayida** [comment]
貌似找到原因了，我自己在pom中引入了`p6spy:3.9.0`，看到`dynamic-datasource-spring-boot-starter`中也有可选的p6spy
```
<dependency>
    <groupId>p6spy</groupId>
    <artifactId>p6spy</artifactId>
    <version>3.8.7</version>
    <optional>true</optional>
</dependency>
```
我是不是应该是使用自带的3.8.6，请教下我该如何使用这个可选的自带的的p6spy ?

**Comment by huayanYu** [comment]
自行解决

**Comment by liuyeshennai** [comment]
> 貌似找到原因了，我自己在pom中引入了`p6spy:3.9.0`，看到`dynamic-datasource-spring-boot-starter`中也有可选的p6spy
> 
> ```
> <dependency>
>     <groupId>p6spy</groupId>
>     <artifactId>p6spy</artifactId>
>     <version>3.8.7</version>
>     <optional>true</optional>
> </dependency>
> ```
> 
> 我是不是应该是使用自带的3.8.6，请教下我该如何使用这个可选的自带的的p6spy ?

你好，我也遇到这个情况，请问是如何解决的？

**Comment by ayida** [comment]
> 你好，我也遇到这个情况，请问是如何解决的？

久远，有点忘记原因了，大致印象貌似是spy.properties中的modulelist，你先试试
```
modulelist=com.baomidou.mybatisplus.extension.p6spy.MybatisPlusLogFactory
logMessageFormat=com.tbyf.platformapi.config.P6spyConfig
appender=com.p6spy.engine.spy.appender.Slf4JLogger
excludecategories=info,debug,result,commit,resultset
dateformat=yyyy-MM-dd HH:mm:ss
```
