### ISSUE TITLE
mybatis-plus父类的save update数据源指定

### ISSUE THREAD

**Issue by libra1010** [baomidou/dynamic-datasource-spring-boot-starter#182]
配置了数据源A 数据源B用来做读写分离，想用A做增删改， B做查询
这个时候 mybatis-plus ServiceImpl里面的 save 方法和 getById如何指定数据源勒？

另：
M1方法使用的Ds("A") M2方法使用Ds("B")
M1调用了M2方法，那这个时候，M1是使用 A数据源， M2还是 B数据源吗？
如果在M1,和M2上分别都加入了事务
这个时候事务是不生效的？

**Comment by huayanYu** [comment]
1.查看文档 重写ServiceImpl或者某个方法。
2. 查看文档分布式事务。
