### ISSUE TITLE
3.0.0版本将@DS注解配置在Mapper无效

### ISSUE THREAD

**Issue by luckamuu** [baomidou/dynamic-datasource-spring-boot-starter#183]
@DS注解在Mapper中配置在service中调用无效，只有配置在service中在controller中调用才可以。望解答

**Comment by luckamuu** [comment]
我的项目架构是model -> mapper -> service -> controller

**Comment by Yangqi0338** [comment]
3.0.0以上的版本没有修改到springboot版本,还是1.5.1-RELEASE

**Comment by huayanYu** [comment]
请按issue模板来提问以便了解你的环境和配置便于复现问题。
暂时无法复现
