### ISSUE TITLE
根据文档集成druid和mp无法开启druid的监控页

### ISSUE THREAD

**Issue by airclear** [baomidou/dynamic-datasource-spring-boot-starter#184]
# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
2.2
Starter Version(required):
3.0.0
# Describe

根据这个文档做集成
https://github.com/baomidou/dynamic-datasource-spring-boot-starter/wiki/Integration-With-Druid
并添加了mp3.3.1

druid的监控页404

Expected Result: 

开启监控页

**Comment by huayanYu** [comment]
spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
