### ISSUE TITLE
多数据源中，个别源暂时无法连接，导致项目无法启动

### ISSUE THREAD

**Issue by warlockhades** [baomidou/dynamic-datasource-spring-boot-starter#186]
# Enviroment

JDK Version(required): 1.8.0_171

SpringBoot Version(required): 2.2.1.RELEASE

Starter Version(required):2.2.1.RELEASE

# Describe
配置了多个数据源，第一个源能连通，第二个数据库暂时不能连接，项目无法启动

Expected Result: 跳过不能连接的数据源，继续启动项目

Actual Result:  程序异常退出

# Steps to reproduce

- Step 1 
配置一个存在的数据源和一个不存在的数据源

- Step 2 
启动spring boot 项目

- Step 3 
报错
2020-04-28 10:57:07.674 ERROR 7900 --- [           main] com.zaxxer.hikari.pool.HikariPool        : oracle_60 - Exception during pool initialization.

java.sql.SQLRecoverableException: IO 错误: The Network Adapter could not establish the connection

**Comment by Yangqi0338** [comment]
3.0.0以上的版本没有修改到springboot版本,还是1.5.1-RELEASE

**Comment by huayanYu** [comment]
感觉做不了。。。

**Comment by withinfly** [comment]
启动的时候，既然发现无法存在无法使用的数据源，导致启动失败很正常啊、既然无效，就要你解决吖。

**Comment by Umenezumi** [comment]
你不能把bug当feature处理啊

**Comment by huayanYu** [comment]
无法实现。
