### ISSUE TITLE
多数据源中,druid连接池max-wait不生效

### ISSUE THREAD

**Issue by wangfeng654** [baomidou/dynamic-datasource-spring-boot-starter#189]
# Enviroment

JDK Version(required): 1.8.0_171

SpringBoot Version(required): 2.2.1.RELEASE

Starter Version(required):2.2.1.RELEASE

# Describe
项目用到了多数据源，并且使用了druid连接池，配置max-wait，但是Debug查看连接池，max-wait并没有设置成功，还是默认的-1

Expected Result: max-wait设置生效

Actual Result:  max-wait设置不生效

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
无法复现， 建议升级druid版本试试。 我记得druid有个版本是有参数覆盖的问题。
