### ISSUE TITLE
DynamicDataSourceAnnotationInterceptor导致SQL异常无法抛出

### ISSUE THREAD

**Issue by angel8899421110** [baomidou/dynamic-datasource-spring-boot-starter#196]
# Enviroment

JDK Version(required): 
jdk1.8
SpringBoot Version(required): 
springboot 2.
Starter Version(required):
3.1.0
# Describe
DynamicDataSourceAnnotationInterceptor中
@Override
  public Object invoke(MethodInvocation invocation) throws Throwable {
    try {
      DynamicDataSourceContextHolder.push(determineDatasource(invocation));
      return invocation.proceed();
    } finally {
      DynamicDataSourceContextHolder.poll();
    }
  }
异常使用try 拦截但未抛出 导致无法正常显示错误信息，此处抛出异常是否会影响程序的正常执行有待验证，是否考虑抛出异常

**Comment by huayanYu** [comment]
- -应该会抛出去啊， 我没有抓异常啊。

**Comment by angel8899421110** [comment]
invocation.proceed(); 在try-catch块中间啊 你就没抛出去

**Comment by huayanYu** [comment]
@angel8899421110 会抛出去的，可以测一下。

**Comment by angel8899421110** [comment]
我是用代码跟踪到这的，发现并没有抛出任何异常。。。。我找个时间，弄个样例再试试

**Comment by JJdog** [comment]
版本 3.0.0  我也遇到了这个问题   没抛出来，执行sql 控制 卡住   ，debug进去 才知道是sql异常
