### ISSUE TITLE
建议：有没有可能自动识别select的sql自动切换slave库 其他增删改默认是master

### ISSUE THREAD

**Issue by DreamPWJ** [baomidou/dynamic-datasource-spring-boot-starter#20]
这样默认配置能满足默认需求  无需注解控制 实现简单的读写分离

**Comment by huayanYu** [comment]
mybatis环境下可以，查看最新的提交的代码。 注入即可

**Comment by huayanYu** [comment]
@DreamPWJ

**Comment by DreamPWJ** [comment]
牛  期待发布新版  默认集成  提供配置选项 供用户选择是否自动模式

**Comment by DreamPWJ** [comment]
不知道  这种拦截器自动切换方式  对性能有没有太大的影响  没经过测试

**Comment by DreamPWJ** [comment]
![image](https://user-images.githubusercontent.com/16730031/52630769-158f7100-2ef8-11e9-8fea-a6fd1598fedd.png)
没有方法  啥情况@huayanYu
