### ISSUE TITLE
NamedInheritableThreadLocal引发的线程并发问题

### ISSUE THREAD

**Issue by syc87** [baomidou/dynamic-datasource-spring-boot-starter#200]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.2.5

Starter Version(required): 3.1.0

# Describe
升级到3.1.0，使用quartz任务调度时，quartz元数据在主库，某些作业访问的是日志库，当访问不同库的作业并发执行时，大概率出现找不到quartz元数据的异常，明显就是数据库切换错误导致的（quartz元数据在日志库也存一份就不会出现问题）。

而3.0.0没有这个问题，通过比较这两个版本的代码，发现了一个可疑的地方，就是原来用来保存数据源栈的ThreadLocal对象改成了NamedInheritableThreadLocal对象。

InheritableThreadLocal的特性是子线程会继承父线程的变量，这样我感觉在下面的场景会带来线程安全的问题。

比如调度线程为父线程，两个作业为子线程（quartz真实的架构也许不是这样，仅仅是模拟这样的场景）
调度线程：主库
作业A：主库
作业B：日志库
如果按如下顺序执行：
1、调度线程创建作业A、作业B同时启动，并且创建了一个数据源栈继承给了两个作业。
2、作业A，访问quartz元数据（主库）进行调度前处理，栈压入主库
3、作业B，访问quartz元数据（主库）进行调度前处理，栈压入主库
4、作业B，写入日志（日志库），栈压入日志库，执行可能比较耗时，栈顶为日志库
5、作业A，执行完毕，需要访问quartz元数据（主库）进行调度后处理，由于栈顶是日志库，访问不到quartz元数据，出现异常。

最后通过替换3.1.0的代码，改回ThreadLocal变量，问题解决，也基本验证了这个猜想。

使用NamedInheritableThreadLocal的目的是什么？是为了支持什么新特性么？

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by syc87** [comment]
补充一下，在使用3.1.0还出现过一个可怕的问题就是，数据源切换异常有次貌似还从调度传递到了前端controller线程，只出现过一次，很难重现，就是调度异常后，前端的请求也大概率的访问不到数据库（偶尔能正常），按理说调度的线程池应该和controller不是同一个，是怎么泄漏出来的，原因还不明。
反正，一个可以共享的ThreadLocal变量感觉还是非常危险的。

**Comment by ls9527** [comment]
在 spring 初始化的时候, 会初始化quartz默认的线程池, 
然而在初始化线程池的期间,当前线程的线程变量 队列应该为空的.
出现这个问题,可能是不合理的多层调用引起? 

既然会引发这个问题.    建议增加兼容吧.  
类似springmvc的  LocaleContextHolder.
可以默认设置成 InheritableThreadLocal, 然后给用户一个更改为 ThreadLocal 的机会.
这样即使提出这个问题, 楼主也只是需要改配置,而不是自己改源码, 部署私服

**Comment by huayanYu** [comment]
revert

**Comment by jasonjiang9527** [comment]
> 补充一下，在使用3.1.0还出现过一个可怕的问题就是，数据源切换异常有次貌似还从调度传递到了前端controller线程，只出现过一次，很难重现，就是调度异常后，前端的请求也大概率的访问不到数据库（偶尔能正常），按理说调度的线程池应该和controller不是同一个，是怎么泄漏出来的，原因还不明。
> 反正，一个可以共享的ThreadLocal变量感觉还是非常危险的。

目前遇到了同样的问题，tomcat的线程holder里也出现了不可能出现的ds。我看源码，确实有可能出现在async task pool里，这个controller线程里也出现很不理解😫
