### ISSUE TITLE
DynamicDataSourceContextHolder.peek为空

### ISSUE THREAD

**Issue by 0532** [baomidou/dynamic-datasource-spring-boot-starter#203]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.1.5

Starter Version(required):3.1.0

# Describe

![image](https://user-images.githubusercontent.com/5317048/82425274-df587e00-9ab8-11ea-9bb1-fcc8398dcf72.png)

测试的时候
```
    public static String peek() {
        return (String)((Deque)LOOKUP_KEY_HOLDER.get()).peek();
    }
```
结果为空

Expected Result: 

Actual Result:  
     没有选择传入数据源，走了默认，这里需要手动push一下吗

# Steps to reproduce

- Step 1 
```
@DS("yc")
    private void testDb(String system){
        List<Entity> list = dao.list(system);
        System.out.println("#########"+list.size());
    }
```
- Step 2 

- Step 3

**Comment by huayanYu** [comment]
看不到图， 不过逻辑就是找不到注解所指定的数据源就走默认数据源， 或者使用严格模式，抛出异常。

**Comment by 0532** [comment]
嗯 解决了 在程序里没有问题里，可能是测试类配的有问题
@huayanYu  谢谢了 😄
