### ISSUE TITLE
多数据源一部分支持druid、一部分不支持druid

### ISSUE THREAD

**Issue by Wing-Lo** [baomidou/dynamic-datasource-spring-boot-starter#204]
# Enviroment

JDK Version(required): 
1.8

SpringBoot Version(required): 
2.2.0.RELEASE

dynamic-datasource-spring-boot-starter Version(required):
3.1.0
druid Version(optional):
1.1.18

# Describe
多数据源配置一个mysql、一个clickhouse
报错
`Caused by: java.lang.IllegalStateException: dbType not support : clickhouse`

看了下源码，发现是下面这一行
https://github.com/baomidou/dynamic-datasource-spring-boot-starter/blob/8800108bdd3361ae8746891814a8a15ded0bffed/src/main/java/com/baomidou/dynamic/datasource/creator/DataSourceCreator.java#L51
只要是有依赖druid的jar包则开启druid

# 建议
是否是可以有参数配置支持多数据源一部分开启一部分不开启druid

**Comment by huayanYu** [comment]
手动指定type即可 @Wing-Lo

**Comment by Wing-Lo** [comment]
好的谢谢

**Comment by gotowu** [comment]
> 手动指定type即可 @Wing-Lo

请问指定type 成什么呢？
