### ISSUE TITLE
多主或多从时，健康检查代码有问题

### ISSUE THREAD

**Issue by withinfly** [baomidou/dynamic-datasource-spring-boot-starter#206]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.1.8.RELEASE

dynamic-datasource-spring-boot-starter Version(required):3.1.0

druid Version(optional):1.1.9

# Describe

源码：MasterSlaveAutoRoutingPlugin.java
![image](https://user-images.githubusercontent.com/13146413/82726384-56d71900-9d16-11ea-8247-e604ba7c36f1.png)

![image](https://user-images.githubusercontent.com/13146413/82726419-8d149880-9d16-11ea-8ffd-2ee07113ec6b.png)

除非自己改写MasterSlaveAutoRoutingPlugin.java，

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
嗯，自己改写吧。 本来就是一个示例，根据自己需求改写下吧。
