### ISSUE TITLE
集成mybatils plus 时，使用Lambda查询方式会使@DS失效

### ISSUE THREAD

**Issue by neozo** [baomidou/dynamic-datasource-spring-boot-starter#207]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.2.2

dynamic-datasource-spring-boot-starter Version(required):2.5.6

druid Version(optional):1.1.21

# Describe
集成mybatils plus 时，使用Lambda查询方式会使@DS失效

这种方式可以正常切换DS
```
LambdaQueryWrapper<Customer> wrapper = Wrappers.<Customer>lambdaQuery()；
customerService.count(wrapper);
```

使用这种方式时，DS失效，使用了默认数据源
`customerService.lambdaQuery().count();`

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
无法复现，请详细描述。
