### ISSUE TITLE
问一下  这个可以和 sharding-jdbc结合使用吗

### ISSUE THREAD

**Issue by esonChe** [baomidou/dynamic-datasource-spring-boot-starter#21]
# Enviroment

JDK Version(required): 

SpringBoot Version(required): 

Starter Version(required):

# Describe

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
没结合过， 你可以尝试下。
