### ISSUE TITLE
多数据源程序启动成功后立即执行部分sql，出现数据源错乱问题

### ISSUE THREAD

**Issue by huoshanwei** [baomidou/dynamic-datasource-spring-boot-starter#213]
# Enviroment

JDK Version(required): 
1.8.0
SpringBoot Version(required): 
2.1.5
dynamic-datasource-spring-boot-starter Version(required):
3.1.0
druid Version(optional):
1.1.22
# Describe
业务场景：
A，B数据库
1.通过定时任务拉取A库中数据，写入B库中，300ms执行一次
2.程序启动成功后执行立即一个读A库和B库中的数据分别写本地缓存的操作
部分sql操作会数据源错乱，会在A库中找B库的表，结果报错
注释1或2操作代码，不会出现此问题，实在没办法了，在写缓存操作中加入了一个sleep(5s)，以上问题未再复现

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
没有代码无法复现， 猜测可能是共用了线程。 尝试断点和查看运行日志看线程是否是同一个线程。 解决方法一般要么新开线程，要么手动调用工具类切换。

**Comment by huoshanwei** [comment]
![image](https://user-images.githubusercontent.com/14287441/83106538-3aa8f280-a0ef-11ea-82e7-a067f696a99a.png)

**Comment by dlchris** [comment]
目前我们也是发现了类似的问题

**Comment by huayanYu** [comment]
3.1.0是bug版本。 遇到此问题的升级到最新版本
