### ISSUE TITLE
多数据源动态切换，mapper.xml配置问题

### ISSUE THREAD

**Issue by superlyao** [baomidou/dynamic-datasource-spring-boot-starter#215]
# Enviroment

JDK Version(required): 1.8.0_201

SpringBoot Version(required): 2.1.2.RELEASE

dynamic-datasource-spring-boot-starter Version(required): 3.1.0

druid Version(optional):1.1.9

# Describe

项目中有多种数据源，
- A
 -A-1
 -A-2
- B
 -B-1
 -B-2,
AB两类数据源的mapper.xml的目录结构不一样，如何在代码中配置，
我看示列代码都是使用的注解的方式

```java
    SqlSessionFactoryBean bean = new SqlSessionFactoryBean();
    ResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();
    bean.setDataSource(dataSource);
    bean.setMapperLocations(resolver.getResources(mapperLocations));
    return bean.getObject();
```
之前的代码在配置datasource就可以配置`setMapperLocations`，现在使用动态数据源，如何配置每个数据源的`mapperLocations`

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
https://blog.csdn.net/qq_42685050/article/details/81427865
你可能比较适合静态多数据源。
