### ISSUE TITLE
Updating the SQLite table record  restarted SpringBoot Application?

### ISSUE THREAD

**Issue by liulipengju** [baomidou/dynamic-datasource-spring-boot-starter#217]
# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
2.1.1
dynamic-datasource-spring-boot-starter Version(required):
3.1.0
druid Version(optional):
1.1.22
# Describe

1. first db is SqlServer and second db is SQLite
2. Dynamic DB restarted SpringBoot Application when updated the SQLite table record at the service of SqlServer . 
3. SqlServer DB is primary，Sqllite Mapper added the DS annotation
![TIM截图20200529142438](https://user-images.githubusercontent.com/10510950/83228639-44972800-a1b9-11ea-9a3b-f39f266c0d56.png)

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by liulipengju** [comment]
![image](https://user-images.githubusercontent.com/10510950/83229151-0c441980-a1ba-11ea-86cb-3b2416ef00d0.png)
<mybatis-plus.version>3.3.2</mybatis-plus.version>

**Comment by huayanYu** [comment]
根据我一般经验都是一些其他问题影响的，仔细检查下或者降低下dynamic-datasource-spring-boot-starter 版本试试。

**Comment by huayanYu** [comment]
无更多回复，关闭

**Comment by liulipengju** [comment]
你好，我因为有事没有回复，请重新开启一下数据库，我测试过，使用sqlserver+h2，动态数据源不会重启，但是sqlserver+sqlite就会重启，这应该不是其他问题影响的

**Comment by liulipengju** [comment]
我从spring官网创建了一个demo，什么都没有放，仅放了sqlserver/sqlite，hutool，然后放了几个必要类，然后就保存了一个sqlite表，一样会重启的，h2不会，我觉得是代码问题，需要看看

**Comment by liulipengju** [comment]
好，我找到问题了，是我自己的问题
