### ISSUE TITLE
通过手动创建hikariDatasource,导致actuator中的metrics不能收集信息

### ISSUE THREAD

**Issue by a419506442** [baomidou/dynamic-datasource-spring-boot-starter#22]
通过手动创建hikariDatasource,导致actuator中的metrics不能收集信息

**Comment by huayanYu** [comment]
啥意思,能稍微描述清楚些不? 
怎么手动创建的？ 预期什么结果。

**Comment by a419506442** [comment]
> 啥意思,能稍微描述清楚些不?
> 怎么手动创建的？ 预期什么结果。

hikariDatasource在这个项目中是new hikariDatasource 方式创建， 但是 actuator中是通过HikariDataSourceMetricsPostProcessor 方式进行bean拦截赋值，是赋值不上的

**Comment by huayanYu** [comment]
> > 啥意思,能稍微描述清楚些不?
> > 怎么手动创建的？ 预期什么结果。
> 
> hikariDatasource在这个项目中是new hikariDatasource 方式创建， 但是 actuator中是通过HikariDataSourceMetricsPostProcessor 方式进行bean拦截赋值，是赋值不上的

我没搜到这个类

**Comment by a419506442** [comment]
> > > 啥意思,能稍微描述清楚些不?
> > > 怎么手动创建的？ 预期什么结果。
> > 
> > 
> > hikariDatasource在这个项目中是new hikariDatasource 方式创建， 但是 actuator中是通过HikariDataSourceMetricsPostProcessor 方式进行bean拦截赋值，是赋值不上的
> 
> 我没搜到这个类

HikariDataSourceMetricsPostProcessor 是在 springboot项目spring-boot-actuator-autoconfigure中的
