### ISSUE TITLE
单模块的多数据源事务问题有说明吗？

### ISSUE THREAD

**Issue by caorenpeng-kaer** [baomidou/dynamic-datasource-spring-boot-starter#221]
# Enviroment

JDK Version(required): 

SpringBoot Version(required): 

dynamic-datasource-spring-boot-starter Version(required):

druid Version(optional):

# Describe

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
不支持，必须基于seata。 基于seata也可以是单模块的。 示例就是

**Comment by caorenpeng-kaer** [comment]
> 不支持，必须基于seata。 基于seata也可以是单模块的。 示例就是
麻烦请问一下，示例demo有吗？有的话在哪里
