### ISSUE TITLE
项目新启动后并发访问出现数据源选错的情况

### ISSUE THREAD

**Issue by yesgs** [baomidou/dynamic-datasource-spring-boot-starter#228]
# Enviroment

JDK Version(required): 1.8.0_241-b07

SpringBoot Version(required): 2.1.8.RELEASE

dynamic-datasource-spring-boot-starter Version(required): 3.1.0

druid Version(optional): 1.0.18

# Describe
每次项目启动后，并发访问十个接口(每个接口为不同的数据源)时，会出现数据源错乱的情况。
数据源配置从header中获取。
在自定义的DsProcessor中打最后日志，发现最终return的key是正确的。

Expected Result: 
根据DS注解配置的寻找正确的数据源

Actual Result:  
部分接口数据源选错

# Steps to reproduce

- Step 1 
启动项目，同时访问多个数据源不同的接口

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
这个太难复现了，能不能fork项目，参考示例项目给出你的大概场景。

**Comment by yesgs** [comment]
升级到最新版本后选错数据源的问题消失了
