### ISSUE TITLE
内存泄露算个问题不

### ISSUE THREAD

**Issue by a419506442** [baomidou/dynamic-datasource-spring-boot-starter#23]
# Enviroment

JDK Version(required): 

SpringBoot Version(required): 

Starter Version(required):

# Describe

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3 

![image](https://user-images.githubusercontent.com/1701838/53476118-992a8f80-3aac-11e9-9228-5c484419842f.png)

**Comment by huayanYu** [comment]
请提交到mybatis-plus
