### ISSUE TITLE
求助，开始十个线程按年份去数据库查询数据，插入数据库2中的十个表，完成7个线程之后，一直处于假死状态，卡在了mapper层查询，不报错也运行不下去，同时其他查询的放在无法再查询数据库数据了

### ISSUE THREAD

**Issue by Summary-wcj** [baomidou/dynamic-datasource-spring-boot-starter#230]
# Enviroment

JDK Version(required): 

SpringBoot Version(required): 

dynamic-datasource-spring-boot-starter Version(required):

druid Version(optional):

# Describe

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
线程太多了，底层Hold不住。 或者可能存在的死锁情况。和本工具应无关
