### ISSUE TITLE
针对动态添加数据源的例子，如果是多台机器做负载均衡，是每一台都要执行addDataSource操作吗么？

### ISSUE THREAD

**Issue by alwyngo** [baomidou/dynamic-datasource-spring-boot-starter#233]
https://github.com/baomidou/dynamic-datasource-spring-boot-starter/blob/3cbeb3163cd3ca95d448ba49a08a3c9f3bbe8416/samples/dynamic-add-remove-datasource/src/main/java/com/baomidou/samples/dynamicload/controller/LoadController.java#L37

针对该例子，如果是针对一台机器是没有问题的，如果是多台机器，那么只会在一台添加数据源，如果请求到另外一台机器是不是就没有添加的数据源了，所以需要所有机器都要执行这么一个添加动作

**Comment by huayanYu** [comment]
嗯，使得，这种场景建议使用一个监听器或者 观察者之类模式， 统一向一个地方发消息，其他机器监听自动加载。
