### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by 346069073** [baomidou/dynamic-datasource-spring-boot-starter#236]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.1.5

dynamic-datasource-spring-boot-starter Version(required):3.1.0

druid Version(optional):
启动报错:
is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
这是一个info， 这不是由本程序引起的
