### ISSUE TITLE
when to support clickhouse and chproxy

### ISSUE THREAD

**Issue by GPF199541** [baomidou/dynamic-datasource-spring-boot-starter#237]
# Enviroment

JDK Version(required): 

SpringBoot Version(required): 

dynamic-datasource-spring-boot-starter Version(required):

druid Version(optional):

# Describe

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
只要符合jdbc驱动的都能加载， 也可以自己实现creator加载。
