### ISSUE TITLE
Service 头部有 @transactional(readOnly = true, rollbackFor = Exception.class) 注解时， 无法在里面切换数据源

### ISSUE THREAD

**Issue by bashuyi** [baomidou/dynamic-datasource-spring-boot-starter#24]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 1.5.10.RELEASE

Starter Version(required): 2.4.2

# Describe

Service 头部有 @transactional(readOnly = true, rollbackFor = Exception.class) 注解时，
无法在里面切换数据源

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
看文档，不支持事物
