### ISSUE TITLE
单模块的多数据源事务,可以使用ChainedTransactionManager方式支持一下吗？

### ISSUE THREAD

**Issue by fanhualuo** [baomidou/dynamic-datasource-spring-boot-starter#240]

**Comment by huayanYu** [comment]
可以PR

**Comment by a364176773** [comment]
> 可以PR

可以利用lcn原理,代理Connection,做当前事务组下的Connection统一commit/rollback即可.分布式事务可以直接利用seata.
有空的话,我之后做一版,提pr过来

**Comment by yy-zte** [comment]
请问大神，这个问题还有解决方案的例子吗，现在我们项目非常需要单体多数据库事务，用seata，显的笨重，目前我实现了ChainedTransactionManager与jdbcTimeplate联合使用，支持了事务机制功能，但是要实现ChainedTransactionManager与DynamicDataSource联合使用，发现数据持久层访问框架mybatis同样也有自己的transaction，这与springboot的transaction之间貌似有关联，这两者又有什么关系，怎么才能做到两者兼容并且实现跨库事务，还请大神们赐教

**Comment by huayanYu** [comment]
@yy-zte 感觉很复杂，可用进群聊。

**Comment by huayanYu** [comment]
近期会更新对事务的原生支持。
