### ISSUE TITLE
2个以上多数据源针对数据原配置不同的连接池驱动不管用，会默认使用第一个默认的连接驱动

### ISSUE THREAD

**Issue by zengdingxin** [baomidou/dynamic-datasource-spring-boot-starter#241]
# Enviroment

JDK Version(required): 1.8.0_231

SpringBoot Version(required): 2.1.9

dynamic-datasource-spring-boot-starter Version(required):3.1.1

druid Version(optional):1.1.22

# Describe

2个以上多数据源针对数据原配置不同的连接池驱动不管用，会默认使用第一个默认的连接驱动

spring:
  datasource:
    dynamic:
      datasource:
        mysql:
          druid :
            connectionTestQuery: SELECT 1
            connectionTimeout: 30000
            idleTimeout: 10000
            isReadOnly: false
            maxLifetime: 1800000
            maxPoolSize: 5
            minIdle: 1
        sqlserver:
          hikari:
            connectionTestQuery: SELECT 1
            connectionTimeout: 30000
            idleTimeout: 10000
            isReadOnly: false
            maxLifetime: 1800000
            maxPoolSize: 5
            minIdele: 1

sqlserver将会默认使用druid 连接驱动，不会使用hikari

Expected Result: 

数据源能使用不同的连接驱动配置

Actual Result:  

实际结果是默认使用第一个连接驱动，第二个数据源配置不同的连接驱动不管用默认使用了第一个连接驱动

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
手动配置type
