### ISSUE TITLE
mybatis-plus是不是把dynamic-datasource-spring-boot-starter给单独出来了

### ISSUE THREAD

**Issue by samuel072** [baomidou/dynamic-datasource-spring-boot-starter#243]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.2.5 

dynamic-datasource-spring-boot-starter Version(required):3.1.1

druid Version(optional):

# Describe
我在mybatis-plus里面没有添加dynamic-datasource-spring-boot-starter这个包，然后找不到@DS注解。是不是dynamic-datasource-spring-boot-starter这个单独出来了，不会集成在mybatis-plus里面？

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
嗯，一直是独立的。
