### ISSUE TITLE
欢迎加入QQ群 1132021421快速咨询问题，ISSUE正常回复

### ISSUE THREAD

**Issue by huayanYu** [baomidou/dynamic-datasource-spring-boot-starter#244]
直接加入 <a target="_blank" href="//shang.qq.com/wpa/qunwpa?idkey=ded31006508b57d2d732c81266dd2c26e33283f84464e2c294309d90b9674992"><img border="0" src="//pub.idqqimg.com/wpa/images/group.png" alt="dynamic-sring-boot-starter" title="dynamic-sring-boot-starter"></a>

QQ群号:1132021421 。 ISSUE也会回复。

![IMG_1057(20200629-225348)](https://user-images.githubusercontent.com/16700837/86075443-98e43f00-baba-11ea-8549-789e12f7d753.JPG)

**Comment by blameswood** [comment]
按文档 集成  shardingsphere 无法正常分片，求完整示例

**Comment by TaoZhou** [comment]
请问这个是不是支持mybatis的？不支持JPA

**Comment by zhangxiangfeng** [comment]
@TaoZhou 数据源 和 ORM框架有关系吗？

**Comment by shilohooo** [comment]
@huayanYu 你好，dynamic-datasource-spring-boot-starter 2.1.0版本设置druid的remove-abandoned，remove-abandoned-timeout，log-abandoned3个参数无效，请问这个版本是缺少参数，需要升级版本吗

**Comment by huayanYu** [comment]
@shilohooo 升级啊。

**Comment by shilohooo** [comment]
@huayanYu 👌

**Comment by silloy** [comment]
可否开通一个微信群

**Comment by huayanYu** [comment]
@silloy 有时效，懒得维护~
