### ISSUE TITLE
mybatis关联查询怎么设置多数据源

### ISSUE THREAD

**Issue by hxy6699** [baomidou/dynamic-datasource-spring-boot-starter#246]
# Enviroment

JDK Version(required): 8u171

SpringBoot Version(required): 2.2.6

dynamic-datasource-spring-boot-starter Version(required):3.1.1

druid Version(optional):1.1.10

# Describe
配置数据源之后 在dao层的方法都放上DS注解
直接调用dao层的查询都能正确的使用第二数据源拿到数据
但是mapper映射文件中配置的关联查询 比如association这些都依然是使用的主数据源
这个问题有办法解决吗

另外我没有使用mybatis-plus 数据库这块就是springboot+druid+myabtis
如果把DS注解写在dao层的类上就会报错
`java.lang.IllegalArgumentException: Can not set final java.lang.Class field org.apache.ibatis.binding.MapperProxy.mapperInterface to org.springframework.aop.framework.JdkDynamicAopProxy`

**Comment by huayanYu** [comment]
第一个问题，添加事物到service层就好了。
第二个问题要开启aop代理。 不能使用原生JDK

**Comment by hxy6699** [comment]
@huayanYu 
单步调试发现查询操作都没有走第二数据源 都是从第一数据源找 写的时候都写到第二数据源了
我把第一数据源里面和第二数据源重名的表删掉之后就开始报错找不到表了

数据库配置如下
![数据库连接配置](https://user-images.githubusercontent.com/46079468/86326497-5fefca00-bc74-11ea-9a7b-d8b3e1692ff2.png)
设置了master和test两个数据源 来自两个服务器

Service层配置如下
在类上添加了DS注解和Transactional注解
![Service层](https://user-images.githubusercontent.com/46079468/86326612-90cfff00-bc74-11ea-9a92-3e0cec569527.png)

Dao层没有做任何配置
![Dao层](https://user-images.githubusercontent.com/46079468/86326644-9cbbc100-bc74-11ea-819d-96af7161f482.png)

求大佬帮忙看看咋回事

我这个项目用了shiro 把shiro注释掉之后问题依然存在

**Comment by ls9527** [comment]
加一个你的方法执行的代码,   描述一下哪个是走的 主库, 哪个走的从库.   目前的文字和图片没描述没办法定位

**Comment by hxy6699** [comment]
@ls9527

目前登录和权限认证都走第二数据源 这是个主模块 都是用的第二数据源 业务相关的在另一个模块 用第一数据源
我就放一下登录的流程shiro在用户登录的时候调UserService的login方法 login方法调SysUserDao的getUser4Auth方法

![Service层](https://user-images.githubusercontent.com/46079468/86331098-2ff7f500-bc7b-11ea-8f9a-43f91525a29d.png)

![Dao层](https://user-images.githubusercontent.com/46079468/86331321-836a4300-bc7b-11ea-9921-46bfd396782a.png)

因为语句很简单 我就直接写在Dao层了

**Comment by ls9527** [comment]
目前的问题就是走的mater数据源, 没走test数据源.   产生这种问题的原因又两种,  
第一种就是切面没切到这个类,
第二种就是外部还有一层事物已经选择了master库, 所以后续的都只能走master库.    


你运行到 SysUserServiceImpl.login 的地方后,  对调用栈截图,  然后还有 sysUserServiceImpl 的代理类的 advisors 展开截图.
通过这两个图就能定位到具体原因了

**Comment by ls9527** [comment]
作者建了一个QQ群:   1132021421   ,  加群解决更快

**Comment by hxy6699** [comment]
我是直接在类上做的配置 然后写数据都能写到第二数据源 读的时候就变成走第一数据源了 很郁闷

**Comment by ls9527** [comment]
读的时候前面是不是还有事物?  看起来前面的事物已经选择了第一数据源

**Comment by hxy6699** [comment]
应该没有了 controller进来之后就直接调的service层方法 而且这个模块的所有的service类我都加上DS注解了 都用的第二数据源
![image](https://user-images.githubusercontent.com/46079468/86335227-ced32000-bc80-11ea-97fb-819c49d76f1d.png)

**Comment by hxy6699** [comment]
感谢大佬的解答
问题原因是这个项目使用了shiro 其中使用第二数据源中的一些表做登录和权限
springboot在项目启动的时候往realm中注入service的时候没有将切面也注入进去
结果在后续的查询过程中使用默认的第一数据源
解决办法为在realm中使用ApplicationContext获取bean手动注入service 而且不能写在构造方法里
放在realm里需要的地方懒加载调用
