### ISSUE TITLE
多数据源 xa / atomik  是否支持， 多数据源中使用不同类型的数据库时，数据源为什么没有配置validationQuery

### ISSUE THREAD

**Issue by lucian521** [baomidou/dynamic-datasource-spring-boot-starter#247]
# Enviroment

JDK Version(required): 

SpringBoot Version(required): 

dynamic-datasource-spring-boot-starter Version(required):

druid Version(optional):

# Describe
多数据源 xa / atomik  是否支持， 多数据源中使用不同类型的数据库时，数据源为什么没有配置validationQuery，  查看源码中validationQuery  并没有设置到数据源中呀

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
1.不支持。
2.每个数据源手动配置validationQuery.
源码DruidConfig 159行左右

**Comment by lucian521** [comment]
@huayanYu   您好  DruidConfig 中确实是有 validationQuery，  但DruidConfig 是统一配置参数， 如果一个应用中 多个数据源， 有mysql   oracle  等， 那不同的数据库  validationQuery 应该是不同的呀

**Comment by huayanYu** [comment]
@lucian521 请仔细阅读文档，支持单独配置
