### ISSUE TITLE
在控制层使用service的查询包装链如query，lambdaQuery，update，lambdaUpdate，service层ds失效

### ISSUE THREAD

**Issue by xjzrc** [baomidou/dynamic-datasource-spring-boot-starter#25]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.1.3.RELEASE

Starter Version(required):2.5.0

# Describe
控制层Controller使用如下查询：
```java
xxService.lambdaQuery().like(Objects.nonNull(name), Xx::getName, name).page(this.getSortPage())
```
Service层DS配置如下：
```java
@Service
@DS("hive")
public class XxServiceImpl extends ServiceImpl<XxMapper, Db> implements IXxService {
}
```
Expected Result: 使用hive数据源

Actual Result:  使用了默认数据源

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3 

目前项目解决如下：  
1.将@DS("hive")注解配置在XxMapper上。
2.将Controller的调用链查询封装在Service层。

**Comment by huayanYu** [comment]
无法解决，只能包一次。建议就采用封装在Service层上
