### ISSUE TITLE
使用动态数据源时SeataAT的undo_log的记录不会删除

### ISSUE THREAD

**Issue by a364176773** [baomidou/dynamic-datasource-spring-boot-starter#250]
# Enviroment

JDK Version(required): 1.8
SpringBoot Version(required): 2.2.0

dynamic-datasource-spring-boot-starter Version(required):3.1.1

druid Version(optional):

# Describe
https://github.com/seata/seata/issues/2878
Seata的自动代理与mp动态数据源组件有兼容性问题.
问题原因

mp帮助进行了多数据源的手动代理->seata自动代理了DynamicRoutingDataSource->dynamic拿到seata自动代理后的DynamicRoutingDataSource传入ds(数据源标识)->return 对应的数据源.

兼容方案需要与作者进行一个简单的沟通.

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
进我QQ群1132021421 来聊呢？人不多. @a364176773

**Comment by huayanYu** [comment]
https://github.com/baomidou/dynamic-datasource-spring-boot-starter/issues/137
