### ISSUE TITLE
多数据源 druid 的 maxWait 参数配置无效，其他部分有效

### ISSUE THREAD

**Issue by landashu** [baomidou/dynamic-datasource-spring-boot-starter#254]
# Enviroment
windows
JDK Version(required): 
1.8
SpringBoot Version(required): 
2.3.0.RELEASE
dynamic-datasource-spring-boot-starter Version(required):
3.1.1
druid Version(optional):
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.1.9</version>
        </dependency>
# Describe

多数据源 druid 的 maxWait 参数配置无效，其余参数配置有效，但没有全部测试，希望作者快速看下问题。

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by landashu** [comment]
包括 /druid/ 的后台sql监控配置也是无效的。


`
spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: wiedp
      datasource:
        # 主库
        wiedp:
          url: jdbc:mysql://10.240.30.33:3306/wiedp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          username: dev
#          password: dev@2020
          password: mysql@dev.2020
        # 采集库
        iedp:
          url: jdbc:mysql://10.240.30.230:3306/iedp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          username: iedp
          password: Iedp2020
      druid:
        # 初始化连接大小
        initial-size: 30
        # 最小空闲连接数
        min-idle: 20
        # 最大连接数
        maxActive: 200
        # 配置获取连接等待超时的时间
        maxWait: 10000
        # 最大等待线程数
        MaxWaitThreadCount: 10
#      # 失败后重试0次
#      connectionErrorRetryAttempts: 0

#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      # 连接空闲时间超过设置之间就测试一下连接的有效性 1分钟
#      timeBetweenEvictionRunsMillis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒,超过该时间空闲线程会被剔除 2分钟
#      minEvictableIdleTimeMillis: 120000
#      validationQuery: SELECT 1 FROM DUAL
#      # testWhileIdle：如果为true（默认true），当应用向连接池申请连接，
#      # 并且testOnBorrow为false时，连接池将会判断连接是否处于空闲状态，如果是，则验证这条连接是否可用。
#      # testWhileIdle什么时候会起作用? 获取连接时 且 testOnBorrow=false testWhileIdle=true
#      testWhileIdle: true
#      # testOnBorrow 检测池里连接的可用性 false 不检测 true 检测.但消耗性能。
#      # 假如连接池中的连接被数据库关闭了，应用通过连接池getConnection时，都可能获取到这些不可
#      # 用的连接，且这些连接如果不被其他线程回收的话，它们不会被连接池被废除，也不会重新被创建，
#      # 占用了连接池的名额，项目本身作为服务端，数据库链接被关闭，客户端调用服务端就会出现大量的timeout，客户端设置了超时时间，然而主动断开，服务端必然出现close_wait。
#      testOnBorrow: false
#      # 会影响性能
#      testOnReturn: false
#      # 打开PSCache，并且指定每个连接上PSCache的大小
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
#      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      # filters: stat,wall,log4j
#      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
#      # 配置DruidStatFilter
#      web-stat-filter:
#        enabled: true
#        url-pattern: "/*"
#        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
#      # 配置DruidStatViewServlet
        stat-view-servlet:
          url-pattern: "/druid/*"
          # IP白名单(没有配置或者为空，则允许所有访问)
          allow: 127.0.0.1
          # IP黑名单 (存在共同时，deny优先于allow)
          deny: 192.168.1.73
          #  禁用HTML页面上的“Reset All”功能
          reset-enable: false
          # 登录名
          login-username: admin@2020
          # 登录密码
          login-password: 123456@2020
`

**Comment by landashu** [comment]
druid 包括后台配置也是无效的，以下是我的配置文件信息


spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: wiedp
      datasource:
        # 主库
        wiedp:
          url: jdbc:mysql://0.0.0.0:3306/wiedp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          username: aaa
#          password: aaa
          password: aaa
        # 采集库
        iedp:
          url: jdbc:mysql://0.0.0.0:3306/iedp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          username: aaa
          password: aaa
      druid:
        # 初始化连接大小
        initial-size: 30
        # 最小空闲连接数
        min-idle: 20
        # 最大连接数
        maxActive: 200
        # 配置获取连接等待超时的时间
        maxWait: 10000
        # 最大等待线程数
        MaxWaitThreadCount: 10
#      # 失败后重试0次
#      connectionErrorRetryAttempts: 0

#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      # 连接空闲时间超过设置之间就测试一下连接的有效性 1分钟
#      timeBetweenEvictionRunsMillis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒,超过该时间空闲线程会被剔除 2分钟
#      minEvictableIdleTimeMillis: 120000
#      validationQuery: SELECT 1 FROM DUAL
#      # testWhileIdle：如果为true（默认true），当应用向连接池申请连接，
#      # 并且testOnBorrow为false时，连接池将会判断连接是否处于空闲状态，如果是，则验证这条连接是否可用。
#      # testWhileIdle什么时候会起作用? 获取连接时 且 testOnBorrow=false testWhileIdle=true
#      testWhileIdle: true
#      # testOnBorrow 检测池里连接的可用性 false 不检测 true 检测.但消耗性能。
#      # 假如连接池中的连接被数据库关闭了，应用通过连接池getConnection时，都可能获取到这些不可
#      # 用的连接，且这些连接如果不被其他线程回收的话，它们不会被连接池被废除，也不会重新被创建，
#      # 占用了连接池的名额，项目本身作为服务端，数据库链接被关闭，客户端调用服务端就会出现大量的timeout，客户端设置了超时时间，然而主动断开，服务端必然出现close_wait。
#      testOnBorrow: false
#      # 会影响性能
#      testOnReturn: false
#      # 打开PSCache，并且指定每个连接上PSCache的大小
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
#      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      # filters: stat,wall,log4j
#      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
#      # 配置DruidStatFilter
#      web-stat-filter:
#        enabled: true
#        url-pattern: "/*"
#        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
#      # 配置DruidStatViewServlet
        stat-view-servlet:
          url-pattern: "/druid/*"
          # IP白名单(没有配置或者为空，则允许所有访问)
          allow: 127.0.0.1
          # IP黑名单 (存在共同时，deny优先于allow)
          deny: 192.168.1.73
          #  禁用HTML页面上的“Reset All”功能
          reset-enable: false
          # 登录名
          login-username: admin@2020
          # 登录密码
          login-password: 123456@2020

**Comment by landashu** [comment]
druid  监控配置也是无效的

**Comment by huayanYu** [comment]
请查看示例项目，都没有问题。 检查配置。
