### ISSUE TITLE
@DS不建议加在mapper上的原因是？

### ISSUE THREAD

**Issue by fyyyr** [baomidou/dynamic-datasource-spring-boot-starter#259]
@DS 可以注解在方法上和类上，同时存在方法注解优先于类上注解。强烈建议只注解在service实现上。
然而实际可能会在Service方法中调用多个不同的Mapper接口来访问数据库，例如先查询再修改，这样该方法对数据库的多次访问将无法切换数据源。考虑到这样的情形，注解直接加在Mapper上是最好的。
既然不建议加在mapper上，原因是什么？可能会出现数据源切换不及时，以至于先查询，再切换数据源？还是其他原因？

**Comment by huayanYu** [comment]
1. 底层代码兼容性，从3.2.0才解决大部分注解在mapper上可能发生的异常。  在service上注解就没那么多问题。
2. 个人认为service才是业务属性，它负责决定选什么库。
3. 如果确定某个mapper就只属于某个ds，可以注解在mapper上。
