### ISSUE TITLE
在主库事务中,切换从库DS失败

### ISSUE THREAD

**Issue by fasoal** [baomidou/dynamic-datasource-spring-boot-starter#26]
# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
2.0.4.RELEASE
Starter Version(required):
2.5.1
# Describe
![image](https://user-images.githubusercontent.com/14243815/53856350-882dd100-400c-11e9-8993-f5731ca34f86.png)
pcReportConfigService的指定其他DS就会失败

**Comment by huayanYu** [comment]
不支持事物！！！

**Comment by fasoal** [comment]
了解了

**Comment by esonChe** [comment]
这个框架是怎么去掉mybatis-plus的事物

**Comment by huayanYu** [comment]
@esonChe 也不是说不能去掉， 至少从设计上来说我不会去掉。 如果你想去掉可以改源码，或者自己手动copy一份mybatis-plus的serviceImpl吧事物全去掉。

**Comment by esonChe** [comment]
好的谢谢

**Comment by esonChe** [comment]
为什么我去掉mybatis-plus的serviceImpl  中的事物  好像还是不能正常切换，切换注解  我是放service中
![image](https://user-images.githubusercontent.com/43061140/53868958-24b69a00-4032-11e9-9ceb-bd1397af3671.png)

**Comment by huayanYu** [comment]
@esonChe 具体描述或者查看文档自己调试。

**Comment by esonChe** [comment]
![image](https://user-images.githubusercontent.com/43061140/53869729-bb378b00-4033-11e9-9634-b4ec4c65339f.png)
正常的话切换到
![image](https://user-images.githubusercontent.com/43061140/53869776-d6a29600-4033-11e9-91b8-aa8f29d5e359.png)库，
