### ISSUE TITLE
使用druid  wallfilter时,如果使用自定义diver,无法正确设置dbtype

### ISSUE THREAD

**Issue by gaochuanneu** [baomidou/dynamic-datasource-spring-boot-starter#260]
使用druid  wallfilter时,如果使用自定义diver,无法正确设置dbtype,建议能象druid一样在单独数据源配置的地方配置dbtype,现在filter初始化的地方只能覆盖扩展,比较暴力,希望大佬下个版本支持使用人员自己更优雅的扩展

**Comment by huayanYu** [comment]
我不用druid，不懂你具体在说什么。  
请详细描述。
有能力也可以直接提交代码。

**Comment by huayanYu** [comment]
没有更多消息，关闭。
