### ISSUE TITLE
不支持Spring Batch中切换数据源

### ISSUE THREAD

**Issue by imefox** [baomidou/dynamic-datasource-spring-boot-starter#265]
# Enviroment

JDK Version(required): 
JDK 1.8

SpringBoot Version(required): 
2.3.2

dynamic-datasource-spring-boot-starter Version(required):
3.2.0

druid Version(optional):
non

# Describe
不支持在Spring Batch中切换数据源， @DS注解无法动态切换数据源

**Comment by huayanYu** [comment]
请fork项目，参考示例项目提供一个简单可复现的环境。
或者详细描述复现过程。

**Comment by huayanYu** [comment]
@imefox 请及时回复或加QQ群详聊。

**Comment by huayanYu** [comment]
没有更多消息，关闭。其他人有类似问题请提供示例代码或详细步骤。
