### ISSUE TITLE
数据源切换无法拦截protected方法

### ISSUE THREAD

**Issue by syc87** [baomidou/dynamic-datasource-spring-boot-starter#266]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.3.2

dynamic-datasource-spring-boot-starter Version(required): 3.2.0

druid Version(optional):

# Describe
版本从3.1.1升级到3.2发现，某些方法没有正常切换数据源，调试后发现新版本修改了搜索DS注解的方式，其中有一个判断是
if (!Modifier.isPublic(method.getModifiers())) {
    return null;
}
我判断这里估计是想提高效率，因为spring不可能代理private方法，但是spring并不是只能代理public方法，protected同样也能被代理，只是不常用罢了。

PS：我之所以采用protected声明方法，是因为这个方法是作为调度使用的，而调度的声明不是通过代码显式调用而是注解声明，也就是说这个方法并没有对外提供接口，也没必要声明为public，出于最小权限原则就只声明为protected（如果不是aop无法拦截private，其实private更合适）

出于严谨建议修改。

**Comment by ls9527** [comment]
预计在 3.3.0 版本加入配置 allowPublicOnly,  默认还是只拦截public方法,  可以在 spring.dynamic.datasource.allow-public-only 配置为false, 就会支持protected方法了

**Comment by huayanYu** [comment]
3.2.1 发布中

**Comment by huayanYu** [comment]
allowed-public-only
