### ISSUE TITLE
可否对不同数据源进行不同的配置

### ISSUE THREAD

**Issue by ldgithub2199** [baomidou/dynamic-datasource-spring-boot-starter#267]
比如一个数据源开启驼峰转换，一个数据源不开启

**Comment by huayanYu** [comment]
这个属于其他插件支持的问题，本数据源只负责创建和切换。
建议你咨询其他相关软件。
不过大概率是不会支持的。
除非你抛弃本插件，自己手动创建多个数据源，每个数据源分贝手动配置事务等。
