### ISSUE TITLE
在JBOSS下，复杂业务逻辑中事务会失效

### ISSUE THREAD

**Issue by whli745** [baomidou/dynamic-datasource-spring-boot-starter#269]
# Enviroment

JDK Version(required):  1.8

SpringBoot Version(required):  2.3.2.RELEASE

dynamic-datasource-spring-boot-starter Version(required): 3.2.0

Hikari Version(optional): 2.2.0

# Describe
在使用JBOSS发布单体WAR服务时，实际过程中复杂业务逻辑抛出异常，但异常前的事务未回滚；比如先插入用户，后插入用户与角色关系时抛出异常，用户仍然插入数据库

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
不支持事务
