### ISSUE TITLE
建议支持单库事务

### ISSUE THREAD

**Issue by fasoal** [baomidou/dynamic-datasource-spring-boot-starter#27]
# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
2.0.4
Starter Version(required):
2.5.1
# Describe
我这边的情况如下
主库 增删改查,.其他得库只是查询
建议还是可以支持这种情况的事务处理

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
这和你具体什么操作没关系，这就是多库事务。 暂时不支持，在研究。
