### ISSUE TITLE
这个seata 支持SQL server吗

### ISSUE THREAD

**Issue by tangmingze7280** [baomidou/dynamic-datasource-spring-boot-starter#282]
# Enviroment
windows
JDK Version(required): 
1.8
SpringBoot Version(required): 
2.0.6.RELEASE
dynamic-datasource-spring-boot-starter Version(required):
3.3.1
druid Version(optional):
1.1.22
# Describe

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
我觉得去seata那边问或者仔细看seata文档更好，我其实也不清楚。
