### ISSUE TITLE
druid升级到1.1.24，有时候会导致dynamic找不到datasource

### ISSUE THREAD

**Issue by qq592304796** [baomidou/dynamic-datasource-spring-boot-starter#284]
# Enviroment

JDK Version(required): 
1.8

SpringBoot Version(required): 
2.2.1

dynamic-datasource-spring-boot-starter Version(required):
3.2.0

druid Version(optional):
1.1.24

# Describe
项目中有配置10个数据源，有时候会导致加载数据源找不到DynamicRoutingDataSource，好像是druid1.1.24修复了一个创建数据源的bug导致的

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
那就去druid提哇0 0
