### ISSUE TITLE
没有看到示例项目了

### ISSUE THREAD

**Issue by a619646645** [baomidou/dynamic-datasource-spring-boot-starter#286]
示例项目的链接都挂了啊
 https://github.com/baomidou/dynamic-datasource-spring-boot-starter/tree/master/samples/sharding-jdbc-sample

https://gitee.com/baomidou/dynamic-datasource-samples

这些都404了，，，

**Comment by huayanYu** [comment]
https://github.com/dynamic-datasource/dynamic-datasource-samples
