### ISSUE TITLE
集成Quartz的文档是不是有问题，我根据文档操作还是会被主数据源覆盖

### ISSUE THREAD

**Issue by liunancun** [baomidou/dynamic-datasource-spring-boot-starter#289]
参考集成Quartz的文档：
https://baomidou.gitee.io/dynamic-datasource-doc/guide/integration/Quartz.html

在org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration中也存在SchedulerFactoryBeanCustomizer的定义，他会覆盖MyQuartzAutoConfiguration的配置

@Bean
@Order(0)
public SchedulerFactoryBeanCustomizer dataSourceCustomizer(QuartzProperties properties, DataSource dataSource,
		@QuartzDataSource ObjectProvider<DataSource> quartzDataSource,
		ObjectProvider<PlatformTransactionManager> transactionManager) {
	return (schedulerFactoryBean) -> {
		DataSource dataSourceToUse = getDataSource(dataSource, quartzDataSource);
		schedulerFactoryBean.setDataSource(dataSourceToUse);
		PlatformTransactionManager txManager = transactionManager.getIfUnique();
		if (txManager != null) {
			schedulerFactoryBean.setTransactionManager(txManager);
		}
	};
}

又不敢去掉spring.quartz.job-store-type=jdbc配置，因为JdbcStoreTypeConfiguration中还有其他配置，除非完全复写JdbcStoreTypeConfiguration配置，感觉有点复杂

**Comment by liunancun** [comment]
https://github.com/dynamic-datasource/dynamic-datasource-samples/tree/master/quartz-sample
直接运行这个例子的话也是会用master数据源

**Comment by huayanYu** [comment]
只能保证数据库是独立的。 操作还是需要手动切数据源。 
你应该需要静态注入。

**Comment by liunancun** [comment]
@huayanYu 我的问题是怎么集成Quartz，用文档里面的quartz-sample集成，直接运行数据库错了

**Comment by huayanYu** [comment]
@liunancun 你的错了是什么意思， 没问题啊。 群里都是这么用的。 有更细致的问题进群问吧。

**Comment by warthur1214** [comment]
不要把Quartz的DataSource注册为Bean，给Quartz单独设置DataSource
```ruby
@Configuration
@Setter
@ConfigurationProperties(prefix = "spring.datasource.dynamic.quartz")
public class QuartzConfig {

    private String driverClassName;
    private String jdbcUrl;
    private String userName;
    private String password;

    @Bean
    public SchedulerFactoryBeanCustomizer schedulerFactoryBeanCustomizer() {
        return bean -> bean.setDataSource(getDataSource());
    }

    /**
     * Quartz 的DataSource不再声明成bean使用
     */
    public HikariDataSource getDataSource() {
        HikariDataSource dataSource = new HikariDataSource();
        dataSource.setDriverClassName(driverClassName);
        dataSource.setJdbcUrl(jdbcUrl);
        dataSource.setUsername(userName);
        dataSource.setPassword(password);
        return dataSource;
    }
}
```
