### ISSUE TITLE
Hikari连接池不兼容jdbcUrl属性的加载

### ISSUE THREAD

**Issue by JonasHua2013** [baomidou/dynamic-datasource-spring-boot-starter#292]
DataSourceProperty中无jdbcUrl属性，直接使用url属性进行加载，连接中配置的jdbc-url获取不到，在初始化hikari时报错jdbcUrl未找到。
建议在DataSourceProperty中兼容下jdbc-url属性的注入
private String jdbcUrl;
public String getUrl() {
        return url==null?decrypt(jdbcUrl):decrypt(url);
    }

**Comment by huayanYu** [comment]
不做兼容，自己保证连接正确。
