### ISSUE TITLE
希望新版本能加全Druid的配置

### ISSUE THREAD

**Issue by jlcon** [baomidou/dynamic-datasource-spring-boot-starter#295]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.3.3

dynamic-datasource-spring-boot-starter Version(required):3.2.1

druid Version(optional):1.1.22

# Describe

Druid的部分配置属性缺失

Expected Result: 

希望补全druid全部属性

Actual Result:  

例如：
async-close-connection-enable
aop-patterns

# Steps to reproduce

- Step 1 
无

- Step 2 
无

- Step 3 
无

**Comment by huayanYu** [comment]
希望你能参与贡献代码
