### ISSUE TITLE
一个Service中，同时调用mybatisplus的insert和selectOne方法，如何进行读写库的切换呢？

### ISSUE THREAD

**Issue by houxiaodong5** [baomidou/dynamic-datasource-spring-boot-starter#296]
# Enviroment

JDK Version(required): 

SpringBoot Version(required): 

dynamic-datasource-spring-boot-starter Version(required):

druid Version(optional):

# Describe

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
自己重写加注解
