### ISSUE TITLE
请问调用mybatisplus Model里面的基础方法时，如何切换数据源？

### ISSUE THREAD

**Issue by houxiaodong5** [baomidou/dynamic-datasource-spring-boot-starter#297]
# Enviroment

JDK Version(required): JDK1.8

SpringBoot Version(required): 2.2.2

dynamic-datasource-spring-boot-starter Version(required):2.2.0

druid Version(optional):

# Describe

配置多数据源后，调用mybatisplus Model里面的基础方法时数据源无法切换，始终是固定的一个

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by ls9527** [comment]
在失效的地方进去， 然后将调用栈发出来看一下

**Comment by houxiaodong5** [comment]
已解决
