### ISSUE TITLE
多数据源切换的时候 会偶尔失效

### ISSUE THREAD

**Issue by seeyou888999** [baomidou/dynamic-datasource-spring-boot-starter#299]
# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
2.2.9
dynamic-datasource-spring-boot-starter Version(required):
3.1.0
druid Version(optional):
1.2.3

# Describe what happened

Expected Result:
多数据源来回切换的时候 会出现偶尔失效的问题

Actual Result:
druid的版本也升级了 

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
我没有3.4.0的版本

**Comment by seeyou888999** [comment]
写错的 不好意思 作者  是3.1.0

**Comment by seeyou888999** [comment]
抱歉。

**Comment by huayanYu** [comment]
升级

**Comment by seeyou888999** [comment]
现有的版本哪个最为稳定呢 ？
