### ISSUE TITLE
多数据源，全局配置和数据源本地配置问题

### ISSUE THREAD

**Issue by woshilao6** [baomidou/dynamic-datasource-spring-boot-starter#304]
3.2.1版本
               ① DruidConfig 的  proxyFilters自定义过滤器 无法使用本地配置，多个数据源只能使用全局配置，无法单独使用数据源的proxyFilters自定义过滤器。
               ② 数据源本地配置druid.filters无配置的时候，默认添加了stat，wall 两个Filter，是否当不主动配置的时候不默认添加。一般来讲，会自定义 stat Filter里添加一些监控什么。

**Comment by woshilao6** [comment]
③ 在 WallFilter 这里，没有使用configFromProperties方法，以至于无法分数据源设置 logViolation 和throwException 两个属性。

综合以上三条：如果想在不同数据源配置不同的属性，我既不能通过proxyFilters 自己实例化两个bean来实现，又不能通过数据源内部的本地配置DruidConfig 来实现。 不同数据源只能配置相同的logViolation 和throwException，配置相同的自定义Filter。

**Comment by huayanYu** [comment]
大哥，来提PR吧。 我不用druid的。

**Comment by huayanYu** [comment]
没有回复，关闭。 期待PR
