### ISSUE TITLE
关于切换数据源

### ISSUE THREAD

**Issue by wencyGit** [baomidou/dynamic-datasource-spring-boot-starter#306]
- 切换数据源不要那么死板只能通过 @DS注解 切换数据源
- 应该可以提供根据不同的包切换不同的数据源

**Comment by huayanYu** [comment]
可以啊，自己写。 就像spring事务一样，可以注解，也可以定义切面，自己研究下。

**Comment by wencyGit** [comment]
@huayanYu 我是想说这个starter可以支持，，，自己写我知道可以实现

**Comment by huayanYu** [comment]
老版本支持。 可以看源码参考写，建议还是自己实现。

**Comment by wencyGit** [comment]
- 看了源码可以自己写AOP手动调用 DynamicDataSourceContextHolder.push("master");指定数据源
```
    @Before("master()")
    public void doBeforeAdviceMaster(JoinPoint joinPoint) {
        DynamicDataSourceContextHolder.push("master");
    }
```
