### ISSUE TITLE
使用了dynamic配置了druid连接池，wall默认是开启的，怎么配置关闭，

### ISSUE THREAD

**Issue by Rookie-F** [baomidou/dynamic-datasource-spring-boot-starter#308]
# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
2.1.4
dynamic-datasource-spring-boot-starter Version(required):
2.2.0
druid Version(optional):
1.1.9

# Describe what happened
![image](https://user-images.githubusercontent.com/36975380/100313155-f4294780-2fee-11eb-8344-7e5575e90b91.png)
这里描述的wall是默认开启的，在这个默认开启的情况下我运行的sql会报如下错误：

\r\n### Error updating database.  Cause: java.sql.SQLException: sql injection violation, class com.alibaba.druid.sql.ast.statement.SQLIfStatement not allow 

以下是我的配置
![image](https://user-images.githubusercontent.com/36975380/100313321-5b46fc00-2fef-11eb-8ebe-caff77bf85d7.png)

Expected Result:

怎么才能关闭wall

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
改filters

**Comment by Rookie-F** [comment]
谢谢，问题及解决
修改后的配置如下
![image](https://user-images.githubusercontent.com/36975380/100316964-75380d00-2ff6-11eb-915a-7764bcbeee90.png)
