### ISSUE TITLE
@DS 能动态指定吗? 连数据库都是动态增加的,不是写死配置的,动态新增一个数据库连接马上去查

### ISSUE THREAD

**Issue by gclsoft** [baomidou/dynamic-datasource-spring-boot-starter#309]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.5

dynamic-datasource-spring-boot-starter Version(required):

druid Version(optional):

# Describe what happened

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 
@DS 能动态指定吗? 连数据库都是动态增加的,不是写死配置的,动态新增一个数据库连接马上去查;
并且查的时候, 别的用户都是独立的,各个用户都是查自己需要的数据库, 同一时间的情况下能不互相影响
这个要怎么实现呢?

**Comment by huayanYu** [comment]
仔细看完所有文档，根据SPEL
