### ISSUE TITLE
how to integrate with springmvc env（not springboot）

### ISSUE THREAD

**Issue by neil88** [baomidou/dynamic-datasource-spring-boot-starter#31]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): um, i just wanna spring

Starter Version(required):

# Describe
i have a demand need multiple datasource, meanwhile my project env just is spring, how 
could i do?

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
参考 DynamicDataSourceAutoConfiguration 自己注入吧
