### ISSUE TITLE
多数据源情况下分页问题如何处理

### ISSUE THREAD

**Issue by lxl2695693** [baomidou/dynamic-datasource-spring-boot-starter#310]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.2.10

dynamic-datasource-spring-boot-starter Version(required):3.4.1

druid Version(optional):

# Describe what happened
mybatis-plus全局配置的分页拦截器MybatisPlusInterceptor是oracle数据库，在数据源切换为mysql时，分页就不行了
Expected Result:
期待多数据源切换时都可以正常使用分页插件PaginationInnerInterceptor

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
不指定分页的具体type,让他自己每次识别应该就可以
