### ISSUE TITLE
如何对数据库密码保密

### ISSUE THREAD

**Issue by badwood316** [baomidou/dynamic-datasource-spring-boot-starter#312]
考虑到配置文件中明文写密码的不安全性，目前最简单的方法是配置文件中写上密文的密码（spring.datasource.dynamic.datasource.master.password=ENC(xxx））以及公钥（spring.datasource.dynamic.datasource.master.public-key=YYYYY）；这种方法无需自己再写代码，还是有问题，有公钥就能解开密文，得到密码。除非自己实现解密算法，这样能提高安全性。而在druid中支持的密码回调函数的方法（DruidPasswordCallback），貌似在dynamic中无法使用。
提2个建议：
1、把密码放到其他位置，比如环境变量中。密码属性直接设置为password=ENV(环境变量名)，或者文件系统等地方。这样的好处就是修改密码方便，不需要重新打包应用。
2、支持用户自定义的密码回调，增强密码解密复杂度。
开发者可以结合两者一起使用。

**Comment by huayanYu** [comment]
思路没问题，不过加密那块代码很简单。 希望你能来支持。

**Comment by huayanYu** [comment]
无回复，关闭。  希望大家多多参与进来，共同维护。

**Comment by badwood316** [comment]
我也是刚入门者，能力有限，怕做不好这事。
















在 2020-12-08 10:48:23，"小锅盖" <notifications@github.com> 写道：

无回复，关闭。 希望大家多多参与进来，共同维护。
