### ISSUE TITLE
与sharding-jdbc-spring-boot-starter集成无法找到masterSlaveDataSource

### ISSUE THREAD

**Issue by ErickPang** [baomidou/dynamic-datasource-spring-boot-starter#314]
JDK Version(required):  jdk8

SpringBoot Version(required):  2.3.6.RELEASE

dynamic-datasource-spring-boot-starter Version(required):  3.2.0

druid Version(optional):   <druid-spring-boot.version>1.1.22</druid-spring-boot.version>

配置参照：https://baomidou.gitee.io/dynamic-datasource-doc/guide/integration/ShardingJdbc.html#%E5%9F%BA%E7%A1%80%E4%BB%8B%E7%BB%8D

启动没有问题，实际访问接口操作表时报No bean named 'masterSlaveDataSource' available：

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'masterSlaveDataSource' available

在代码中引用的资源name="masterSlaveDataSource"
<img width="826" alt="sharding" src="https://user-images.githubusercontent.com/6110616/101236008-61805b00-3708-11eb-8a03-d1a87d206462.png">

**Comment by huayanYu** [comment]
@AutoConfigureBefore(DynamicDataSourceAutoConfiguration.class)

试试

**Comment by ErickPang** [comment]
在自定义的ShardingDataSourceConfiguration配置中加上了，通过debug看到masterSlaveDataSource提示异常。
`@Lazy
    @Resource(name = "masterSlaveDataSource")
    private DataSource masterSlaveDataSource;`
获取到的masterSlaveDataSource是如下的错误，感觉是没有初始化成功。
Method threw 'org.springframework.beans.factory.NoSuchBeanDefinitionException' exception. Cannot evaluate com.sun.proxy.$Proxy183.toString()

**Comment by ls9527** [comment]
错误栈要发全一些，要不然根本看不懂是什么错误。  这是未定义这个bean, 如果你的sharding-jdbc未配置主从的话名字是： shardingDataSource

**Comment by huayanYu** [comment]
@ErickPang 不知道你怎么配置的， 先看下示例项目也。  如果能用示例项目复现，麻烦上传到github，给我地址我跑一下

**Comment by ErickPang** [comment]
@huayanYu 按照您的方向已解决，主要问题在配置文件中的主从配置错误，调整后可以正常启动，非主从模式的使用shardingDataSource也可以正常启动访问正常，谢谢。
