### ISSUE TITLE
将@DS注解添加在service上，该service中有调用默认数据源的其他service，默认数据源查询缓慢

### ISSUE THREAD

**Issue by rouxiaoxiao** [baomidou/dynamic-datasource-spring-boot-starter#317]
# Enviroment

JDK Version(required): JDK8

SpringBoot Version(required): 2.0.0

dynamic-datasource-spring-boot-starter Version(required):3.1.1

druid Version(optional):1.1.10

# Describe what happened
本项目整合dynamic-datasource-spring-boot-starter和sharding，将不分表的数据设置为默认数据源走普通jdbc，分表数据设置@DS注解走sharding jdbc。将@DS注解添加在service上，该service中有调用默认数据源的其他service，默认数据源查询缓慢。直接执行查询cost=700ms左右，如果放在@DS注解下的其他service中调用则cost=3000ms左右。有人遇到同样的状况么？

**Comment by huayanYu** [comment]
各个地方断点查询啊， dynamic-datasource-spring-boot-starter在运行时其实只负责了在当前线程设置数据源KEY，然后调用原生的datasource取一个连接出来。 性能瓶颈肯定不是dynamic-datasource-spring-boot-starter
