### ISSUE TITLE
为什么不支持原生spring事务？都用seata做事务压力会很大。

### ISSUE THREAD

**Issue by 15168326318** [baomidou/dynamic-datasource-spring-boot-starter#319]
seata事务性能不会很高，它额外要增加对表的很多操作，成本不小。spring 本地食物几乎没什么性能损耗，而且大部分都是需要本地事务，不需要分布式事务。
     现在一刀切都只能使用分布式事务，我觉得不太好。应该要支持原生spring事务.

**Comment by huayanYu** [comment]
准确的说是原生spring事务不支持多数据源。 下周会上线一个新的本地事务方案，但是仍然支持不了spring注解。
master可以查看代码。

非常希望你能参与开发代码，支持spring事务，

**Comment by zhangxiangfeng** [comment]
> 准确的说是原生spring事务不支持多数据源。 下周会上线一个新的本地事务方案，但是仍然支持不了spring注解。
> master可以查看代码。
> 
> 非常希望你能参与开发代码，支持spring事务，

”支持spring事务“  要写 这个确实 得有点儿东西 。😂
