### ISSUE TITLE
xml中字符串拼接如："%"#{search,jdbcType=VARCHAR}"%"   不支持

### ISSUE THREAD

**Issue by xbox1994** [baomidou/dynamic-datasource-spring-boot-starter#321]
xml中：
```sql
and name like "%"#{search,jdbcType=VARCHAR}"%" 
```

报错：
sql injection violation, syntax error: syntax error, error in :'name like "%"?"%"', expect RPAREN, actual QUES pos 549, line 22, column 43, token QUES :

不用这个多数据源插件，用原生的单数据源查询是可以支持的

改成
```sql
and name like concat('%', #{search,jdbcType=VARCHAR},'%')
```
就可以了，问题：如果不支持字符串拼接，请在说明文档中警告开发者

**Comment by huayanYu** [comment]
我可以很明确的告诉你，和本插件无关。 请自行查找问题。
