### ISSUE TITLE
关于多数据源切换问题，A、B、C三个独立数据源，A-->B-->C调用关系

### ISSUE THREAD

**Issue by 1181888200** [baomidou/dynamic-datasource-spring-boot-starter#322]
是否可以简绍一下是如果切换后再回到之前的数据源上的

**Comment by zhangxiangfeng** [comment]
> 是否可以简绍一下是如果切换后再回到之前的数据源上的

这个很简单的，ThreadLocal存储的是栈，后进先出。每次开启新的jdbc连接的时候，都会去获取数据源，然后从ThreadLocal拿到当前的，就获取到对应的数据源了。如果还是不明白，提供QQ号出来，我远程给你解释。
