### ISSUE TITLE
使用了@Transactional(rollbackFor = Exception.class)-导致动态失效

### ISSUE THREAD

**Issue by zhangxiangfeng** [baomidou/dynamic-datasource-spring-boot-starter#323]
**示例代码在这里，基于你们发的示例，做微小改动：**

https://gitee.com/foreign-resources-mirrors/dynamic-datasource-samples/blob/master/jdbc-template-sample/src/main/java/com/baomidou/samples/jdbc/controller/UserController.java

**然后调用接口：**

数据源就不会发生切换了，一直是master、

**Comment by zhangxiangfeng** [comment]
已经尝试，通过隔离事务进行解决。

@Transactional(rollbackFor = Exception.class, propagation = Propagation.NOT_SUPPORTED)

**Comment by ShuningWan** [comment]
> 已经尝试，通过隔离事务进行解决。
> 
> @transactional(rollbackFor = Exception.class, propagation = Propagation.NOT_SUPPORTED)
这样你的代码不就没有事务了么
