### ISSUE TITLE
Service层的一个方法中可以直接切换多个数据源吗，测试切换不了

### ISSUE THREAD

**Issue by zm935580231** [baomidou/dynamic-datasource-spring-boot-starter#324]
# Enviroment

JDK (required): 1.8

SpringBoot Version(required): 2.0.4

dynamic-datasource-spring-boot-starter Version(required):2.5.5

druid Version(optional):1.1.9

# Describe what happened
Service层的一个方法中可以直接切换多个数据源吗，测试切换不了

# Steps to reproduce

![image](https://user-images.githubusercontent.com/22015904/102191240-18908980-3ef4-11eb-9cb4-b08809508683.png)
调用这两个方法失效，无法切换

**Comment by zhangxg1990** [comment]
现在使用3.2.0版本也没有解决，需要重新在该类方法上开启一个新的事物进行使用，这样增大了数据源连接开销
