### ISSUE TITLE
DynamicDataSourceAnnotationInterceptor Exception catch is incorrect

### ISSUE THREAD

**Issue by happier233** [baomidou/dynamic-datasource-spring-boot-starter#325]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.4.1

dynamic-datasource-spring-boot-starter Version(required):3.2.1

druid Version(optional):

# Describe what happened
com.baomidou.dynamic.datasource.aop.DynamicDataSourceAnnotationInterceptor#invoke
```Java
    @Override
    public Object invoke(MethodInvocation invocation) throws Throwable {
        try {
            String dsKey = determineDatasourceKey(invocation);
            DynamicDataSourceContextHolder.push(dsKey);
            return invocation.proceed();
        } finally {
            DynamicDataSourceContextHolder.poll();
        }
    }
```
If an exception occurs during the processing of the dsKey, the dsKey will not push into DynamicDataSourceContextHolder, but the finally block will still be executed.
dsKey determine and push should move out of the try block.
```Java
    @Override
    public Object invoke(MethodInvocation invocation) throws Throwable {
        String dsKey = determineDatasourceKey(invocation);
        DynamicDataSourceContextHolder.push(dsKey);
        try {
            return invocation.proceed();
        } finally {
            DynamicDataSourceContextHolder.poll();
        }
    }
```

**Comment by huayanYu** [comment]
@happier233 PR,tks
