### ISSUE TITLE
请问动态数据源如何与liquibase集成使用呢？

### ISSUE THREAD

**Issue by RomanticWd** [baomidou/dynamic-datasource-spring-boot-starter#33]
# Enviroment

JDK Version(required):  1.8

SpringBoot Version(required):  2.0.6

Starter Version(required): 2.5.3

# Describe

目前我在项目中使用了liquibase进行数据库版本管理，原来只有数据库A的时候，liquibase会在项目启动的时候会对数据库A进行更新，但是现在增加了动态数据源，此时我修改了数据库B，我希望在项目启动的时候也可以更新数据库B的配置。但是不知道该如何进行配置

Expected Result: 
假若我使用liquibase对数据库A、B都进行了修改，希望项目启动的时候能够帮我更新数据库。
Actual Result:  
只能更新数据库A。
# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
我没用过liquibase,很难实现。

**Comment by yuenke** [comment]
@RomanticWd 你好，我现在有个和你一样的需求。
这种方式的liquibase你实现了么，还是换成其它方案了？
