### ISSUE TITLE
java.lang.NoClassDefFoundError: io/seata/rm/datasource/SeataDataSourceProxy

### ISSUE THREAD

**Issue by MisterBowie** [baomidou/dynamic-datasource-spring-boot-starter#332]
# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
2.2.5.RELEASE
dynamic-datasource-spring-boot-starter Version(required):
3.4.1
druid Version(optional):
没有使用

# Describe what happened

Expected Result:
ok

Actual Result:
java.lang.NoClassDefFoundError: io/seata/rm/datasource/SeataDataSourceProxy

**Comment by MisterBowie** [comment]
seata version 1.2.0

**Comment by MisterBowie** [comment]
seata-spring-boot-starter version 1.2.0

**Comment by huayanYu** [comment]
没有3.4.1 只有3.3.1

**Comment by huayanYu** [comment]
无回复，关闭

**Comment by k300moom** [comment]
我在配置多数据源后启动时也报错 
JDK Version(required):
1.8
SpringBoot Version(required):
2.2.6.RELEASE
dynamic-datasource-spring-boot-starter Version(required):
3.3.0

**Comment by xiaobu1994** [comment]
> 我在配置多数据源后启动时也报错
> JDK Version(required):
> 1.8
> SpringBoot Version(required):
> 2.2.6.RELEASE
> dynamic-datasource-spring-boot-starter Version(required):
> 3.3.0
> java.lang.NoClassDefFoundError: io/seata/rm/datasource/SeataDataSourceProxy

我也报这个

**Comment by xiaobu1994** [comment]
> > 我在配置多数据源后启动时也报错
> > JDK Version(required):
> > 1.8
> > SpringBoot Version(required):
> > 2.2.6.RELEASE
> > dynamic-datasource-spring-boot-starter Version(required):
> > 3.3.0
> > java.lang.NoClassDefFoundError: io/seata/rm/datasource/SeataDataSourceProxy
> 
> 我启动项目不报 但是junit测试我也报这个

**Comment by wangxiang1993** [comment]
> > > 我在配置多数据源后启动时也报错
> > > JDK Version(required):
> > > 1.8
> > > SpringBoot Version(required):
> > > 2.2.6.RELEASE
> > > dynamic-datasource-spring-boot-starter Version(required):
> > > 3.3.0
> > > java.lang.NoClassDefFoundError: io/seata/rm/datasource/SeataDataSourceProxy
> > 
> > 
> > 我启动项目不报 但是junit测试我也报这个

哥们，解决了吗？我也是同样的问题。
