### ISSUE TITLE
加载的数据源数量问题

### ISSUE THREAD

**Issue by jk8800331** [baomidou/dynamic-datasource-spring-boot-starter#333]
首先肯定框架是非常好用的，解决了业务上很多问题，实际使用过程中遇到如下问题：
1、可以配置多少个数据源？我现在配置了300多个数据库，偶尔会有某个库无法使用
2、是否支持分布式方案？例如将数据源加载到Redis中获取
3、启动时如果数据库的账号密码写错了，不会报错，一直卡住
4、 从源码中DynamicDataSourceContextHolder.push();这个方法切库，不知道是否可行

**Comment by huayanYu** [comment]
1.数量和内存有关，无法使用应该是你数据源本身问题。 框架核心源码都是网上烂大街的逻辑。~不会有什么问题了。
2. 支持的，仔细读文档。 可以自己扩展加载数据源。
3. 无法解决，这是连接池控制的事情。有的连接池会一直尝试，如druid似乎可以配置多少次不尝试。 我不熟悉，也不会去控制。
4. 可行，如无特殊需求不建议。

**Comment by huayanYu** [comment]
@jk8800331

**Comment by huayanYu** [comment]
无后续回复，关闭
