### ISSUE TITLE
@DS注解配置在Service实现类上，Controller使用lambdaQuery().list()切换失败

### ISSUE THREAD

**Issue by jzcccc** [baomidou/dynamic-datasource-spring-boot-starter#337]
# Enviroment

JDK Version(required): jdk1.8.0_261

SpringBoot Version(required): 2.4.1

dynamic-datasource-spring-boot-starter Version(required):3.3.1

druid Version(optional):1.2.4

mybatis-plus Version:3.4.0

# Describe what happened

@DS()在Service实现类上配置多数据源，controller中使用 .lambdaQuery().list();切换失败。

试过 @DS配置在mapper类上时可以，切换成功；配置在Service实现类的自己写的方法上时，也切换成功

![image](https://user-images.githubusercontent.com/26700791/104427630-6e715380-55be-11eb-910c-3eb2dae6297d.png)

![image](https://user-images.githubusercontent.com/26700791/104427895-c14b0b00-55be-11eb-8bb6-e2c222ff252b.png)

**Comment by huayanYu** [comment]
无法解决，底层是基于aop。 直接调用lambdaQuery不会走aop。 
后续会在文档补充，  解决方法只有在service层封装个方法，在里面处理逻辑。
@jzcccc
