### ISSUE TITLE
Dynamic DataSource未找到关闭web-stat-filter

### ISSUE THREAD

**Issue by zhengzhaojian** [baomidou/dynamic-datasource-spring-boot-starter#34]
# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
1.5.1
Starter Version(required):
2.5.3
# Describe
使用MockMvc测试多数据源整合Druid时，Druid的WebStatFilter报空指针异常。
在百度找到了如下解决办法：https://gitee.com/jinglun404/DLXD/issues/IGCM9
发现Dynamic DataSource未找到关闭web-stat-filter的属性

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
spring:
  datasource:
    dynamic:
      druid:
        "filters": ""
//手动去掉默认的stat,wall
