### ISSUE TITLE
当使用springbatch去整合的时候，切换数据源会不成功，因为springbatch中如果操作多个数据源不能操作

### ISSUE THREAD

**Issue by zhouzhonghui** [baomidou/dynamic-datasource-spring-boot-starter#340]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 

SpringBoot Version(required): 

dynamic-datasource-spring-boot-starter Version(required):

druid Version(optional):

# Describe what happened

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
请补充详细说明重新提ISSUE。

**Comment by dragontree101** [comment]
主要是因为， springbatch 在进行每一步的过程中都开启了事物， 所以无法在Step的过程中进行切换数据源

**Comment by leyan95** [comment]
@dragontree101 @huayanYu  意思就是只要使用了spring的事务，那么在同一个线程内就无法使用这个工具切换数据源了么？
我只是想查一下读库的数据，然后再处理完之后写入到另一个库中，有没有什么方式能让我在用这个工具的前提下解决我的问题？

**Comment by huayanYu** [comment]
@leyan95 读的时候不用事务或者单独事务，写的时候单独开事务不就行了。

**Comment by leyan95** [comment]
@huayanYu
感谢您的回复，
Springbatch 在进行每一步的过程中都开启了事务，目前我还没有找到能够控制springbatch不自动开启事务的扩展点，我再去找找资料如果还是不行那我到时写一个demo就劳烦阁下帮我看看了☺。

**Comment by studyAction** [comment]
@wu9007 请问问题解决了吗，最近我也遇到这个问题。
