### ISSUE TITLE
报错Caused by: java.lang.RuntimeException: dynamic-datasource Please check the setting of primary 但是打包maven之后就好了

### ISSUE THREAD

**Issue by tangmingze7280** [baomidou/dynamic-datasource-spring-boot-starter#341]
# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
2.0.6.RELEASE
dynamic-datasource-spring-boot-starter Version(required):
3.3.1
druid Version(optional):
1.2.1

# Describe what happened

Expected Result:
应该是启动springboot项目

Actual Result:
并没有启动  日志报错Caused by: java.lang.RuntimeException: dynamic-datasource Please check the setting of primary

If there is an exception,or aop invalid,please attach the exception trace:
DynamicRoutingDataSource.class 中的 afterPropertiesSet
```
Just paste your stack trace here!
```
错过了 没找到

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
没有设置对Primary，文档常见问题
