### ISSUE TITLE
本地事务提问

### ISSUE THREAD

**Issue by cn-src** [baomidou/dynamic-datasource-spring-boot-starter#342]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

你好！能否在文档中说明清楚，同时也是我想问的：

1. 本地事务是解决了什么程度上的事务问题，比如：是能保证同一个注解的范围里，同数据源操作的事务一致性；
还是说能做到一定程度的分布式事务，同一个注解的范围里不同数据源的一致性？

2. 本地事务的默认回滚策略是什么？是跟spring样的 RuntimeException 和 Error 回滚么？

3. 本地事务有没有提供编程式事务控制？

# Enviroment

JDK Version(required): 

SpringBoot Version(required): 

dynamic-datasource-spring-boot-starter Version(required):

druid Version(optional):

# Describe what happened

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
1. 本地事务就是所有的涉及的commit放在一个链表，最后一起提交， 出错都回滚。
2. RuntimeException。
3. 无。
源码https://github.com/baomidou/dynamic-datasource-spring-boot-starter/blob/master/src/main/java/com/baomidou/dynamic/datasource/aop/DynamicTransactionAdvisor.java

**Comment by cn-src** [comment]
了解，感谢谢！！！
