### ISSUE TITLE
为什么不建议在mapper上添加注解

### ISSUE THREAD

**Issue by dragontree101** [baomidou/dynamic-datasource-spring-boot-starter#344]
Please fill it out carefully, or it will be closed.
我看文档上面写了

强烈建议只在Service的类和方法上添加注解，不建议在Mapper上添加注解。

但是没有写具体的理由， 请问这个是为什么，

因为我们的场景， 在一个service的一个方法下面， 会陆续去读多个数据源的数据。

目前读的话直接到了DAO层，中间并没有对应的Service层了， 如果我直接加@DS注解在DAO层会出现什么问题。

请作者进行一下解答。 谢谢

# Enviroment

JDK Version(required): 
11

SpringBoot Version(required): 
2.4.1

dynamic-datasource-spring-boot-starter Version(required):
3.3.1

**Comment by huayanYu** [comment]
请找历史ISSUE

**Comment by dragontree101** [comment]
翻了很久， 没有找到对应issue， 能给一个链接么？
谢谢！

**Comment by ls9527** [comment]
因为涉及到查找顺序的问题， 一个接口可以继承多个接口，如果多个接口的都写了查找注解，就容易引起混乱。

如果写在类或者父类上面， 按照从下往上，一直找到Object前一个类， 找到哪个类有注解就用哪个。

**Comment by dragontree101** [comment]
那如果不存在多实现， 多继承的话， 应该理论还是可以的吧。 其实service 也有可能有这种情况吧 
另外如果service有多重继承， 是不是也有这种情况？

**Comment by huayanYu** [comment]
我个人建议的核心原因是，我认为数据源是针对一组业务的。 mapper只关心执行sql。
