### ISSUE TITLE
集成Hikari时出现的问题

### ISSUE THREAD

**Issue by salveandtango** [baomidou/dynamic-datasource-spring-boot-starter#345]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.4.1

dynamic-datasource-spring-boot-starter Version(required):3.3.1

druid Version(optional):none

# Describe what happened
集成hikari进行本地测试时, 连接测试数据库可以正常使用, 上线后链接阿里云RDS数据库, 启动项目后显示非primary库连接失败, 更换为druid后则一切正常

application 

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:
spirngboot启动报错如下:
1.[com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]

2.[java.net.SocketTimeoutException: Read timed out]

Just paste your stack trace here!
集成hikari配置如下:
spring:
 datasource:
    dynamic:
      hikari:
        min-idle: 5
        max-pool-size: 40
        is-auto-commit: true
        idle-timeout: 30000
        pool-name: XXX
        max-lifetime: 120000
        connection-timeout: 60000
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: XXX
          password: XXX
          url: jdbc:mysql://XXX.mysql.rds.aliyuncs.com:3306/XXX?useUnicode=true&characterEncoding=utf-8
        yzb:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: XXX
          password: XXX
          url: jdbc:mysql://XXX.mysql.rds.aliyuncs.com:3306/XXX?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
 

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
这个明显是连接池参数配置的问题，Hikari是容易在阿里云上出现这个问题。 非本插件原因，建议搜索相关文档或联系阿里云

**Comment by salveandtango** [comment]
> 这个明显是连接池参数配置的问题，Hikari是容易在阿里云上出现这个问题。 非本插件原因，建议搜索相关文档或联系阿里云

好的, 多谢
