### ISSUE TITLE
并发调用，结果数据源切换会不及时，还是用最早切换的数据源

### ISSUE THREAD

**Issue by lxldemon** [baomidou/dynamic-datasource-spring-boot-starter#346]
# Enviroment

JDK Version(required): jdk1.8

SpringBoot Version(required): 2.2.1

dynamic-datasource-spring-boot-starter Version(required):3.1.0

druid Version(optional):

# Describe what happened
并发调用，数据源切换会不及时，还是用最早切换的数据源,导致说报错:A数据库 没有sys_user 表，这个sys_user表其实是在B数据库

Expected Result:

期望开辟新线程，独立切换

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
升级
