### ISSUE TITLE
JDBC链接neo4j失败,是否是不支持nosql

### ISSUE THREAD

**Issue by huyuanxin** [baomidou/dynamic-datasource-spring-boot-starter#348]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): openjdk alibaba dragonwell 1.8

SpringBoot Version(required): 2.0+

dynamic-datasource-spring-boot-starter Version(required):v3.0.0

druid Version(optional):

# Describe what happened
JDBC链接neo4j失败,是否是不支持nosql

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
原生JDBC能连就支持，没用过不了解

**Comment by huyuanxin** [comment]
感谢，已解决。是连接池的问题
