### ISSUE TITLE
Druid数据源如果配置了proxy-filters会引起spring上下文提前初始化，使actuator部分配置无法生效

### ISSUE THREAD

**Issue by lingjieee** [baomidou/dynamic-datasource-spring-boot-starter#353]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment
Mac OS
JDK Version(required): 
1.8.251
SpringBoot Version(required): 
2.2.5
dynamic-datasource-spring-boot-starter Version(required):
3.3.1
druid Version(optional):
1.2.4

# Describe what happened
在配置proxy-filters后，actuator上jvm相关的数据全都消失了

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
所以你有啥解决办法么？
