### ISSUE TITLE
prometheus support required

### ISSUE THREAD

**Issue by Wanxp** [baomidou/dynamic-datasource-spring-boot-starter#354]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required):2.4.1 

dynamic-datasource-spring-boot-starter Version(required):3.3.1

hikari Version(optional):3.4.5

# Describe what happened
If I use spring-data-jdbc dependency default, prometheus could collect hikari pool data and display at grafana.
But use dynamic-datasource-spring-boot-starter , promethes cannot collect any data from hikari pool.

Expected Result:
support spring-boot-starter-actuator or micrometer-registry-prometheus

Actual Result:
not support for spring-boot-starter-actuator or micrometer-registry-prometheus

dependency
```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>

```

**Comment by huayanYu** [comment]
我从来没用过这两个东西，能不能参与进来改进。

**Comment by huayanYu** [comment]
我从来没用过这两个东西，能不能参与进来改进。

**Comment by huayanYu** [comment]
从我基本的猜测，我估计也比较难实现。 单数据源只要他正常那监控就正常， 多个数据源怎么返回状态， 是全都正常才正常。还是每个数据源返回自己的状态， 返回了监控能否展示也是问题。 
感觉不是那么好处理的。

**Comment by ls9527** [comment]
could you get a demo for us?  it's a problem of the health check

**Comment by huayanYu** [comment]
试试3.3.4，不过只能监控主的。

**Comment by chachae** [comment]
> 试试3.3.4，不过只能监控主的。

大佬，为什么只能监控主，我这边用 ``HikariDataSourceCreator``手工创建 hikari 数据源然后手动设置了也不生效，只有主生效
```java
DynamicRoutingDataSource ds = (DynamicRoutingDataSource) dataSource;
DataSource dataSource = this.hikariDataSourceCreator.createDataSource(dataSourceProperty);
ItemDataSource itemDataSource = (ItemDataSource) dataSource;
HikariDataSource hikariDataSource = (HikariDataSource) itemDataSource.getRealDataSource();
hikariDataSource.setMetricsTrackerFactory(this.prometheusMetricsTrackerFactory);
ds.addDataSource(name, dataSource);
```

**Comment by chachae** [comment]
> > 试试3.3.4，不过只能监控主的。
> 
> 大佬，为什么只能监控主，我这边用 `HikariDataSourceCreator`手工创建 hikari 数据源然后手动设置了`MetricsTrackerFactory `也不生效，只有主生效
> 
> ```java
> DynamicRoutingDataSource ds = (DynamicRoutingDataSource) dataSource;
> DataSource dataSource = this.hikariDataSourceCreator.createDataSource(dataSourceProperty);
> ItemDataSource itemDataSource = (ItemDataSource) dataSource;
> HikariDataSource hikariDataSource = (HikariDataSource) itemDataSource.getRealDataSource();
> hikariDataSource.setMetricsTrackerFactory(this.prometheusMetricsTrackerFactory);
> ds.addDataSource(name, dataSource);
> ```

没事了，尝试改变 metrics tracker factory 后发现多数据源下 prometheus metrics 生效了
```JAVA
// @Autowired
// private MeterRegistry meterRegistry;

hikariDataSource.setMetricsTrackerFactory(new MicrometerMetricsTrackerFactory(this.meterRegistry));
```
