### ISSUE TITLE
请注意不要用Iservice中的默认方法，会导致多数据源不生效

### ISSUE THREAD

**Issue by showlist** [baomidou/dynamic-datasource-spring-boot-starter#355]
/**
     * 链式查询 lambda 式
     *
     * @return LambdaQueryWrapper 的包装类
     */
    default LambdaQueryChainWrapper<T> lambdaQuery() {
        return new LambdaQueryChainWrapper<>(getBaseMapper());
    }
如果使用此方法，生成lamdbaQuery后，则直接走mapper中的方法，不经过用户的自定义的serviceImpl，也就读取不到serviceImpl上的@DS注解，导致多数据源不生效。分享给大家，避坑！！！！！

**Comment by huayanYu** [comment]
后面加入到文档中，谢谢
