### ISSUE TITLE
指定了错误的 DS 名称，如何抛出异常而不是自动切换到 master 数据源

### ISSUE THREAD

**Issue by ifu25** [baomidou/dynamic-datasource-spring-boot-starter#356]
### Enviroment

- JDK Version(required): 11 （kotlin）
- SpringBoot Version(required): 2.4.3
- dynamic-datasource-spring-boot-starter Version(required):3.3.2

### Describe what happened
在 `Mpaaer` 上通过 `DS` 指定了一个`不存在的数据源名称`，结果运行的时候没有报错而在自动去 `master` 执行了，我不希望这样，如何能让抛出异常？
因为我是想在项目启动后的某个时机再去动态增加数据源，比如第一次使用某个尚未注册的数据源时再动态增加。
如图：
![20210316_165156](https://user-images.githubusercontent.com/5575008/111281494-f4218600-8677-11eb-9c59-ef73e9a79c40.png)

### Expected Result:
没有报错而是切换到了 `master` 数据源。（不希望这样）😁

**Comment by huayanYu** [comment]
注意看文档哦。

**Comment by ifu25** [comment]
> 注意看文档哦。

天了，一语惊醒装睡人，你一说我想到了 `strict`，第一次接触这个项目时以为这个`参数`是配置是启动时的检测规则呢，原来就是用于配置我说的这个问题的。

😂😂
