### ISSUE TITLE
功能建议,spring.datasource.dynamic.include=db1,db2

### ISSUE THREAD

**Issue by lizhian** [baomidou/dynamic-datasource-spring-boot-starter#357]
spring.datasource.dynamic.include=db1,db2
spring.datasource.dynamic.db1.***
spring.datasource.dynamic.db2.***
spring.datasource.dynamic.db3.***

说明
表明使用哪几个数据源,默认*表示使用所有

场景
公司有十几个数据源
但是很多应用只使用里面的某几个
在外部配置化场景下(nacos)
想做到数据源配置统一统一管理
应用通过配置来决定使用其中某几个个数据源的效果

**Comment by huayanYu** [comment]
1. 不同的应用不同的配置，这本身是你们配置能解决的。
2. 可以使用懒加载， 使用到了再加载。
3. 自己尝试修改源码。
总结：过于个性化的需求且有其他方式解决的，本工具不会做改变。

**Comment by lizhian** [comment]
1
