### ISSUE TITLE
DynamicRoutingDataSource#determinePrimaryDataSource  调用之后应该 finally 清理 threadLocal

### ISSUE THREAD

**Issue by wayne0zhang** [baomidou/dynamic-datasource-spring-boot-starter#358]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.1.9.Release

dynamic-datasource-spring-boot-starter Version(required):3.1.0

druid Version(optional):

# Describe what happened

Expected Result:

main thread invoke method DynamicDataSourceContextHolder.peek() ，so all thread inherit ThreadLocal ，and
then every thread can affect by each other. Actually main Thread get the default datasource by getConnecttion
and will not clear the threadLocalVariable, so when get default datasource, it can manully clear the thread local map.

Actual Result:

main thread invoke method DynamicDataSourceContextHolder.peek() ，so all thread inherit ThreadLocal ，and
then every thread can affect by each other.

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

import activiti

and below method will invoke  dataSource.getConnection();  and main thread has the threadLocal.
```
org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl#initDatabaseType
```

```
private DataSource determinePrimaryDataSource() {
        log.debug("dynamic-datasource switch to the primary datasource");
        try {
            return groupDataSources.containsKey(primary) ? groupDataSources.get(primary).determineDataSource() : dataSourceMap.get(primary);
        } finally {
            DynamicDataSourceContextHolder.clear();
        }
```
    }

**Comment by huayanYu** [comment]
还是说中文吧，有些地方get不到。
1.如果是手动调用肯定要手动清理。
2.注解调用会在DynamicDataSourceAnnotationInterceptor push和poll.
3. 如果改成你的写法，看起来可能会影响A->B->C这种传递。


主要是我还是不理解你怎么用的，出现了什么问题。 是否有完整的示例能复现你的场景。

我没用过activiti， 能顺便给个集成的示例项目最好了。

**Comment by wayne0zhang** [comment]
主要是 主线程如果调用了 DynamicDataSourceContextHolder.peak(),
那么后续所有线程池中的线程都会包含 同一个 ArrayDeque，之后所有入栈和出栈都是在同一个队列中进行操作，所以所有线程 都会互相影响。

**Comment by ls9527** [comment]
至少升级到 3.1.1

**Comment by wayne0zhang** [comment]
其实算是不闭环，AbstractRoutingDataSource 这个类代理了所有的 getConnection 方法，无法避免其他 组件 jar 去调用。

**Comment by wayne0zhang** [comment]
> 至少升级到 3.1.1

避免不了问题

**Comment by ls9527** [comment]
3.1.1 已经从 java.lang.InheritableThreadLocal 改成了  ThreadLocal ，可以解决跨线程的数据源切换错误的问题。

**Comment by wayne0zhang** [comment]
> 3.1.1 已经从 java.lang.InheritableThreadLocal 改成了 ThreadLocal ，可以解决跨线程的数据源切换错误的问题。

嗷嗷，看到了，谢谢。

**Comment by wayne0zhang** [comment]
> 3.1.1 已经从 java.lang.InheritableThreadLocal 改成了 ThreadLocal ，可以解决跨线程的数据源切换错误的问题。

再问一下哈。3.1.1 升级说明有吗，是否可以直接升级？

**Comment by ls9527** [comment]
改动非常小可以直接升级， 如果要升级更高的版本， 要细看升级记录，避免踩坑

**Comment by wayne0zhang** [comment]
好的，升级记录在哪里看

> 改动非常小可以直接升级， 如果要升级更高的版本， 要细看升级记录，避免踩坑
