### ISSUE TITLE
集成shardingsphere后，无法对shardingsphere库进行sql监控

### ISSUE THREAD

**Issue by modefang** [baomidou/dynamic-datasource-spring-boot-starter#359]
# Enviroment

JDK Version(required): 1.8.0_191

SpringBoot Version(required): 2.4.2

dynamic-datasource-spring-boot-starter Version(required):3.3.2

druid Version(optional):1.2.5

# Describe what happened

shardingsphere的数据库无法使用sql监控，dynamic配置的库可以

![企业微信截图_20210324091720](https://user-images.githubusercontent.com/21217474/112240705-c940be80-8c83-11eb-9380-d83ffa1d2d53.png)
![企业微信截图_20210324093450](https://user-images.githubusercontent.com/21217474/112240916-381e1780-8c84-11eb-81bd-346a46c527fb.png)
![企业微信截图_20210324093641](https://user-images.githubusercontent.com/21217474/112241046-79162c00-8c84-11eb-951d-53e69bcd8b4f.png)
![企业微信截图_20210324093030](https://user-images.githubusercontent.com/21217474/112240716-cba31880-8c83-11eb-87b4-3e636c7f4612.png)
![企业微信截图_20210324093247](https://user-images.githubusercontent.com/21217474/112240771-e8d7e700-8c83-11eb-89ed-8cfd2d9ff156.png)

**Comment by modefang** [comment]
dynamic全局的druid配置没加载进来，有解决方法吗？

![企业微信截图_20210324111411](https://user-images.githubusercontent.com/21217474/112249189-4bd07a80-8c92-11eb-96a6-4f0525b22222.png)
![企业微信截图_20210324111439](https://user-images.githubusercontent.com/21217474/112249193-4d01a780-8c92-11eb-947c-2360546c3674.png)

**Comment by huayanYu** [comment]
因为不是数据源创建的DataSouse，只是把sharding数据源拿过来放一起。 所以没法啊

**Comment by modefang** [comment]
> 因为不是数据源创建的DataSouse，只是把sharding数据源拿过来放一起。 所以没法啊


在sharding的配置里加druid就可以了，但是每个数据源都要配置😂


![企业微信截图_20210324114431](https://user-images.githubusercontent.com/21217474/112251503-542ab480-8c96-11eb-959b-47a98bc1b436.png)
