### ISSUE TITLE
怎么判断指定数据源是否存在？

### ISSUE THREAD

**Issue by idlqy** [baomidou/dynamic-datasource-spring-boot-starter#36]
# Enviroment

JDK Version(required): 1.8.0

SpringBoot Version(required): 1.5.9

Starter Version(required):2.4.0

# Describe

因为需要动态的去判断某个数据源是否存在，不存在则创建，存在则调用被注解的方法。

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
DynamicRoutingDataSource 里有获取当前所有的数据源方法,自己注入

**Comment by idlqy** [comment]
好的，收到，非常感谢，这回复实在太迅速了。
