### ISSUE TITLE
如果想增加一个全局拦截header怎么做？

### ISSUE THREAD

**Issue by SilenceRainly** [baomidou/dynamic-datasource-spring-boot-starter#360]
如果想增加一个全局拦截header怎么做？

拦截全局的header 优先级最低,之后在是实现了的DsProcessor等

**Comment by huayanYu** [comment]
不知道你表达的啥意思， 优先级最低就放到DsProcessor最后一个不就好了。

或者仔细描述下你的场景

**Comment by SilenceRainly** [comment]
我要定义一个全局的header选择,并且优先级是 放为最低

**Comment by huayanYu** [comment]
优先级最低就放到DsProcessor最后一个不就好了

**Comment by SilenceRainly** [comment]
现在是解析 class 和 方法上的 DB注释     名称 -> header -> session -> spel ,
我先做个 controller 进来就能确定个数据源 然后 后面自定义在覆盖掉

**Comment by huayanYu** [comment]
哦，那你用拦截器自定义 手动设置吧。

**Comment by SilenceRainly** [comment]
![image](https://user-images.githubusercontent.com/37230683/113385891-9a30f800-93bb-11eb-9712-e31af7cd920b.png)
![image](https://user-images.githubusercontent.com/37230683/113385903-9f8e4280-93bb-11eb-9fb9-de686d373c23.png)
一个线程调用方法,一个方法是controller拦截的,下一个方法就是 spel  切换不过去吗？

**Comment by huayanYu** [comment]
仔细看文档，不支持原生事务，

**Comment by SilenceRainly** [comment]
我找到问题了 是因为第一次没有指定 负载均衡把 master和salve 一样一次的问题  
如果在 一个数据源 原生的事务也不支持吗？
