### ISSUE TITLE
class包名错误

### ISSUE THREAD

**Issue by M1NGc** [baomidou/dynamic-datasource-spring-boot-starter#362]
springboot 2.2.12 
![image](https://user-images.githubusercontent.com/26264126/114642958-5b7a3680-9d07-11eb-86db-af3e956ad2e4.png)
dynamic baomidou3.3.2
![image](https://user-images.githubusercontent.com/26264126/114642985-6af97f80-9d07-11eb-9f43-c9ac72fdb14b.png)

**Comment by nukiyoam** [comment]
这个注解需要依赖
```xml
<dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
```
springboot 健康检查的包

**Comment by huayanYu** [comment]
移除支持
