### ISSUE TITLE
DsProcessor的使用问题

### ISSUE THREAD

**Issue by happier233** [baomidou/dynamic-datasource-spring-boot-starter#365]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.4.5

dynamic-datasource-spring-boot-starter Version(required): 3.3.2

druid Version(optional):

# Describe what happened

DsProcessor是链式结构注册成一个Bean然后被DynamicDataSourceAnnotationInterceptor引用。
但如果一个项目引入的多个jar包中每个项目都有各自的DsProcessor实现，那还得重新屏蔽每个jar包的DsProcessor注册或者由集成的项目统一进行DsProcessor初始化和注册。
有没有可能进行修改，允许注册多个DsProcessor Bean，然后做一个DelegateDsProcessor或者DsProcessorManager进行包装，DsProcessor通过Order进行前后顺序管理。
但的确这样做会引入破坏性修改，得考虑向前兼容问题。
想问下作者这方面有什么考虑吗？

**Comment by huayanYu** [comment]
由集成的项目统一进行DsProcessor初始化和注册 就可以了啊，也不麻烦啊。

过于个性化的需求不会支持哈，或者考虑自己本地改源码使用。
