### ISSUE TITLE
dynamic-datasource-spring-boot-starter冲突spring-cloud-starter-sleuth

### ISSUE THREAD

**Issue by github-stone** [baomidou/dynamic-datasource-spring-boot-starter#368]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): jdk8

SpringBoot Version(required): 2.3.7

dynamic-datasource-spring-boot-starter Version(required): 3.2.1

druid Version(optional):1.2.4

# Describe what happened

微服务分布式调用，定位问题排查日志没有 很麻烦；
打算用 spring-cloud-starter-sleuth 补全日志里的 traceId，
发现好像和 dynamic-datasource-spring-boot-starter ，冲突；添加了sleuth后，boot启动会卡在

** 2021-04-28 10:43:37,074 [main] INFO [com.baomidou.dynamic.datasource.DynamicRoutingDataSource] [DynamicRoutingDataSource.java:237] [trace=,span=] - dynamic-datasource initial loaded [1] datasource,primary datasource named [master]**

这个地方，不报错，也不会继续走；

**Comment by huayanYu** [comment]
没用过也，麻烦参考示例项目，fork一个直接能跑的起来我看看也。

**Comment by huayanYu** [comment]
无回复，关闭。
