### ISSUE TITLE
maven上的jar包DsSpelExpressionProcessor类少了setBeanResolver方法

### ISSUE THREAD

**Issue by JasenL** [baomidou/dynamic-datasource-spring-boot-starter#369]
重构数据源加载类的时候发现maven下载下来的jar包少了方法。
![image](https://user-images.githubusercontent.com/50433952/116531095-64772480-a911-11eb-9903-2e4ae48d8431.png)

![image](https://user-images.githubusercontent.com/50433952/116530897-21b54c80-a911-11eb-9bd2-e5bfacea9551.png)
这个是源码的。
![image](https://user-images.githubusercontent.com/50433952/116530938-30036880-a911-11eb-99b5-9dd52249be78.png)
这个是jar包里的

**Comment by huayanYu** [comment]
master还没发版
