### ISSUE TITLE
能否可以支持自定义规则切换数据源的场景。比如先定义一个规则，在拦截器中根据规则切换数据源

### ISSUE THREAD

**Issue by keji94** [baomidou/dynamic-datasource-spring-boot-starter#37]
# 背景：
项目环境有9个，test1~test5、integration、pre、prod。
我打算做一个后台，支持在前端页面切换环境。目前我是使用拦截器切换的数据源。希望mybatis-plus能够支持这种场景。

**Comment by keji94** [comment]
ok,I found this
[https://apidoc.gitee.com/baomidou/dynamic-datasource-spring-boot-starter/](https://apidoc.gitee.com/baomidou/dynamic-datasource-spring-boot-starter/)

**Comment by huayanYu** [comment]
https://gitee.com/baomidou/dynamic-datasource-spring-boot-starter/wikis/%E5%8A%A8%E6%80%81%E5%8F%82%E6%95%B0%E8%A7%A3%E6%9E%90%E6%95%B0%E6%8D%AE%E6%BA%90(spel)?sort_id=1030624
