### ISSUE TITLE
jdbc.connections.active can not be got from v3.2.0. In v3.1.1, it’s ok.

### ISSUE THREAD

**Issue by fanzhouworld** [baomidou/dynamic-datasource-spring-boot-starter#370]
# Enviroment

JDK Version(required): 11

SpringBoot Version(required): 2.4.0

dynamic-datasource-spring-boot-starter Version(required):>=3.2.0

druid Version(optional):

hikari

mariadb 2.7.0

# Describe what happened

jdbc.connections.active can not be got from v3.2.0. In v3.1.1, it’s normal.

Expected Result:

jdbc.connections.active not null

jdbc.connections.max not null

jdbc.connections.min not null

Actual Result:

jdbc.connections.active null

jdbc.connections.max null

jdbc.connections.min null

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
怎么get的？ 复现步骤？

**Comment by huayanYu** [comment]
没有回复，关闭
