### ISSUE TITLE
3.3.6配置druid问题

### ISSUE THREAD

**Issue by jameswuwu** [baomidou/dynamic-datasource-spring-boot-starter#378]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.5

dynamic-datasource-spring-boot-starter Version(required):3.3.6

druid Version(optional):1.1.21

# Describe what happened

Expected Result: webStatFilter和statViewServlet可以配置使用

Actual Result:
不能使用

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

![image](https://user-images.githubusercontent.com/52489194/120578150-f2d24f00-c457-11eb-8b59-55feb2a8dce8.png)

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
filter是druid 原来怎么配就怎么配，不是配里面的。
