### ISSUE TITLE
DSTransactional类不生效

### ISSUE THREAD

**Issue by younker99** [baomidou/dynamic-datasource-spring-boot-starter#387]
# Enviroment

JDK Version(required): 8

SpringBoot Version(required): 2.4.3

dynamic-datasource-spring-boot-starter Version(required):3.4.1

druid Version(optional):na

# Describe what happened
@DSTransactional注解可以加在类与方法上，但是从切点的代码看只在加在方法上才生效。是否将该注解调整为只适用于方法，还是调整现有切点Expression使其在类与方法上都可以生效？

Expected Result:

@DSTransactional加在类上与方法上都生效

Actual Result:
@DSTransactional只在方法上生效

```
DynamicDataSourceAutoConfiguration:112
pointcut.setExpression("@annotation(com.baomidou.dynamic.datasource.annotation.DSTransactional)");
```

**Comment by huayanYu** [comment]
merge
