### ISSUE TITLE
停止程序的时候会有dynamic-datasource closed datasource named [{}] failed警告

### ISSUE THREAD

**Issue by silence934** [baomidou/dynamic-datasource-spring-boot-starter#395]
我在整合动态数据源和Sharding的时候遇到了一个问题
在关闭应用程序的时候会有一个异常：
![image](https://user-images.githubusercontent.com/49453669/134614014-6eaffe0b-e04c-4e3d-91b1-16e570abaa6f.png)
跟踪堆栈信息发现问题出在这里：
![C7C681BE9CD9CB535485AA0F93FBA5EB](https://user-images.githubusercontent.com/49453669/134614024-a3d44a80-48c1-40a4-8da5-3d7bdac7ade3.jpg)
停止程序的时候会通过反射去调用每个DataSource的close方法
但是这里使用的是getDeclaredMethod方法  它无法获取父类的方法
当DataSource的close方法在父类上是就会报以上的错误（ShardingDataSource的close方法刚好是在父类上）

**Comment by huayanYu** [comment]
准备发版
