### ISSUE TITLE
使用Sharding Sphere可以支持多数据源下的事务回滚

### ISSUE THREAD

**Issue by liunancun** [baomidou/dynamic-datasource-spring-boot-starter#41]
多个库的事物如何处理？
不能 不能 不能，一个业务操作涉及多个库不要加事物。

使用Sharding Sphere可以支持多数据源下的事务回滚，可否研究下

**Comment by huayanYu** [comment]
研究不出来,你研究下呗.

**Comment by liunancun** [comment]
@huayanYu Sharding Sphere是重写了Connection中的事务相关方法，获取实际的Connection列表，分别调用提交方法的
