### ISSUE TITLE
Spel support not friendly enough

### ISSUE THREAD

**Issue by xiaoyao9184** [baomidou/dynamic-datasource-spring-boot-starter#413]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.3.4 

dynamic-datasource-spring-boot-starter Version(required): 3.5.0

druid Version(optional): not use

# Describe what happened

[DsSpelExpressionProcessor](https://github.com/baomidou/dynamic-datasource-spring-boot-starter/blob/master/src/main/java/com/baomidou/dynamic/datasource/processor/DsSpelExpressionProcessor.java) not support static method Spel if DS string is not start with '#'

see those, method call use 'T()' 
https://stackoverflow.com/questions/26029760/spel-getmethod-dont-work
https://stackoverflow.com/questions/37135971/spel-error-method-cannot-be-found-on-type

because DynamicDataSourceAnnotationInterceptor only use `startsWith(DYNAMIC_PREFIX)` for enbale Spel 

https://github.com/baomidou/dynamic-datasource-spring-boot-starter/blob/9a55abf799ec8554b0362640a2426f3c7c88f92a/src/main/java/com/baomidou/dynamic/datasource/aop/DynamicDataSourceAnnotationInterceptor.java#L35

https://github.com/baomidou/dynamic-datasource-spring-boot-starter/blob/9a55abf799ec8554b0362640a2426f3c7c88f92a/src/main/java/com/baomidou/dynamic/datasource/aop/DynamicDataSourceAnnotationInterceptor.java#L56-L59

so if i want use Spel method call on `DS` annotation, i must code like this:

```java
@DS("#path.substring(0,0) + T(com.*.*.PathUtil).parseDatabaseFromPath(#path)")
@Override
public List<Node> query(String path) {
```

**Comment by huayanYu** [comment]
do u have any idea?  you can pr

**Comment by huayanYu** [comment]
no replay , closed
