### ISSUE TITLE
整合sharding的时候，停止程序报错，和#395差不多

### ISSUE THREAD

**Issue by hachikozjq** [baomidou/dynamic-datasource-spring-boot-starter#415]
![image](https://user-images.githubusercontent.com/36358868/153134212-84b05706-b722-46fa-9632-3e652c2dcf06.png)
如：https://github.com/baomidou/dynamic-datasource-spring-boot-starter/issues/395
但是我这边是报了npe。

datasource的配置：
`@Configuration
public class DataSourceAutoConfiguration {
    /**
     * 分表数据源名称
     */
    public static final String SHARDING_DATA_SOURCE_NAME = "sharding";
    @Resource
    private DynamicDataSourceProperties properties;
    @Lazy
    @Resource
    private ShardingDataSource shardingDataSource;

    @Bean
    public DynamicDataSourceProvider dynamicDataSourceProvider() {
        return new AbstractDataSourceProvider() {
            @Override
            public Map<String, DataSource> loadDataSources() {
                Map<String, DataSource> dataSourceMap = new HashMap<>();
                dataSourceMap.put(SHARDING_DATA_SOURCE_NAME, shardingDataSource);
                Map<String, DataSource> shardingInnerDataSources = shardingDataSource.getDataSourceMap();
                dataSourceMap.putAll(shardingInnerDataSources);
                return dataSourceMap;
            }
        };
    }

    @Primary
    @Bean
    public DataSource dataSource() {
        DynamicRoutingDataSource dataSource = new DynamicRoutingDataSource();
        dataSource.setPrimary(properties.getPrimary());
        dataSource.setStrict(properties.getStrict());
        dataSource.setStrategy(properties.getStrategy());
        dataSource.setP6spy(properties.getP6spy());
        dataSource.setSeata(properties.getSeata());
        return dataSource;
    }
}`

yml的配置：
`spring:
  datasource:
    dynamic:
      strict: true
      hikari:
        min-idle: 5
        max-pool-size: 50
        is-auto-commit: true
        idle-timeout: 30000
        max-lifetime: 300000
        connection-timeout: 30000
        connection-test-query: select 1
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          pool-name: xxx-pool
          username: root
          password:
          url: jdbc:mysql://localhost:3306/xxx?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&connectTimeout=5000&socketTimeout=60000
        stock:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          pool-name: xxx-pool
          username: root
          password:
          url: jdbc:mysql://localhost:3306/xxx?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&connectTimeout=5000&socketTimeout=60000
  shardingsphere:
    datasource:
      names: ds-0
      ds-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/sharding_0?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&connectTimeout=5000&socketTimeout=60000
        username: root
        password:
        min-idle: 5
        max-pool-size: 50
        is-auto-commit: true
        idle-timeout: 30000
        pool-name: ds-0-pool
        max-lifetime: 300000
        connection-timeout: 30000
        connection-test-query: select 1
    sharding:
      tables:
        tb_user:
          actual-data-nodes: ds-0.tb_user_$->{0..1}
          table-strategy:
            standard:
              sharding-column: user_id
              precise-algorithm-class-name: xxx.TbShardingAlgorithmForLong
    algorithm:
      config:
        - tableName: tb_user
          shardingNumber: 2`

# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
2.3.2
dynamic-datasource-spring-boot-starter Version(required):
3.5.0
sharding Version(optional):
4.1.1

# Describe what happened
想知道 https://github.com/baomidou/dynamic-datasource-spring-boot-starter/issues/395 说是等发版，是已经解决了还是latest版本目前还没解决。

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by linghengqian** [comment]
I think the problem with #395 is `@Lazy`. I don't have this problem with ShardingSphere 4.1.1 and 5.0.0 on my side.

**Comment by Hachiko-JQ** [comment]
> I think the problem is that both you and another issue have added `@Lazy` to the data source of ShardingSphere, and lazy loading directly causes the exception to be thrown. I don't have this in ShardingSphere JDBC version 4.1.1 and version 5.0.0 problem.

boot版本问题，用Example复现，把boot换成2.3.x也会出现这个问题

**Comment by linghengqian** [comment]
> > I think the problem is that both you and another issue have added `@Lazy` to the data source of ShardingSphere, and lazy loading directly causes the exception to be thrown. I don't have this in ShardingSphere JDBC version 4.1.1 and version 5.0.0 problem.
> 
> boot版本问题，用Example复现，把boot换成2.3.x也会出现这个问题

I'm not sure what happened with the old version, but spring-boot `2.5.1`-`3.0.0-M1` works fine.

**Comment by linghengqian** [comment]
I can confirm that there are commonsense issues with the Current Dynamic Datasource and ShardingSphere JDBC 4.1.1 example, perhaps for compatibility with older versions, but some operations are not necessary.

**Comment by linghengqian** [comment]
I need to point out that Spring-Boot 2.3.x has ended its community support (2021-05-20), if you are limited to 2.3.x help, you should seek commercial support before 2022-08-20. Refer to https://spring.io/projects/spring-boot#support .

**Comment by wxyShine** [comment]
解决了吗？我的问题和这个一样。

**Comment by wxyShine** [comment]
我把shardingDataSource  这个@Lazy去掉正常了

**Comment by linghengqian** [comment]
> 解决了吗？我的问题和这个一样。

This problem does not exist in SpringBoot `2.5.1`-`3.0.0-M2`, and there is no way to feed back to the Spring community for problems with specific releases that have been discontinued from the community.

**Comment by wxyShine** [comment]
> 

Spring Boot Version: 2.5.7 
@Lazy去掉才正常

**Comment by linghengqian** [comment]
> > 
> 
> Spring Boot Version: 2.5.7 
> @Lazy去掉才正常

You never need `@Lazy`. In fact, I don't understand why there is a specific version that requires this annotation, which means that users need to change the registration process of ShardingSphere.

**Comment by linghengqian** [comment]
Resolved at https://github.com/apache/shardingsphere/pull/17602 . Example Updated comments, refer to https://github.com/dynamic-datasource/dynamic-datasource-samples/commit/90109761751450a0fceaeb177c5c07e05c3b33f0 . I think this Issue can be closed.
