### ISSUE TITLE
使用 @Autowire注入 Spring， DynamicRoutingDataSource 报错NoSuchBeanDefinitionException

### ISSUE THREAD

**Issue by justime** [baomidou/dynamic-datasource-spring-boot-starter#416]
环境：

JDK Version(required): 1.8

SpringBoot Version(required): 2.3.2

dynamic-datasource-spring-boot-starter Version(required): 2.5.8 和 3.3.2 都是试了

druid Version(optional): no use

代码如下：

@Configuration
@RequiredArgsConstructor
public class OLJobConfigure {

    private final DynamicRoutingDataSource dynamicRoutingDataSource;

    @Bean
    public ThreadPoolTaskExecutor scheduleJobExecutorService() {
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(5);
        executor.setMaxPoolSize(10);
        executor.setQueueCapacity(20);
        executor.setKeepAliveSeconds(30);
        executor.setThreadNamePrefix("OLive-Job-Thread");
        executor.setWaitForTasksToCompleteOnShutdown(true);
        executor.setAwaitTerminationSeconds(60);
        executor.setRejectedExecutionHandler(new ThreadPoolExecutor.CallerRunsPolicy());
        executor.initialize();
        return executor;
    }

    @Bean
    public SchedulerFactoryBean schedulerFactoryBean() {
        SchedulerFactoryBean factory = new SchedulerFactoryBean();
        // 设置数据源
        DataSource job = dynamicRoutingDataSource.getDataSource("job");
        factory.setDataSource(job);
        Properties prop = new Properties();
    }
}

错误日志：
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in run.olive.server.job.configure.OLJobConfigure required a bean of type 'com.baomidou.dynamic.datasource.DynamicRoutingDataSource' that could not be found.

Action:

Consider defining a bean of type 'com.baomidou.dynamic.datasource.DynamicRoutingDataSource' in your configuration.

说明： 1、pom 中有引入         
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
            <version>${dynamic-datasource.version}</version>
        </dependency>
2、把 SpringBoot版本换成 2.2.5 就行了。

3、看答复有说改成注入DataSource， 改成  DataSource，怎么获取指定数据源呢？

**Comment by huayanYu** [comment]
注入DataSource ，使用的时候强转成DynamicRoutingDataSource

**Comment by justime** [comment]
虽然很暴力，但是问题解决了。    

想继续了解一下，为什么 SpringBoot 2.3.X 注入不了 DynamicRoutingDataSource  呢
