### ISSUE TITLE
mybatis plus最新版本必须要使用这个包吗？

### ISSUE THREAD

**Issue by 87048824** [baomidou/dynamic-datasource-spring-boot-starter#42]
public class TonytestService extends ServiceImpl<TTonytestMapper, TTonytest> {
    @Autowired
    private TTonytestMapper tTonytestMapper;
    @Autowired
    private WeixinBasfUserInfoMapper weixinBasfUserInfoMapper;
    @Autowired
    private  UserService userService;

    private static final Logger logger = LoggerFactory.getLogger(TonytestService.class);

    /***
     * 更新By Id
     * @param inDTO
     * @return
     * @throws Exception
     */
    @DS("slave")
    public OutDTO updateById(InDTO inDTO) throws Exception{
        //Map<String,Object> map = new HashMap<String,Object>();
        OutDTO outDTO = new OutDTO();

        //String username = (String)inDTO.get("username");
        TTonytest test = new TTonytest();
        test.setId(5);
        test.setPageUrl("www.baidu.com");
        test.setCreateDate(LocalDateTime.now());
        //baseMapper.updateById(test);
        tTonytestMapper.updateById(test);

        WeixinBasfUserInfo user = weixinBasfUserInfoMapper.selectById(1);

我想在一个service函数中同时使用2个数据源的逻辑，无法实现 。由于使用了@DS切换了数据源，报找不到表。
如果有方法，将数据源固定配置在Mapper类上就最好。我在service中操作mapper自动根据配置好的多数据源执行各自的逻辑。

**Comment by huayanYu** [comment]
可以把@ds 放到mapper方法上

**Comment by 87048824** [comment]
weixinBasfUserInfoMapper这个mapper类的selectById方法是默认的，mapper中没有。如果在mapper类中加入方法是可以的，我试过了，但这样方法还是要重写，不是增加了开发工作量吗？

**Comment by huayanYu** [comment]
@87048824 加在类上为什么要重写?

**Comment by 87048824** [comment]
@DS("slave")
public interface TTonytestMapper extends BaseMapper<TTonytest> {

}

在mapper上加了以后，我在service中调用tTonytestMapper.updateById(test);之后，报这个错误是什么原因？

java.lang.IllegalArgumentException: Can not set final java.lang.Class field org.apache.ibatis.binding.MapperProxy.mapperInterface to com.baomidou.mybatisplus.core.override.MybatisMapperProxy
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38)

**Comment by huayanYu** [comment]
@87048824  升级最新版

**Comment by RandyZ** [comment]
这个问题解决了？我使用3.2.0依然不行，问题依然存在

**Comment by RandyZ** [comment]
> @87048824 升级最新版

这个问题解决了？我使用3.2.0依然不行，问题依然存在
