### ISSUE TITLE
引入动态数据源后无限连接问题

### ISSUE THREAD

**Issue by emonaiba8857** [baomidou/dynamic-datasource-spring-boot-starter#420]
# Enviroment

JDK Version(required):  openjdk 11

SpringBoot Version(required):  2.3.0.RELEASE

dynamic-datasource-spring-boot-starter Version(required):  3.5.1

druid Version(optional): 1.1.10

# Describe what happened
引入动态数据源依赖后配置druid的 break-after-acquire-failure、connection-error-retry-attempts属性失效导致出现无限连接数据库，log日志无限增大问题

Expected Result:
希望能够根据配置在连接数据源错误时进行有限次的连接

Actual Result:
配置break-after-acquire-failure、connection-error-retry-attempts属性后还是会无限连接 并打印log

现有版本有解决该问题的方法吗？

**Comment by huayanYu** [comment]
你再研究研究druid文档， 是能控制的，或者断点看看。 我不用druid，不太清楚。

这个是连接池底层的异常，我无法控制。 可以换一个连接池。
