### ISSUE TITLE
spring.datasource.dynamic.primary设置不生效

### ISSUE THREAD

**Issue by kender1314** [baomidou/dynamic-datasource-spring-boot-starter#422]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): JDK 17

SpringBoot Version(required):  2.3.3.RELEASE

dynamic-datasource-spring-boot-starter Version(required): 3.5.1

druid Version(optional): 1.2.8

# Describe what happened
设置spring.datasource.dynamic.primary = orderdb

Expected Result:
如果我没有使用注解@DS的情况下，默认应该访问orderdb数据库

Actual Result:
找不到数据库orderdb。
应该是类DynamicDataSourceAutoConfiguration中以下方法没有执行
    @Bean
    @ConditionalOnMissingBean
    public DataSource dataSource() {
        DynamicRoutingDataSource dataSource = new DynamicRoutingDataSource();
        dataSource.setPrimary(properties.getPrimary());
        dataSource.setStrict(properties.getStrict());
        dataSource.setStrategy(properties.getStrategy());
        dataSource.setP6spy(properties.getP6spy());
        dataSource.setSeata(properties.getSeata());
        return dataSource;
    }
类DynamicRoutingDataSource中primary取用了默认值master，而不是我设置的值orderdb，就没法找我设置的默认数据库

**Comment by huayanYu** [comment]
@ConditionalOnMissingBean 
你没有执行，说明你有自定义数据源。 这里就不会执行

**Comment by kender1314** [comment]
感谢解答，找到问题了，我自己写了DynamicRoutingDataSourceConfig类，继承了DynamicRoutingDataSource类之后，又把它注入到了spring容器中出现了这个问题
