### ISSUE TITLE
使用注解@DSTransactional批量提交事务，提交异常的事务在上层业务无法感知

### ISSUE THREAD

**Issue by Nutao** [baomidou/dynamic-datasource-spring-boot-starter#423]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required):  1.8

SpringBoot Version(required): 2.1.18.RELEASE

dynamic-datasource-spring-boot-starter Version(required): 3.4.0

druid Version(optional):

# Describe what happened
使用注解@DSTransactional批量提交事务，提交异常的事务在上层业务无法感知

Expected Result:
某个数据源事务提交出现异常后，能抛出异常

Actual Result:
某个数据源事务提交出现异常后，异常未抛出，仅打印了error日志

<img width="732" alt="image" src="https://user-images.githubusercontent.com/14237345/164151197-fe44f3bf-28cc-4106-9f65-84c35fcf221e.png">

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
欢迎PR参与

**Comment by Nutao** [comment]
> 欢迎PR参与

可以直接从3.4.x的tag拉分支改吗？

**Comment by gxmgxm** [comment]
您好 ，这里是高相猛，很高兴收到您的邮件 。

**Comment by huayanYu** [comment]
> > 欢迎PR参与
> 
> 可以直接从3.4.x的tag拉分支改吗？

tag分支？ 没这么玩过。

**Comment by Nutao** [comment]
> > > 欢迎PR参与
> > 
> > 
> > 可以直接从3.4.x的tag拉分支改吗？
> 
> tag分支？ 没这么玩过。

比如从tag v3.4.1拉个新分支：
```
git checkout -b feat/xxx  v3.4.1
```
