### ISSUE TITLE
DS 注解放到调用的方法上不能生效

### ISSUE THREAD

**Issue by ZYuanCheng** [baomidou/dynamic-datasource-spring-boot-starter#424]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required):  1.8

SpringBoot Version(required):  2.2.6

dynamic-datasource-spring-boot-starter Version(required):

druid Version(optional):1.1.22

# Describe what happened
1. Controller 是这样的
![QQ图片20220425173501](https://user-images.githubusercontent.com/30103415/165062660-ef2dd255-9da4-4233-a007-baa78f62765f.png)
2.ServiceImp 如果放到这里可以切换数据库
![QQ图片20220425173654](https://user-images.githubusercontent.com/30103415/165062996-1193c09b-7fe8-4bee-992a-85a9bd936d39.png)
3.放到另外一个方法就不能切换数据库
![QQ图片20220425173825](https://user-images.githubusercontent.com/30103415/165063216-7e1d80cc-7735-4366-ad2f-4f946add08fd.png)
请问一下这是什么原因？

**Comment by Rushing0711** [comment]
你这种调用方式，并不会触发AOP拦截。
解决：
1-把getArticles放到其他service中，通过  service.getArticles 调用
2-查一下@EnableAspectJAutoProxy(exposeProxy = true)这种方式
