### ISSUE TITLE
导入包，出现is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

### ISSUE THREAD

**Issue by xiaoyu-666** [baomidou/dynamic-datasource-spring-boot-starter#425]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
![image](https://user-images.githubusercontent.com/27267958/165264937-8ade12b3-05b7-4fef-9124-b73947e1c411.png)
dynamic-datasource-spring-boot-starter Version(required):
![image](https://user-images.githubusercontent.com/27267958/165265027-31d3a533-8a81-4b20-90a5-dbaaff16968e.png)
druid Version(optional):
![image](https://user-images.githubusercontent.com/27267958/165265090-e7a8b758-7044-4c1b-a029-e25073a5e3b3.png)

# Describe what happened
![image](https://user-images.githubusercontent.com/27267958/165265200-b975c923-b47c-4a22-a3a7-17d411b3e3b9.png)
我不过就导入了包，运行时就显示这个内容，这个问题对多数据源切换有影响吗？

**Comment by huayanYu** [comment]
不
