### ISSUE TITLE
使用Dynamic-datasource-spring-boot-starter整合SpringDataJpa发生异常

### ISSUE THREAD

**Issue by shuangyue521** [baomidou/dynamic-datasource-spring-boot-starter#428]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required):  1.8

SpringBoot Version(required):  2.3.7.RELEASE

dynamic-datasource-spring-boot-starter Version(required):3.5.1

druid Version(optional):

# Describe what happened
使用Dynamic-datasource-spring-boot-starter整合mybatis或者mybatis-plus时，使用DSTransaction一切正常,会在mapper执行前进入切面根据DS切换对应的数据源,但是整合SpringDataJpa后,会先执行对应的repository后，再进入到切面，有没有什么好的解决方案

Expected Result:
整合SpringDatatJpa也可以使用

Actual Result:
sql无法执行，表或视图不存在

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
调整切面顺序试试，不建议用jpa,没整合过

**Comment by shuangyue521** [comment]
> 

昨天试了一整天，无论如何都不行，看来可能是我的技术比较菜😢

**Comment by huayanYu** [comment]
@shuangyue521 请正确理解多数据源，不是我支持不支持他。 我只是实现spring官方接口。
另外是有很多人集成了jpa的， 但jpa不同的人用法差异极其大。 可能不同用法会有不同的影响。
