### ISSUE TITLE
文档没办法支付了!

### ISSUE THREAD

**Issue by mengxzh** [baomidou/dynamic-datasource-spring-boot-starter#429]
Please fill it out carefully, or it will be closed.
直接把拉回来的json返回来了, 没返回扫码的图片

# Enviroment

JDK Version(required): 

SpringBoot Version(required): 

dynamic-datasource-spring-boot-starter Version(required):

druid Version(optional):

# Describe what happened

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
已自己测试，联系平台官方都没有发现此问题。  请检查网络，是否开启代理会有影响之类
