### ISSUE TITLE
DynamicDataSourceProvider的自动配置能否加上@ConditionalOnMissingBean

### ISSUE THREAD

**Issue by VonXXGhost** [baomidou/dynamic-datasource-spring-boot-starter#435]
# Enviroment

JDK Version(required):  jdk11

SpringBoot Version(required): 2.7.0

dynamic-datasource-spring-boot-starter Version(required):3.5.1

# Describe what happened

当前版本的 `DynamicDataSourceAutoConfiguration` 中，`ymlDynamicDataSourceProvider()` 方法会默认提供一个 `DynamicDataSourceProvider`，因为没有限制条件，只要这个 AutoConfiguration 运行了都会注册这个 bean。

现在我想在保留本类其他方法都正常运行的基础上，自己另外配置注入 `DynamicRoutingDataSource` 的 bean，同时自定义自己的 `DynamicDataSourceProvider`，然后我发现这个自带的 `YmlDynamicDataSourceProvider` 很难处理掉，总是会被配置注入到 `DynamicRoutingDataSource` 的 `providers` 当中。自己暂时没找到比较优雅的方法处理这个问题。

有一点不是很理解为什么 `ymlDynamicDataSourceProvider()` 不加上 condition，明明其他都有加上，如果没有其他特殊的考量是否能加上 `@ConditionalOnMissingBean` ？

**Comment by huayanYu** [comment]
你为什么非要搞掉它

**Comment by VonXXGhost** [comment]
> 你为什么非要搞掉它

我想在特定的测试条件下，不使用配置文件指定的数据库连接信息，而是使用自己另外代码配置出来的 DataSource 替换掉同名的数据源。如果能控制 `DynamicRoutingDataSource` 的 `providers` 的顺序的话也可以不搞掉它，我自己定义的 `DynamicDataSourceProvider` 试了几遍都排在前面覆盖不了 yml 的配置。所以希望两种方式至少能提供一种，个人感觉 yml 的无约束加载似乎没什么道理

**Comment by huayanYu** [comment]
不可能用@ConditionalOnMissingBean 有很多人是要多渠道加载的。
你可以想象其他办法提PR。
yml至少是9成用户用户选择，必须默认支持。

**Comment by VonXXGhost** [comment]
🤔那我还是往优先级方面想想办法吧
