### ISSUE TITLE
not eligible for auto-proxying

### ISSUE THREAD

**Issue by jackli0909** [baomidou/dynamic-datasource-spring-boot-starter#439]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
2.3.12 relase
dynamic-datasource-spring-boot-starter Version(required):
3.4.1
druid Version(optional):

# Describe what happened
[Bean 'com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration' of type [com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration$$EnhancerBySpringCGLIB$$c6c3f914] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)]

**Comment by huayanYu** [comment]
https://blog.csdn.net/feiying0canglang/article/details/119704109
