### ISSUE TITLE
整合 ShardingSphere 5.1.1 自定义分片算法不能生效

### ISSUE THREAD

**Issue by vwh** [baomidou/dynamic-datasource-spring-boot-starter#440]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.4.5/2.6.7

dynamic-datasource-spring-boot-starter Version(required):3.5.1

druid Version(optional):1.2.8

# Describe what happened
在示例项目shardingSphere-jdbc的基础上，修改sharding-algorithms为CLASS_BASED的自定义方法，但是在插入和查询的时候，并不会进到自定义的方法中。正常的话，应该会打印“===== start doSharding(String) =====“日志，但是实际并不会。

# Steps to reproduce
可复现的项目上传到 https://github.com/vwh/dynamic-datasouce-samples

**Comment by huayanYu** [comment]
请发给sharding，多数据源只负责把它加进来，不会动sharding的东西。
