### ISSUE TITLE
批量保存时切换数据源不成功

### ISSUE THREAD

**Issue by sinboun** [baomidou/dynamic-datasource-spring-boot-starter#45]
# Enviroment

JDK Version(required): jdk 1.8 

SpringBoot Version(required): 2.1.3

Starter Version(required):

# Describe
sava可以保存成功，但是批量保存就不行，提示表不存在 切换数据源不成功
![1555319908870](https://user-images.githubusercontent.com/11026565/56121357-86a7df00-5fa2-11e9-973a-68a4fe655398.jpg)

**Comment by kyle250** [comment]
遇到同样的问题，MyBatisPlus里面saveOrUpdateBatch识别不了数据源。

**Comment by huayanYu** [comment]
mp底层添加了事物, 可以自己copy出来不加事物
