### ISSUE TITLE
Druid的1.2.12之后的版本新增了socket-timeout和connect-timeout配置

### ISSUE THREAD

**Issue by reixuemin** [baomidou/dynamic-datasource-spring-boot-starter#455]
如题，这个需要插件修改吗？还是自动就支持的？

**Comment by huayanYu** [comment]
需要你来提交PR

**Comment by glf14811** [comment]
Druid1.2.12之后的版本新增了socket-timeout和connect-timeout配置， 缺省值为10秒， 详情见com.alibaba.druid.pool.DruidAbstractDataSource。 若有超过10秒以上的复杂SQL查询， 会抛出异常： ### Cause: java.sql.SQLRecoverableException: IO 错误: Socket read timed out
; IO 错误: Socket read timed out; nested exception is java.sql.SQLRecoverableException: IO 错误: Socket read timed out
。 com.baomidou.dynamic.datasource.spring.boot.autoconfigure.druid.DruidConfig 中需增加对Druid1.2.12新增属性的支持？

**Comment by huayanYu** [comment]
3.6.0
