### ISSUE TITLE
自定义druidfilter没有生效 默认的是有的

### ISSUE THREAD

**Issue by zhangyanglei** [baomidou/dynamic-datasource-spring-boot-starter#459]
# Enviroment

JDK Version(required): 
1.8.0_241
SpringBoot Version(required): 
2.1.7.RELEASE
dynamic-datasource-spring-boot-starter Version(required):
3.1.0
druid Version(optional):
1.1.21

# Describe what happened
自定义了druid过滤器 没有自动生效

未使用动态数据源的时候 只要声明了filter自动回复注册到filter链里
使用之后 没有自动加进去

我看DruidDynamicDataSourceConfiguration是直接复制的DruidDataSourceAutoConfigure 但是里面还有个
![image](https://user-images.githubusercontent.com/30100164/200260014-cfc231e4-0d6a-46cf-b201-2b4f4b178797.png)
![image](https://user-images.githubusercontent.com/30100164/200260042-6817e9e9-c1a7-4301-add8-8250a2d1269d.png)
这个里面有注册逻辑

**Comment by zhangyanglei** [comment]
补充下 调了下代码 加了这个配置 好使 
![image](https://user-images.githubusercontent.com/30100164/200271025-bb8b903d-b20a-4987-abf4-2556c584fc95.png)
filter为你自定义filter的bean name
但我觉得这既然跟DruidDataSourceAutoConfigure代码类似 是不是也直接能自动加进去好点

**Comment by huayanYu** [comment]
欢迎PR
