### ISSUE TITLE
小问题: AbstractJdbcDataSourceProvider#loadDataSources 返回 null 导致应用启动以NPE异常结束

### ISSUE THREAD

**Issue by syrm-ll** [baomidou/dynamic-datasource-spring-boot-starter#460]
如果 AbstractJdbcDataSourceProvider 认为连接失败应该终止应用启动, 这里应该抛出异常或包装的异常, 而非返回 null
否则 应返回空 Map, 避免 `DynamicRoutingDataSource#afterPropertiesSet` 中 `dataSources.putAll(provider.loadDataSources());` 抛出 NPE 掩盖真正的问题

问题点:
<https://github.com/baomidou/dynamic-datasource-spring-boot-starter/blob/master/src/main/java/com/baomidou/dynamic/datasource/provider/AbstractJdbcDataSourceProvider.java#L90>

案发现场:
<https://github.com/baomidou/dynamic-datasource-spring-boot-starter/blob/master/src/main/java/com/baomidou/dynamic/datasource/DynamicRoutingDataSource.java#L225>

**Comment by syrm-ll** [comment]
目前可以通过覆盖 `loadDataSources` 实现来解决

**Comment by huayanYu** [comment]
仅供参考，自己覆盖
