### ISSUE TITLE
Druid1.2.12之后的版本新增了socket-timeout和connect-timeout配置， 缺省值为10秒， 详情见com.alibaba.druid.pool.DruidAbstractDataSource。 若有超过10秒以上的复杂SQL查询， 会抛出异常： ### Cause: java.sql.SQLRecoverableException: IO 错误: Socket read timed out

### ISSUE THREAD

**Issue by glf14811** [baomidou/dynamic-datasource-spring-boot-starter#461]
Druid1.2.12之后的版本新增了socket-timeout和connect-timeout配置， 缺省值为10秒， 详情见com.alibaba.druid.pool.DruidAbstractDataSource。 若有超过10秒以上的复杂SQL查询， 会抛出异常： ### Cause: java.sql.SQLRecoverableException: IO 错误: Socket read timed out
; IO 错误: Socket read timed out; nested exception is java.sql.SQLRecoverableException: IO 错误: Socket read timed out
。 com.baomidou.dynamic.datasource.spring.boot.autoconfigure.druid.DruidConfig 中需增加对Druid1.2.12新增属性的支持？

_Originally posted by @glf14811 in https://github.com/baomidou/dynamic-datasource-spring-boot-starter/issues/455#issuecomment-1307341417_

**Comment by huayanYu** [comment]
3.6.0
