### ISSUE TITLE
多数据源在springboot3中无法启动(不使用多数据源能正常启动)---非native运行

### ISSUE THREAD

**Issue by zxiaozhou** [baomidou/dynamic-datasource-spring-boot-starter#463]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 17

SpringBoot Version(required): 3.0.0

dynamic-datasource-spring-boot-starter Version(required):3.5.2

druid Version(optional):使用的是hikari

# Describe what happened

Expected Result:

能过注册数据库驱动

Actual Result:
```
Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (the profiles dev are currently active).

```

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

**Comment by linghengqian** [comment]
- Duplicate with https://github.com/baomidou/dynamic-datasource-spring-boot-starter/pull/454, this issue should be marked as invalid and closed.

**Comment by huayanYu** [comment]
3.6.0
