### ISSUE TITLE
貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 

### ISSUE THREAD

**Issue by ljga** [baomidou/dynamic-datasource-spring-boot-starter#464]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。
貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 貌似不支持最新的springboot 3.0.0 
# Enviroment

JDK Version(required): 

SpringBoot Version(required): 

dynamic-datasource-spring-boot-starter Version(required):

druid Version(optional):

# Describe what happened

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by qmdx** [comment]
适配中

**Comment by linghengqian** [comment]
- Duplicate with https://github.com/baomidou/dynamic-datasource-spring-boot-starter/pull/454, this issue should be marked as invalid and closed.

**Comment by huayanYu** [comment]
3.6.0
