### ISSUE TITLE
对Druid新版本的支持

### ISSUE THREAD

**Issue by reixuemin** [baomidou/dynamic-datasource-spring-boot-starter#466]
我看已经有对Druid新版的支持的提交，是还没通过，有问题吗？怎么还没发版本？

**Comment by huayanYu** [comment]
在调试springboot3的适配,调通了一起发

**Comment by GuryYu** [comment]
Druid 新增加的socketTimeout配置，默认配置为10s会导致任何超过10s的查询被中断，这对大数据量的报表统计等场景影响很大。在当前Druid版本和使用了多数据源情况下，没有找到能够临时配置该参数的方法。

期待近期能发布新版，或者单独发布一个小版本适配该配置。

**Comment by huayanYu** [comment]
3.6.0
