### ISSUE TITLE
关于文档不明白各个组件版本以来的支持

### ISSUE THREAD

**Issue by Lvbuqing** [baomidou/dynamic-datasource-spring-boot-starter#467]
需要在readme里面加上关于版本说明的文档，
需要描述dynamic-datasource每个dynamic-datasource的Releases版本对应支持的组件版本。
例如该格式
![image](https://user-images.githubusercontent.com/32841009/206080184-c27e8fbc-0ace-4082-9f96-d4663208c70d.png)

**Comment by huayanYu** [comment]
都支持.
