### ISSUE TITLE
多数据源切换时偶尔报错

### ISSUE THREAD

**Issue by burningg** [baomidou/dynamic-datasource-spring-boot-starter#469]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 
1.8

SpringBoot Version(required): 
2.3.2.RELEASE
dynamic-datasource-spring-boot-starter Version(required):
3.5.2
druid Version(optional):
使用的hakari

# Describe what happened
切换数据源的时候偶尔报错，使用的dm数据库

Expected Result:
![image](https://user-images.githubusercontent.com/38727277/206615677-bca70617-8974-468c-9b11-e99a9788987b.png)

**Comment by huayanYu** [comment]
自己排查
