### ISSUE TITLE
Whether the load balancer switches the data source once per connection or once per transaction

### ISSUE THREAD

**Issue by 525bigword** [baomidou/dynamic-datasource-spring-boot-starter#472]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 
17
SpringBoot Version(required): 
2.6.9
dynamic-datasource-spring-boot-starter Version(required):
3.5.0
druid Version(optional):
1.1.12

Whether the load balancer switches the data source once per connection or once per transaction
请问负载均衡是每次连接切换一次数据源还是每个事务切换一次

**Comment by huayanYu** [comment]
just try
