### ISSUE TITLE
读写分离设置

### ISSUE THREAD

**Issue by kevinliukaiwen** [baomidou/dynamic-datasource-spring-boot-starter#478]
项目里配置了MasterSlaveAutoRoutingPlugin，默认就是读写分离，读走从库，写走主库，但是我想某条读sql走主，设置了service的方法@DS("master")，最后还是走的slave，没有开启事务，怀疑是执行顺序的问题，有没有好的解决办法
springboot初始化bean
![image](https://user-images.githubusercontent.com/22850723/211968607-3a42143b-4913-4d38-991e-a6e9848ac04e.png)

**Comment by kevinliukaiwen** [comment]
> 项目里配置了MasterSlaveAutoRoutingPlugin，默认就是读写分离，读走从库，写走主库，但是我想某条读sql走主，设置了service的方法@ds("master")，最后还是走的slave，没有开启事务，怀疑是执行顺序的问题，有没有好的解决办法 springboot初始化bean ![image](https://user-images.githubusercontent.com/22850723/211968607-3a42143b-4913-4d38-991e-a6e9848ac04e.png)

或者换个思路讲，当同时配置了主从分离和手动指定DS数据源，手动指定的优先级应该高于主从分离设置，应该按照手动指定的数据源去路由

**Comment by kevinliukaiwen** [comment]
> > 项目里配置了MasterSlaveAutoRoutingPlugin，默认就是读写分离，读走从库，写走主库，但是我想某条读sql走主，设置了service的方法@ds("master")，最后还是走的slave，没有开启事务，怀疑是执行顺序的问题，有没有好的解决办法 springboot初始化bean ![image](https://user-images.githubusercontent.com/22850723/211968607-3a42143b-4913-4d38-991e-a6e9848ac04e.png)
> 
> 或者换个思路讲，当同时配置了主从分离和手动指定DS数据源，手动指定的优先级应该高于主从分离设置，应该按照手动指定的数据源去路由

我去看了下源码，底层是通过ThreadLocal设置数据源，用的是push（addFirst）和poll(pollFirst)方法,实际是先进后出，是为了多数据源依赖调用吗

**Comment by huayanYu** [comment]
建议自己改插件.,就几行代码

**Comment by kevinliukaiwen** [comment]
> 建议自己改插件.,就几行代码

后面会考虑新增类似功能吗，这种是很高频的使用场景，比如正常读写主从分离，缓存失效需要强制读主刷新缓存
