### ISSUE TITLE
duruid配置项time-between-connect-error-millis无效

### ISSUE THREAD

**Issue by Shawn0Parker** [baomidou/dynamic-datasource-spring-boot-starter#487]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.3.5

dynamic-datasource-spring-boot-starter Version(required): 3.4.0

# Describe what happened

dynamic-datasource配置druid的time-between-connect-error-millis项无效

Expected Result:

数据源配置：time-between-connect-error-millis: 6000
<img width="660" alt="image" src="https://user-images.githubusercontent.com/29766620/225792110-01c64ae4-a389-453d-bfcd-fc1b525b2884.png">

Actual Result:

结果仍然为默认的500
<img width="538" alt="image" src="https://user-images.githubusercontent.com/29766620/225792026-b422c946-da28-4eee-b4d6-0191a48c6c2f.png">

# Steps to reproduce

- Step 1 
dynamic-datasource配置druid的time-between-connect-error-millis=6000

- Step 2 

启动应用，捕获 DruidDataSource，查看对应该参数timeBetweenConnectErrorMillis的值

- Step 3 

发现值仍为druid默认值500

**Comment by huayanYu** [comment]
1断点调试, 2尝试升级3.5.2

**Comment by huayanYu** [comment]
等待4.0.0
