### ISSUE TITLE
dynamic-datasource 缺失自定义加密数据源的配置

### ISSUE THREAD

**Issue by tapingtiangu** [baomidou/dynamic-datasource-spring-boot-starter#488]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): Oracle JDK 1.8.0_251

SpringBoot Version(required): 2.7.7

dynamic-datasource-spring-boot-starter Version(required):3.6.1

druid Version(optional):1.2.15

# Describe what happened

Expected Result:
动态数据源能实现 password-callback配置，配置步骤如下：
1.application.properties添加配置：
spring.datasource.dynamic.druid.password-callback=com.xxx.datasource.configure.DbPasswordCallback

2.通过继承com.alibaba.druid.util.DruidPasswordCallback，实现自定义解密数据源
public class DbPasswordCallback extends DruidPasswordCallback {

    @Autowired
    private RsaConf rsaConf;

    @Override
    public void setProperties(Properties properties) {
        System.out.println("------------------> DbPasswordCallback:setProperties()");
        if (properties.containsKey("password") && properties.get("password") != null) {
            String password = String.valueOf(properties.get("password"));
            try {
                System.out.println("开始解密.........");
                String dbPassword = RSADecryptUtils.decrypt(password, rsaConf.getPrivateKey());
                setPassword(dbPassword.toCharArray());
            } catch (Exception e) {
                System.out.println("解密失败");
            }
        }
        super.setProperties(properties);
    }
}

Actual Result:

配置上述期望的1,2步骤后，无法进行自定义解密数据源，断点调试发现不支持，但实际druid-datasource是支持配置自定义解密数据源的。

**Comment by huayanYu** [comment]
可以使用内置的扩展实现Event来实现加密.
