### ISSUE TITLE
解密报错

### ISSUE THREAD

**Issue by 7757** [baomidou/dynamic-datasource-spring-boot-starter#490]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 
1.8

SpringBoot Version(required): 2.7.10

dynamic-datasource-spring-boot-starter Version(required):3.6.0

druid Version(optional):

# Describe what happened
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/48285391/230568387-20de2a2b-9cc3-4b84-8bca-3e854edfd475.png">
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/48285391/230568582-06d488a5-ec99-4bf5-8481-73c604ddfffc.png">

Expected Result
升级了springboot 等级 突然就不能用了

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by gxmgxm** [comment]
您好 ，这里是高相猛，很高兴收到您的邮件 。

**Comment by 7757** [comment]
org.jasypt.exceptions.EncryptionOperationNotPossibleException

**Comment by 7757** [comment]
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/48285391/230569022-2766e5cb-1c43-4f4c-bbcb-e9bc32fede54.png">
直接导致初始化失败 我至今还没找到原因

**Comment by huayanYu** [comment]
我也找不到原因,建议提交一个最小化的复现项目.重新提交PR
