### ISSUE TITLE
我这边验证了，是因为我升级了druid版本，由之前的1.2.16升级为1.2.17报错

### ISSUE THREAD

**Issue by 1065609785** [baomidou/dynamic-datasource-spring-boot-starter#495]
# Enviroment

JDK Version(required): 
 JDK17

SpringBoot Version(required):  
springboot3.0.6

dynamic-datasource-spring-boot-starter Version(required):
3.6.1
druid Version(optional):
1.2.17

# Describe what happened
我这边验证了，是因为我升级了druid版本，由之前的1.2.16升级为1.2.17后，报错

Expected Result:

![132d3fb80b281e2e55593e7f0defcc0b](https://user-images.githubusercontent.com/10160605/234181611-6128ba4f-a7d3-468e-b0be-b4e5b72f17a9.png)

**Comment by huayanYu** [comment]
等待4.0.0
