### ISSUE TITLE
集成shardingsphere-jdbc失败？

### ISSUE THREAD

**Issue by 0556heqing** [baomidou/dynamic-datasource-spring-boot-starter#499]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required):  jdk17

SpringBoot Version(required):  springboot 3.0.6

dynamic-datasource-spring-boot-starter Version(required): 3.6.1

druid Version(optional): 

# Describe what happened

com.baomidou:dynamic-datasource-spring-boot-starter:3.6.1
与
org.apache.shardingsphere:shardingsphere-jdbc-core-spring-boot-starter:5.2.1
不兼容？ 

springboot升级至3后。
shardingsphere 需要升级到 5.2.x版本。
dynamic 看起来需要升级到 3.6.x版本。

3.6.x 与 5.2.x 添加配置后项目无法启动？

**Comment by huayanYu** [comment]
无法?怎么个无法法?

**Comment by 0556heqing** [comment]
不好意思，解决了。原因是，shardingSphere 5.1之后需要用 shardingSphereDataSource 替换 shardingDataSource
