### ISSUE TITLE
请问这样配置多数据源是否有误

### ISSUE THREAD

**Issue by a364176773** [baomidou/dynamic-datasource-spring-boot-starter#50]
# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
1.5.19
Starter Version(required):
2.5.4
# Describe

> spring:
> datasource:
> dynamic:
> primary: master #设置默认的数据源或者数据源组,默认值即为master
> datasource:
> master:
> username: root
> password: 17xs2015
> driver-class-name: com.mysql.jdbc.Driver
> url: jdbc:mysql://192.168.14.67:33306/17bbt
> slave_1:
> username: root
> password: 17xs2015
> driver-class-name: com.mysql.jdbc.Driver
> url: jdbc:mysql://192.168.14.67:33307/17bbt
> dbcp2:
> initial-size: 6
> min-idle: 3
> max-wait-millis: 60000
> validation-query: select 'x'
> time-between-eviction-runs-millis: 60000
> soft-min-evictable-idle-time-millis: 30000
> test-on-borrow: false
> test-on-return: false
> test-while-idle: true
> connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
> 

service:
`@Service(version = "1.0.0", interfaceClass = IFrontUserSelectService.class) @Transactional @DS("slave") public class FrontUserSerlectServiceImpl extends ServiceImpl<FrontUserMapper, FrontUser> implements IFrontUserSelectService {
`
请问这样是不是使用mp自带的通用方法就直接是从库里查询的?
还有能否在logger输出的sql的时候顺带也输出对应的数据源名称?

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
1. 不支持事物 @Transactional 
2. 不能在logger输出的sql的时候顺带也输出对应的数据源名称,底层方法动不了.

**Comment by a364176773** [comment]
@huayanYu  请问大神,那我这样配置多数据源是否有误,是不是 mp自带的通用查询全部就也是这个从库了?还有就是为什么不支持事务@transactional?求指点,因为我就一个主库从库,微服务目前就一个provider跟消费者,没有做集群什么的

**Comment by a364176773** [comment]
@huayanYu  求大神解答

**Comment by a364176773** [comment]
@huayanYu
