### ISSUE TITLE
支持子线程继承主线程的数据源code

### ISSUE THREAD

**Issue by zhnagheng** [baomidou/dynamic-datasource-spring-boot-starter#502]
![image](https://github.com/baomidou/dynamic-datasource-spring-boot-starter/assets/50563791/aaa7d64c-60d9-418e-8a0b-a8093d252366)

LOOKUP_KEY_HOLDER采用NamedInheritableThreadLocal支持父子线程异步调用的场景，子线程继承父线程的数据源code
![image](https://github.com/baomidou/dynamic-datasource-spring-boot-starter/assets/50563791/ecfca9f4-84b1-4005-a66d-a1359dfe1322)

**Comment by huayanYu** [comment]
3.1.0就是用的它,大面积反馈问题,线程复用有问题

**Comment by zhnagheng** [comment]
线程复用有问题是什么样的场景呢，具体是什么问题


张恒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/dynamic-datasource-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 下午4:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/dynamic-datasource-spring-boot-starter] 支持子线程继承主线程的数据源code (Issue #502)





 
3.1.0就是用的它,大面积反馈问题,线程复用有问题

**Comment by zhnagheng** [comment]
我们公司在使用NameThreadLocal的时候，反而很多地方出问题了，子线程没有使用主线程的数据源，导致使用的默认的master数据源，然后数据都错乱了




张恒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/dynamic-datasource-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 下午4:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/dynamic-datasource-spring-boot-starter] 支持子线程继承主线程的数据源code (Issue #502)





 
3.1.0就是用的它,大面积反馈问题,线程复用有问题

**Comment by zhnagheng** [comment]
能说明下具体出问题的场景吗，我们也好避避雷




张恒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/dynamic-datasource-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 下午4:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/dynamic-datasource-spring-boot-starter] 支持子线程继承主线程的数据源code (Issue #502)





 
不会改的了,建议你直接改源码.

**Comment by zhnagheng** [comment]
你现在就这样用ThealLocal也会引起很多问题，难道不知道吗




张恒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/dynamic-datasource-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 下午4:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/dynamic-datasource-spring-boot-starter] 支持子线程继承主线程的数据源code (Issue #502)





 
不会改的了,建议你直接改源码.

**Comment by huayanYu** [comment]
https:zhuanlan.zhihu.com/p/540651080  具体原理其实我也不太懂,反正当时3.1.0很多用户反馈切换数据源错乱

**Comment by zhnagheng** [comment]
你好，想咨询下我们采用无注解方案，在Filter里面解析前端header传递过来的数据源code来实现手动切换，偶尔会出现切换失败，切换到其他租户数据源的情况，这种情况有啦些大概得原因呢？


版本3.2.0：dynamic-datasource-spring-boot-starter




张恒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/dynamic-datasource-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月21日(星期三) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/dynamic-datasource-spring-boot-starter] 支持子线程继承主线程的数据源code (Issue #502)





 
https:zhuanlan.zhihu.com/p/540651080  具体原理其实我也不太懂,反正当时3.1.0很多用户反馈切换数据源错乱

**Comment by zhnagheng** [comment]
你好，想咨询下我们采用无注解方案，在Filter里面解析前端header传递过来的数据源code来实现手动切换，偶尔会出现切换失败，切换到其他租户数据源的情况，这种情况有啦些大概得原因呢？


我这边初步排查发现切换错误的时候好像是没有使用DynamicRoutingDataSource这个数据源


版本3.2.0：dynamic-datasource-spring-boot-starter




张恒
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "baomidou/dynamic-datasource-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月21日(星期三) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/dynamic-datasource-spring-boot-starter] 支持子线程继承主线程的数据源code (Issue #502)





 
https:zhuanlan.zhihu.com/p/540651080  具体原理其实我也不太懂,反正当时3.1.0很多用户反馈切换数据源错乱
