### ISSUE TITLE
多线程环境下如何传递事务

### ISSUE THREAD

**Issue by ChiMuYuan** [baomidou/dynamic-datasource-spring-boot-starter#509]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required):  
1.8

SpringBoot Version(required): 
2.4.3

dynamic-datasource-spring-boot-starter Version(required):
3.5.0

druid Version(optional):
1.2.8

# Describe what happened
一个save方法开启的事务，save完后调用了一些同步数据和各种通知用的方法。
方法里开了线程池来避免效率问题，但是新线程里拿不到刚save的数据。
因DSTransaction 和spring事务不同不能混用，不知DSTransaction 如何传递事务

Expected Result:
DSTransaction 传递到多线程

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
不支持,你研究下seata吧.
