### ISSUE TITLE
DS注解在Mapper上无效

### ISSUE THREAD

**Issue by zuihou** [baomidou/dynamic-datasource-spring-boot-starter#51]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 
 2.0.3.RELEASE
Starter Version(required):
2.5.3
# Describe
@DS 注解 标注在UserMapper上时， 并且Mapper 继承了Mybatis-plus的BaseMapper, 则只有UserMapper 自己的方法能切换， 从BaseMaper继承下来的方法无法切换数据源。

**Comment by huayanYu** [comment]
你跟一下程序看看, 虽然极其不推荐注解在Mapper上,但是应该也能切换的.

**Comment by zuihou** [comment]
> 你跟一下程序看看, 虽然极其不推荐注解在Mapper上,但是应该也能切换的.

为啥不推荐呢？ 能说下原因吗

**Comment by huayanYu** [comment]
@zuihou  注解一般在实现类上 . 业务切换也是在service上切换数据源好一些.

**Comment by wwjjkk** [comment]
似乎是我理解错原因了，是因为调用方法带了事务注解，导致的数据源切换失败....

**Comment by Audi-A7** [comment]
> 似乎是我理解错原因了，是因为调用方法带了事务注解，导致的数据源切换失败....

确实是因为这个
