### ISSUE TITLE
Failed to determine a suitable driver class

### ISSUE THREAD

**Issue by RuiqianZhang** [baomidou/dynamic-datasource-spring-boot-starter#512]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): JDK17

SpringBoot Version(required): 3.0.4

dynamic-datasource-spring-boot-starter Version(required):4.0.0-B1

druid Version(optional):1.2.16

If there is an exception,or aop invalid,please attach the exception trace:

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (the profiles dev are currently active).

```
Just paste your stack trace here!
```

**Comment by zxuanhong** [comment]
I do the same, using 4.0.0

**Comment by huayanYu** [comment]
https://github.com/dynamic-datasource/dynamic-datasource-samples/tree/master/datasource-samples/druid-sample

@zxuanhong @RuiqianZhang  can u Reproduction on this sample ?

**Comment by zxuanhong** [comment]
@huayanYu The package is wrong, and dynamic-datasource-spring-boot-starter is used

**Comment by huayanYu** [comment]
yes  if you are use sb3+ , now you must use  **dynamic-datasource-spring-boot3-starter**
