### ISSUE TITLE
4.0.0 import文件好像没打到jar里面

### ISSUE THREAD

**Issue by zt9788** [baomidou/dynamic-datasource-spring-boot-starter#522]
Springboot3.1 
org.springframework.boot.autoconfigure.AutoConfiguration.imports 没有打到包里,导致无法自动装配

**Comment by huayanYu** [comment]
听不懂

**Comment by zt9788** [comment]
4.0.0 Springboot3.1 没法@Configuration没法自动装配
看了一下,org.springframework.boot.autoconfigure.AutoConfiguration.imports  这个文件在jar包里面没找到
只有spring.factory文件

**Comment by zt9788** [comment]
抱歉抱歉,忽略忽略,应该引dynamic-datasource-spring-boot3-starter
