### ISSUE TITLE
v4.0.0版本启动报错java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy

### ISSUE THREAD

**Issue by kervin521** [baomidou/dynamic-datasource-spring-boot-starter#524]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 
1.8.0.321
SpringBoot Version(required): 
2.7.13
dynamic-datasource-spring-boot-starter Version(required):
4.0.0
druid Version(optional):
1.2.18
Spring Version(optional):
5.3.28

# Describe what happened

Expected Result:

启动正常

Actual Result:
java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by liuhaichaogithub** [comment]
一样的问题，如公用springboot3的版本就没这个问题了，然后debug，发现找不到beecp相关类，可是我没用这个连接池，引入后又报其他的

**Comment by ZPZP1** [comment]
#518 应该和这个issue是一样的已经有pr了估计老哥还没发版

**Comment by huayanYu** [comment]
4.1.0
