### ISSUE TITLE
v4.1.0版本Oracle启动报错密码不正确

### ISSUE THREAD

**Issue by zzzombie207** [baomidou/dynamic-datasource-spring-boot-starter#526]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 1.8.0_181

SpringBoot Version(required): 2.3.1

dynamic-datasource-spring-boot-starter Version(required):4.1.0

druid Version(optional):1.2.14

# Describe what happened

Expected Result:

正常启动

Actual Result:

ORA-01017: invalid username/password; logon denied
If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce
3.6.1可以正常启动查询数据。应该是数据库连接密码加密配置有问题
- Step 1 
spring.datasource.dynamic.druid.keepAlive = true
spring.datasource.dynamic.druid.useUnfairLock = true
spring.datasource.dynamic.druid.test-while-idle = true
spring.datasource.dynamic.druid.test-on-borrow = false
spring.datasource.dynamic.druid.test-on-return = false
spring.datasource.dynamic.druid.pool-prepared-statements = true
spring.datasource.dynamic.druid.filters = stat,config
spring.datasource.dynamic.primary = master
spring.datasource.dynamic.datasource.master.url = 
spring.datasource.dynamic.datasource.master.username = 
spring.datasource.dynamic.datasource.master.password = 
spring.datasource.dynamic.datasource.master.driver-class-name = oracle.jdbc.OracleDriver
spring.datasource.dynamic.datasource.master.druid.initial-size = 5
spring.datasource.dynamic.datasource.master.druid.max-active = 150
spring.datasource.dynamic.datasource.master.druid.min-idle = 5
spring.datasource.dynamic.datasource.master.druid.max-wait = 1200
spring.datasource.dynamic.datasource.master.druid.min-evictable-idle-time-millis = 1800000
spring.datasource.dynamic.datasource.master.druid.max-pool-prepared-statement-per-connection-size = 20
spring.datasource.dynamic.datasource.master.druid.validation-query = SELECT 1 from dual
spring.datasource.dynamic.datasource.master.druid.public-key = 
- Step 2 

- Step 3

**Comment by huayanYu** [comment]
4.1.1
