### ISSUE TITLE
4.0版本无法获取DruidStatProperties Bean,但3.6版本可以

### ISSUE THREAD

**Issue by jfly-cloud** [baomidou/dynamic-datasource-spring-boot-starter#528]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 
17
SpringBoot Version(required): 
2.7.11
dynamic-datasource-spring-boot-starter Version(required):
4.1.1
druid Version(optional):
1.2.18

# Describe what happened
'com.alibaba.druid.spring.boot.autoconfigure.properties.DruidStatProperties' that could not be found

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
怎么获取的啊？ 给我复现步骤啊

**Comment by jfly-cloud** [comment]
![image](https://github.com/baomidou/dynamic-datasource-spring-boot-starter/assets/61487624/7ec196b9-6533-40d1-a728-6efb01501618)
![image](https://github.com/baomidou/dynamic-datasource-spring-boot-starter/assets/61487624/feadec96-c3de-40d5-8cc0-c324bb43f4ad)

**Comment by huayanYu** [comment]
druid-spring-boot-3-starter没有启动,  我这边也没适配. 等待4.1.2,预计今天发版
