### ISSUE TITLE
使用动态数据源@DS时，如何通过databaseid调用对应ds的select SQL

### ISSUE THREAD

**Issue by birdle-joe** [baomidou/dynamic-datasource-spring-boot-starter#56]
当前mp版本：3.0.6

需求：系统支持mysql，oracle两套数据库，两套数据库共用一套mapper。
mapper中定义两个select语句，分别给两个数据库使用。

目前已经通过@DS能够实现数据库切换，但未能实现切换数据库后，调用mapper中指定的select语句，请问该需求如何实现？

原想通过databaseid实现调用对应的select sql，所以在项目中做了以下配置，这样配置databaseId后每次输出的均为mysql的sql，但我service中实际上已经将数据库切换成oracle数据库了，

以下为系统配置：

1.注册bean
`  @Bean
    public DatabaseIdProvider getDatabaseIdProvider (){
        DatabaseIdProvider databaseIdProvider = new VendorDatabaseIdProvider();
        Properties p = new Properties();
        p.setProperty("SQL Server", "sqlserver");
        p.setProperty("Oracle", "oracle");
        p.setProperty("MySQL", "mysql");
        databaseIdProvider.setProperties(p);
        return databaseIdProvider;
    }`
2.在mapper中指定databaseId
`<select id="searchDefault"  parameterType="com.sa.jcsc.desktop.service.dto.TestEntitySearchFilter"  resultMap="TestEntityResultMap"  databaseId="oracle">
		select t1.testentityid from testentity t1 where 1=2
	</select>`
`<select id="searchDefault"  parameterType="com.sa.jcsc.desktop.service.dto.TestEntitySearchFilter"  resultMap="TestEntityResultMap"  databaseId="mysql">
		select t1.testentityid from testentity t1 where 1=3
	</select>`

**Comment by huayanYu** [comment]
研究了下,需要mybatis底层支持.  
DatabaseIdProvider 本意是你可能会在将来切换数据库,而不是支持一次性多个数据库

**Comment by fangjinuo** [comment]
通过自定义 sqlsessiontemplate + sessionfactory 可以达到该目的

**Comment by linwaiwai** [comment]
Override the MybatisConfiguration should be easiest way.

```java
@Bean
	public MybatisPlusPropertiesCustomizer mybatisPlusPropertiesCustomizer() {
		return properties -> {
			DynamicMybatisConfiguration configuration = new DynamicMybatisConfiguration();
			properties.setConfiguration(configuration);
		};
	}
```

```java
@Slf4j
public class DynamicMybatisConfiguration extends com.baomidou.mybatisplus.core.MybatisConfiguration {
	@Override
	public String getDatabaseId() {
             // get dataDatabaseId from thread using dataSourceType 
        } 
```

using _databaseId in the mapper xml
```xml
<if test="_databaseId == 'clickhouse'">
</if>
```

not 

```xml
<update id="updateDetectEndpointIds" databaaseId="clickhouse">
</update>
```

if you still want to using the attribute way, take a look at XMLMapperBuilder.java , sqlElement is the key function . Find a way to change the logic of configuration.getDatabaseId() . We should add some logic that passing the current databaseType to getDatabaseId for there is no database type info in the XMLMapperBuilder . This should work , Good luck or pay me .

```java
private void sqlElement(List<XNode> list) {
    if (configuration.getDatabaseId() != null) {
      sqlElement(list, configuration.getDatabaseId());
    }
    sqlElement(list, null);
  }
```

**Comment by gxmgxm** [comment]
您好 ，这里是高相猛，很高兴收到您的邮件 。
