### ISSUE TITLE
多租户多库能实现吗

### ISSUE THREAD

**Issue by gatspy** [baomidou/dynamic-datasource-spring-boot-starter#6]
现在项目多租户是基于`database per tenant`， dao用的是mp, 服务发现和配置用`consul`。
用这个动态数据源能实现多租户数据库的切换吗?

**Comment by huayanYu** [comment]
@gatspy 难点不在于切换，切换很简单。 我可以支持spel表达式传进来当前用户id，然后自己根据是哪个租户跳到哪张表。   难点在于现在都是预加载数据源，你这个是想要动态加载数据源。

**Comment by gatspy** [comment]
@huayanYu 谢谢您的回复。
是的啊。没法发用注解的方式。现在也考量了下，只有用macat实现了？

**Comment by huayanYu** [comment]
最新版2.3.0支持了 ，可以看一下文档的高级部分

**Comment by huayanYu** [comment]
@gatspy 最新版2.3.2。 支持spel，根据租户来切换数据源。 支持session header 和spel中获取
