### ISSUE TITLE
jta

### ISSUE THREAD

**Issue by zhmingGIT** [baomidou/dynamic-datasource-spring-boot-starter#62]
如何支持jta分布式数据源事务呢

**Comment by huayanYu** [comment]
不支持任何事物

**Comment by zhmingGIT** [comment]
试验过 可以    

@Autowired
    private JtaTransactionManager transactionManager;

    public void addTx() throws Exception {
        TransactionManager tx = this.transactionManager.getTransactionManager();
        tx.begin();
        try {
//            userService.addUser();
//            salaryService.addSalary();
          
            ((UnionService)(AopContext.currentProxy())).addUser();
            ((UnionService)(AopContext.currentProxy())).addSalary();
            int i = 1 / 0;
            tx.commit();
        } catch (Exception e) {
            tx.rollback();
            throw e;
        }
    }

    @DS("slave_1")
    public void addUser() {
        User user = new User("didi", 5);
        userMapper.insert(user);
    }

    @DS("slave_2")
    public void addSalary() {
        Salary salary = new Salary(1,5);
        salaryMapper.insert(salary);
    }


<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jta-atomikos</artifactId>
        </dependency>
