### ISSUE TITLE
在 Mapper 上使用 @Ds 注解时，不兼容 Mybatis-Plus 3.1.0 版本。

### ISSUE THREAD

**Issue by pinocc** [baomidou/dynamic-datasource-spring-boot-starter#63]
# Enviroment

JDK Version(required): JDK8

SpringBoot Version(required): 2.0.4.RELEASE

Starter Version(required):2.4.0

Mybaits-Plus Version: 3.1.0

# Describe
在 Mapper 上使用 @Ds 注解时，不兼容 Mybatis-Plus 3.1.0 版本。
MyBatis-Plus 中 com.baomidou.mybatisplus.core.override.PageMapperProxy 类已经被移除，导致获取 mybatis-plus的 支持失败，认为工程中使用的 Mybatis. 
具体方法为： com.baomidou.dynamic.datasource.DynamicDataSourceClassResolver#DynamicDataSourceClassResolver

**Comment by huayanYu** [comment]
更新版本
