### ISSUE TITLE
添加druid的数据源，不能获取创建连接是否成功

### ISSUE THREAD

**Issue by siminx** [baomidou/dynamic-datasource-spring-boot-starter#67]
# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
2.0.9
Starter Version(required):
2.5.5
# Describe
DynamicDataSourceCreator类里的createDruidDataSource方法，如果创建连接失败，异常直接处理掉了，方法调用者不能知道连接是否创建成功。

![image](https://user-images.githubusercontent.com/22373408/60482633-ec178c00-9cc4-11e9-81a0-3f2debb97c00.png)

Expected Result: 
能抛出异常或者返回的dataSource有某个属性表示是否创建成功。
Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
下个版本会把异常抛出

**Comment by huayanYu** [comment]
2.5.6会抛出异常
