### ISSUE TITLE
Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required

### ISSUE THREAD

**Issue by guohongtao0214** [baomidou/dynamic-datasource-spring-boot-starter#69]
# Enviroment
JDK Version(required): 1.8

SpringBoot Version(required): 2.1.6

Starter Version(required):2.5.5

# Describe
纯粹的多数据源，从一个源查，加到另一个数据源里面
![image](https://user-images.githubusercontent.com/38782106/60795783-e9260b00-a19e-11e9-8cbd-6063adca916e.png)

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 
在serviceImpl的截图如下

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
参数配置异常不够多,无法判断. 先试试2.5.4,并补充具体的配置和截图

**Comment by zjl814965454** [comment]
你使用mybatis-spring-boot-starter版本多少
