### ISSUE TITLE
druid filter conf does not effect

### ISSUE THREAD

**Issue by pan3793** [baomidou/dynamic-datasource-spring-boot-starter#7]
# Enviroment

JDK Version: Oracle JDK 1.8.0_162

SpringBoot Version: 2.0.5.RELEASE

Starter Version: 2.2.1 (lastest at 20180919)

# Describe
configurations at spring.datasource.druid.filter.*** does not effect.
Actually there do load and create filter beans, but those filter beans does not inject into druid datasource bean.

# Analyze
both at alibaba original druid-starter & this dynamic stater, loading spring.datasource.druid.filter.*** conf first, but then, 
1. at alibaba original druid-starter, it use DruidDataSourceWrapper to init druid data source, @Autowird inject the filter beans into ds;
2. at this dynamic stater, just invoke setter to set spring.datasource.druid.filter.dynamic.datasource.***.filters strings to ds props (DataSourceFactory line 134),  implicit invoke FilterManager.loadFilter() (DruidAbstractDataSource line 1325), it just **new** a filter object without load any configuration instead of loading bean from spring.

**Comment by huayanYu** [comment]
so it is, but I dont know how to resolve it.. item datasource may need different filter

**Comment by huayanYu** [comment]
the latest 2.2.3 version support global DruidConfiguration.  However,I can not use filterBean, I use DatasourceFactory to create Datasource.  If you have any idea, pls PR
