### ISSUE TITLE
使用baseMapper中自带的没办法正常切换

### ISSUE THREAD

**Issue by iHappinessLife** [baomidou/dynamic-datasource-spring-boot-starter#73]
# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
2.1.4
Starter Version(required):
2.5.5
# Describe
请问下，BaseMapper中的方法没办法切换数据源，自定义的方法却能切换。其中selectCount方法是自定义的，可以正常切换到从库。
问题：其他的方法，在Service无事务，使用baseMapper中自带的没办法正常切换，还是默认用主库。请问这个要怎么解决？

       Integer count = wxCreditOrderMapper.selectCount();
        System.out.println("count===="+count);
        SysUser user = (SysUser) SecurityUtils.getSubject().getPrincipal();
        RowBounds rowBounds = new RowBounds(start,limit);
        EntityWrapper<WxCreditOrder> ew = new EntityWrapper();
        ew.where("status={0} and creator_user_id={1}",new Object[]{WxCreditOrder.STATUS_OK,user.getId()});
        ew.in("trade_status",new Object[]{WxCreditOrder.TRADE_STATUS_PENDING_CHECK, WxCreditOrder.TRADE_STATUS_PENDING_TRANSFER});
        ew.orderBy("create_time",false);
        List<WxCreditOrder> data = wxCreditOrderMapper.selectPage(rowBounds,ew);
        int total = wxCreditOrderMapper.selectCount(ew);
 
        return Json.succ(oper).data("total",total).data("data",data);

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
如何配置的?
注解在哪的?
注解在mapper上的一律自己排查.

**Comment by iHappinessLife** [comment]
下图是自定义的方法：从库有效
![image](https://user-images.githubusercontent.com/37396786/61191750-807be880-a6e0-11e9-8639-a9f3315db4ed.png)
BaseMapper的方案：从库无效
![image](https://user-images.githubusercontent.com/37396786/61191777-bd47df80-a6e0-11e9-926e-9afcc4b02ecd.png)

注解在service类的方法上，service中如果调用mapper中自定义的方法，@DS("slave")有效。如果调用BaseMapper中通用的方法，@DS("slave")不起作用。

**Comment by sunyanghah** [comment]
同问啊。
mapper继承了baomidou的basemapper
![image](https://user-images.githubusercontent.com/32818464/61519859-8571cc80-aa3f-11e9-8401-fdad07a0e099.png) 
分别调用自己写的查询与basemapper提供的查询
![image](https://user-images.githubusercontent.com/32818464/61519903-9b7f8d00-aa3f-11e9-94fe-e04e9d68bd60.png)
getNum()执行成功。但是selectById异常
![image](https://user-images.githubusercontent.com/32818464/61520028-e4cfdc80-aa3f-11e9-9dc7-0c45b3f8601b.png)

**Comment by huayanYu** [comment]
无法复现
可以查看示例项目 dynamic-mybatisplus2-sample
UserServiceImpl 取消addUser上的注解 或者改成slave_1
//    @DS("master")
然后跑测试,  可以切换.
