### ISSUE TITLE
2.5.5 也依旧强制依赖spring-web

### ISSUE THREAD

**Issue by anic** [baomidou/dynamic-datasource-spring-boot-starter#75]
2.5.5 也依旧强制依赖spring-web，为何？

下个版本修复

_Originally posted by @huayanYu in https://github.com/baomidou/dynamic-datasource-spring-boot-starter/issues/52#issuecomment-505773362_

**Comment by terrylinzs** [comment]
2.5.5确实还是强依赖web环境，请问什么时候能修复呢

**Comment by huayanYu** [comment]
2.5.6
