### ISSUE TITLE
多数据源情况下怎么分别配置global-config啊?

### ISSUE THREAD

**Issue by yaschiro** [baomidou/dynamic-datasource-spring-boot-starter#8]
采用多数据源的话,假如怎样才能针对两个不同的库来配置  主键类型id-type,db-column-underline 等选项呢?
场景是一个是新开发的库,一个是连接别的公司的数据库不可修改数据库.

**Comment by huayanYu** [comment]
不可能

**Comment by yaschiro** [comment]
请问你是作者一个团队的吗,回答权威的话, 那我只能采用原始的两个MybatisPlusConfig 方案了.以前还没出这个动态数据源时候用的,以为动态的话就不用了

**Comment by huayanYu** [comment]
嗯，权威回答。 你这个场景只能两个mpConfig

**Comment by yaschiro** [comment]
好的,死心了
