### ISSUE TITLE
请问啥时候支持2.1.x啊

### ISSUE THREAD

**Issue by OneJane** [baomidou/dynamic-datasource-spring-boot-starter#80]
# Enviroment

JDK Version(required): 

SpringBoot Version(required): 

Starter Version(required):

# Describe

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by DoyuTu** [comment]
SpringBoot v2.1.5 v2.1.6 is support
