### ISSUE TITLE
再次说明,不支持事务(单库事务支持)

### ISSUE THREAD

**Issue by huayanYu** [baomidou/dynamic-datasource-spring-boot-starter#81]
如果有大牛希望你加入来支持.

**Comment by cfreedomc** [comment]
虽然不支持多数据源事务,但是在多数据源配置下,单数据源的事务 如何让事务生效,发现@DS的注解在@Trasactional后,只能选择默认数据源 connection获取不一致

**Comment by huayanYu** [comment]
@cfreedomc 是支持的.你再测一下,或者给出复现的基础demo,可以参考源码下的示例包下写. 这个问题早有人提出并且验证过,

**Comment by gzbpvi** [comment]
大概的思路：抛弃XA的事务，转为统一管理的事务管理中心，类似分布式事务处理那样。实现过程会有些复杂，坑应该会很多吧。

**Comment by zhangdiandian2016** [comment]
测试了一下，支持在事务外部统一切换数据源，不支持事务内部切换数据源！！！谨记谨记！

**Comment by phoema** [comment]
https://github.com/baomidou/dynamic-datasource-spring-boot-starter/issues/83
