### ISSUE TITLE
动态数据源 无法切换

### ISSUE THREAD

**Issue by yanzhuan051** [baomidou/dynamic-datasource-spring-boot-starter#82]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.x

Starter Version(required):2.1.3.release

# Describe
数据源切换无效,配置了两个 mysql 和 postgresql 都是主库,  使用primary 指定 mysql  或者 postgresql 不会报错,也能正确运行 ,但是 比如我primary : mysql 在 service 实现类中加入@DS
没有效果,而且session中的数据源并没有切换到 postgresql 报错为 table不存在

Expected Result: 

Actual Result: 
 # Steps to reproduce

- Step 1 
spring:
  datasource:
    dynamic:
      primary: mysql
      datasource:
        mysql:
          username: xxx
          password: xxx
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://xx.xx.xx.xx:3306/xx
        postgresql:
          username: root
          password: 123456
          driver-class-name: org.postgresql.Driver
          url: jdbc:mysql://xx.xx.xx.xx:5432/dynamic
        slave_2:
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:postgresql://xx.xx.xx.xx:3308/dynamic

**Comment by huayanYu** [comment]
排查是否加了事务,
自行检查或参考示例项目.
这么基础的切换问题不可能出现.

**Comment by yanzhuan051** [comment]
1.项目就是最简单的项目 没有加任何拦截相关 的东西 
2.现象和#44问题 和很相似 也是 ds是 null ,而且加断点 时候 发现 不会进入DynamicDataSourceAnnotationInterceptor 中 的 determineDatasource方法中

**Comment by huayanYu** [comment]
强制使用cglib代理

**Comment by yanzhuan051** [comment]
问题已经解决了 是公司私服 无法下载 dynamic-datasource jar 这个包我自己在别处下载然后放到本地，然后就缺少了 aop相关 这样注解就无法生效了 加上 spring-boot-starter-aop  就正常了

**Comment by tfwx** [comment]
> 排查是否加了事务,
> 自行检查或参考示例项目.
> 这么基础的切换问题不可能出现.

您好，在使用事务时，发现读写分离插件无法正常工作，是因为事务的原因么？
