### ISSUE TITLE
hope: support master multi-datasource and automatic failover

### ISSUE THREAD

**Issue by DoyuTu** [baomidou/dynamic-datasource-spring-boot-starter#84]
hope:
- support master multi-datasource (no need write load balancing)
- support master multi-datasource automatic failover

**Comment by huayanYu** [comment]
多主支持,master_1,master_2
第二个failover 在考虑

**Comment by DoyuTu** [comment]
I mean multi-data source groups can be multi-master, not just one group support it

**Comment by huayanYu** [comment]
啥意思,你还是说中文吧...

**Comment by DoyuTu** [comment]
不支持名称非master、slave的多主多从模式

**Comment by huayanYu** [comment]
对程序来说只是一个分组,并没有主从概念.
