### ISSUE TITLE
多层数据源嵌套锁定

### ISSUE THREAD

**Issue by zhaojiacan** [baomidou/dynamic-datasource-spring-boot-starter#86]
serverA 开启主库实现更新操作，serviceA中嵌套serviceB查询更新后的数据， 如果serviceB是从库，我希望嵌套中锁定数据库源，serviceB也从主库读取可以吗？

**Comment by huayanYu** [comment]
serverA加事务试试?

**Comment by huayanYu** [comment]
加事务不能锁定么
