### ISSUE TITLE
源码有部分未能理解，请指教

### ISSUE THREAD

**Issue by maodou38** [baomidou/dynamic-datasource-spring-boot-starter#87]
DynamicDataSourceConfigure 该如何使用?

源码中没有注入过这个class，所以理解autoconfig里的最后一段应该不会生效吧。如何基于多种策略自动切换数据源，请指教

**Comment by huayanYu** [comment]
@maodou38 https://gitee.com/baomidou/dynamic-datasource-spring-boot-starter/wikis/pages?sort_id=1030583&doc_id=147063

**Comment by maodou38** [comment]
@huayanYu 谢谢大佬指教
