### ISSUE TITLE
Reason: Failed to determine a suitable driver class

### ISSUE THREAD

**Issue by yuanming8804** [baomidou/dynamic-datasource-spring-boot-starter#88]
datasource:
        sqlserver_1:
          username: sa
          password: "Wind0ws"
          url: jdbc:sqlserver://47.94.110.213:40525;DatabaseName=bserp1
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          #schema: db/schema.sql
          druid: #这里可以重写默认值
            initial-size: 5
          mybatis: 
            mybatis.config-location: classpath:mybatis/mybatis-config.xml
            mapper-locations: classpath:mybatis/mapper/*/*.xml
        sqlserver_2:
          username: sa
          password: "Wind0ws"
          url: jdbc:sqlserver://124.42.123.194:40526;DatabaseName=TIZ_LANDI_TEST
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          druid:
            initial-size: 6
          mybatis: 
            mybatis.config-location: classpath:mybatis/mybatis-config.xml
            mapper-locations: classpath:mybatis/mapper/*/*.xml

**Comment by huayanYu** [comment]
看文档

**Comment by yuanming8804** [comment]
> 看文档

1. application.yml

![image](https://user-images.githubusercontent.com/6120965/63487029-51754580-c4dc-11e9-8590-659aa83c48fa.png)


2.启动配置了
![image](https://user-images.githubusercontent.com/6120965/63487047-5e923480-c4dc-11e9-931f-8a575032bac4.png)
