### ISSUE TITLE
动态加载数据源及不使用注解切换如何支持，如何在事务中切换数据源？

### ISSUE THREAD

**Issue by xiongwei628** [baomidou/dynamic-datasource-spring-boot-starter#9]
# Enviroment

JDK Version: 

SpringBoot Version: 

Starter Version:

# Describe

Expected Result: 
 
Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
不使用注解那使用啥？    第二个问题你可以尝试集成分布式事物

**Comment by xiongwei628** [comment]
@huayanYu 分布式事务实现相关说明吗？

**Comment by huayanYu** [comment]
@xiongwei628 没有,我不会。。。
