### ISSUE TITLE
Reason: Failed to determine a suitable driver class

### ISSUE THREAD

**Issue by yuanming8804** [baomidou/dynamic-datasource-spring-boot-starter#90]
我完全按照文档配置的，麻烦您耐心解答一下，不要直接关问题，谢谢！

1.application.yml

![image](https://user-images.githubusercontent.com/6120965/63528831-3c2d0500-c536-11e9-953d-46a158b4cde9.png)

2.Application
![image](https://user-images.githubusercontent.com/6120965/63528891-55ce4c80-c536-11e9-9a63-33b8a605eaee.png)

3.pom.xml

**Comment by huayanYu** [comment]
文档已经很详细了,遇到基础问题自己排查.
我没从你给你描述里看到什么问题.
需要你自己断点排查
