### ISSUE TITLE
spring boot启动失败,提示'url' attribute is not specified and no embedded datasource could be configured.

### ISSUE THREAD

**Issue by Euthpic** [baomidou/dynamic-datasource-spring-boot-starter#91]
# Enviroment

JDK Version(required): 1.8.0_191

SpringBoot Version(required): 5.1.8.RELEASE

Starter Version(required):2.1.6.RELEASE
mybatis-plus-boot-starter:3.1.2
dynamic-datasource-spring-boot-starter:2.5.6

# Describe
spring boot启动失败,以下为报错信息:

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

以下为我的yml配置:
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          url: jdbc:mysql://192.168.0.1:3306/xxx?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: xxx
          password: xxx
          driver-class-name: com.mysql.jdbc.Driver
        slave:
          url: jdbc:mysql://192.168.0.1:3306/xxx?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: xxx
          password: xxx
          driver-class-name: com.mysql.jdbc.Driver

yml配置改成以前非动态数据源是可以正常启动的,问题应该就是读取yml配置出错导致的,读不到url等属性.我的配置文件是通过profile属性进行切换的:
  profiles:
    active: dev
配置数据源的的文件全称是application-dev.yml,不知道这个会不会有影响.
此外,当我想查看
package com.baomidou.dynamic.datasource.spring.boot.autoconfigure;
public class DynamicDataSourceProperties
的源码时,idea提示library source does not match the bytecode for class,不确定这个是否也会影响(maven仓库使用的阿里云镜像,应该不会下载错吧?)

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3 

------------------------------
补充:
我在查看DynamicRoutingDataSource类的源码时,发现引用了p6spy包的一个类,我的项目原先并没有依赖这个包,但是引入了之后也未能解决问题.此外,library source does not match the bytecode for class应该是使用了lombok的原因,一般不会有影响,只是看不到最终编译的源码.

**Comment by Euthpic** [comment]
![yml](https://user-images.githubusercontent.com/17786366/63739337-64628e00-c8bf-11e9-8203-d9804ead76cd.png)
补充yml截图

**Comment by huayanYu** [comment]
https://gitee.com/baomidou/dynamic-datasource-spring-boot-starter/wikis/pages?sort_id=1030627&doc_id=147063

**Comment by 8debug** [comment]
> https://gitee.com/baomidou/dynamic-datasource-spring-boot-starter/wikis/pages?sort_id=1030627&doc_id=147063

网页挂了

**Comment by freshgeek** [comment]
怎么解决？

**Comment by freshgeek** [comment]
@huayanYu

**Comment by gxmgxm** [comment]
您好 ，这里是高相猛，很高兴收到您的邮件 。
