### ISSUE TITLE
能否给个动态增减数据源的实例？

### ISSUE THREAD

**Issue by zhengzhaojian** [baomidou/dynamic-datasource-spring-boot-starter#92]
# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
2.1.7
Starter Version(required):
2.5.3
# Describe
能否给个动态增减数据源的Demo,你们码云的文档太简单了

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
这文档还简单?....

**Comment by zhengzhaojian** [comment]
public class DemoController {

    @Autowired
    private DataSource DataSource;

    @PostMapping("/addDs")
    public void add(){
        DynamicDatasource dynamicDatasource=(DynamicDatasource) datasource;
        dynamicDatasource.addDataSource(ds,someDatasource);
    }
}

就这么个东西？还是说你们还有其他详细点的文档？

**Comment by KANLON** [comment]
同意，请问文档中DynamicDatasource是哪个类？这个类好像找不到，另外这个datasource应该如果通过用户名和密码创建？
