### ISSUE TITLE
service中调用service方法无法切换数据源

### ISSUE THREAD

**Issue by liunewshine** [baomidou/dynamic-datasource-spring-boot-starter#93]
# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
2.1.6
Starter Version(required):
2.5.6
# Describe

![image](https://user-images.githubusercontent.com/7698511/63915432-a7ac3080-ca68-11e9-8a20-ad82e12115ae.png)

Controller中调用get1()和get2(),可以正常获取数据.但是service中同时调用无法正常切换.
可以是两个事物,应该能正常获取才对

**Comment by liunewshine** [comment]
`@Service
public class DeptServiceDb1 extends ServiceImpl<BaseMapper<Dept>, Dept> implements IService<Dept> {

    @Autowired
    private DeptMapper deptMapper;

    public void get() {
        get1();
        get2();
    }

    @DS("db1")
    public void get1() {
        Dept dept = deptMapper.selectById(2);
        System.out.println(dept.getTenantId());
    }

    @DS("db2")
    public void get2() {
        Dept dept = deptMapper.selectById(2);
        System.out.println(dept.getTenantId());
    }

}`

**Comment by rebyss** [comment]
不走代理切面不生效！手动切吧

liunewshine <notifications@github.com>于2019年8月29日 周四14:27写道：

**Comment by liunewshine** [comment]
怎么手动切呢,有demo吗

**Comment by rebyss** [comment]
不是提供了holder吗？去看一下源码

liunewshine <notifications@github.com>于2019年8月29日 周四17:08写道：

**Comment by liunewshine** [comment]
好的

**Comment by xuzongbao** [comment]
请问最后怎么解决的？

**Comment by liunewshine** [comment]
@xuzongbao DynamicDataSourceContextHolder.java 这个类可以用代码切换线程,不过我最后没有这个库,这个库对事务的支持太弱,几乎没法用. 可以自己通过spring自带的DataSourceTransactionManager实现多数据源,用@Transactional("master")切换事务
