### ISSUE TITLE
与shiro集成报错

### ISSUE THREAD

**Issue by ynp** [baomidou/dynamic-datasource-spring-boot-starter#96]
`public class DynamicDataSourceAutoConfiguration {

  @Autowired
  private DynamicDataSourceProperties properties;
。。。
  @Bean
  @ConditionalOnMissingBean
  public DynamicDataSourceCreator dynamicDataSourceCreator() {
    DynamicDataSourceCreator dynamicDataSourceCreator = new DynamicDataSourceCreator();
    dynamicDataSourceCreator.setDruidGlobalConfig(properties.getDruid());
`
properties 报空指针，无法注入。
shiro 在非DynamicDataSource 环境运行正常；
DynamicDataSource在非shiro环境运行正常；
不知道您那有集成shiro成功的工程或者样例没有？

**Comment by neozo** [comment]
> `public class DynamicDataSourceAutoConfiguration {
> 
> @Autowired
> private DynamicDataSourceProperties properties;
> 。。。
> @bean
> @ConditionalOnMissingBean
> public DynamicDataSourceCreator dynamicDataSourceCreator() {
> DynamicDataSourceCreator dynamicDataSourceCreator = new DynamicDataSourceCreator();
> dynamicDataSourceCreator.setDruidGlobalConfig(properties.getDruid());
> `
> properties 报空指针，无法注入。
> shiro 在非DynamicDataSource 环境运行正常；
> DynamicDataSource在非shiro环境运行正常；
> 不知道您那有集成shiro成功的工程或者样例没有？

我也遇到了这个问题，你解决了没有

**Comment by neozo** [comment]
应该是配置有冲突，我在启动类上加了这个就可以， 具体原因不明
`@SpringBootApplication(exclude = {ShiroAnnotationProcessorAutoConfiguration.class, DruidDataSourceAutoConfigure.class})
`
🤣

**Comment by zhaogituser** [comment]
這倆個無關，不會影響。

**Comment by xxyben** [comment]
我也遇到了这个问题，还没解决，有没有人会解决呀？？？？

**Comment by huayanYu** [comment]
相关问题查看文档， 楼上问题新版会解决。
