### ISSUE TITLE
如果我使用HibernateDaoSupport在Service增加注释能否自动匹配

### ISSUE THREAD

**Issue by 181079342** [baomidou/dynamic-datasource-spring-boot-starter#98]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.0.9

Starter Version(required):2.0.9

# Describe
我在springboot2 中采用了HibernateDaoSupport，需要指定SessionFactory，
如果我在Service增加DS注解，能否自动匹配里面dao的SessionFactory

@Service("commonServImplSac")
@DS("db1")
public class CommonServImpl implements CommonServ{
          @Autowired
           public CommonDao commonDao;
}

public class CommonDaoImpl extends HibernateDaoSupport implements CommonDao{

}
例如这样，service 中的 commonDao能否自动指定对应的sessionFactory

**Comment by huayanYu** [comment]
没玩过hibernate  你这不是一测就知道了么?

动手测测吧
