### ISSUE TITLE
数据源配置支持自动从微服务配置中心获取吗?

### ISSUE THREAD

**Issue by sangyuan6122** [baomidou/dynamic-datasource-spring-boot-starter#99]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 
2.1.6
Starter Version(required):
2.5.6
# Describe
数据源配置支持自动从微服务配置中心获取吗?
例如，在DynamicDataSourceProperties上加@RefreshScope

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
你可以尝试改造源码本地测试或者提交PR, 我没用过cloud.

**Comment by dingyongli2019** [comment]
我这边也有这个需求，配置中心用的是Nacos。 @sangyuan6122 你有好的解决方案吗

**Comment by flyingglass** [comment]
SpringCloud热更新是通过ContextRefresher来自动刷新的：
-  对于ConfigurationProperties和@RefreshScope都是可以自动刷新的
-  SpringCloud Bus 和 Config 只是封装暴露了endpoint而已。

**Comment by JJdog** [comment]
我这边也有这样的需求
